import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const adjugrejn25 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2020/09/Ad25-e1600674893122.png"
          rel="attachment wp-att-3229"
        ></a>
        Биологически активные вещества природного происхождения, поверхностно
        активные полимеры, фитогормоны, питательные вещества, гумектанты,
        натуральные криопротекторы.
      </strong>
      Адьюгрейн® 25% ПАВ для обработки семян зерновых и технических культур
      Предназначен для предпосевной обработки семян с целью улучшения посевных
      качеств, повышения жизнеспособности целевых микроорганизмов
      микробиологических препаратов, повышения эффективности действия пестицидов
      и агрохимикатов, снятия стресса и нормализации ростовых процессов при
      обработке химическими пестицидами, повышения засухо- и морозоустойчивости
      всходов. Препаративная форма: вязкая непрозрачная суспензия.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Способствует лучшему закреплению инокулянтов, протравителей и других
          компонентов на семени;
        </li>
        <li>
          Сохраняет жизнеспособность микроорганизмов (инокулянтов) на семени до
          3-х недель;
        </li>
        <li>
          Улучшает посевные качества семян (энергию прорастания и всхожесть),
          стимулирует рост и развитие растений;
        </li>
        <li>
          Повышает морозостойкость на начальных этапах роста, ускоряет
          прорастание семян и развитие корневой системы при низких температурах;
        </li>
        <li>
          Снижает потери эффективности биопрепаратов вследствие разложения и
          смывания;
        </li>
        <li>
          Стимулирует развитие ассоциативной и симбиотической сапротрофной
          микрофлоры в ризосфере и ризоплане растений;
        </li>
        <li>
          Дает возможность обрабатывать семена заблаговременно (15 дней до
          посева).
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Поверхностно-активные полимеры создают на поверхности семян и листьях
      растений дышащую пленку, которая удерживает влагу, предотвращает смыв
      действующих веществ биопрепаратов, пестицидов и агрохимикатов. Действие
      активных компонентов биологических препаратов продлевается за счет
      содержания в препарате элементов питания.
      <h3>Норма расхода</h3>
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Норма расхода, л/т</strong>
            </td>
            <td>
              <strong>Способ, время, особенности применения</strong>
            </td>
          </tr>
          <tr>
            <td>Зерновые, технические культуры</td>
            <td>1,0</td>
            <td>
              Предпосевная обработка семян. Расход рабочей жидкости - 10 л/т.
              При приготовлении баковых смесей включают в состав готовой рабочей
              жидкости.
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      <strong>Упаковка:</strong> 5 л.
    </div>
  );

  return (
    <>
      <Head>
        <title>Адьюгрейн 25% - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Адьюгрейн 25%" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default adjugrejn25;
