import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const adjugrejn = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/09/Ad-e1600439346703.png"
        rel="attachment wp-att-3215"
      ></a>
      <strong>Композиция полисахаридов природного происхождения.</strong>
      Адьюгрейн® ПАВ для обработки семян СОИ, НУТА, ЧЕЧЕВИЦЫ. Предназначен для
      заблаговременной обработки семян бобовых культур (соя, горох, нут,
      чечевица, фасоль и др.) с целью сохранения жизнеспособности
      микроорганизмов на семени и предотвращения воздействия неблагоприятных
      факторов окружающей среды. Препаративная форма: жидкость
      светло-коричневого цвета.
      <h3>Механизм действия</h3>
      Поверхностно-активные полимеры образуют на поверхности семени дышащую
      пленку, предотвращающую смыв активных компонентов средств защиты растений
      (химических и биологических).
      <h3>Преимущества</h3>
      <ul>
        <li>
          Способствует лучшему закреплению инокулянтов, протравителей и других
          компонентов на семени;
        </li>
        <li>
          Сохраняет жизнеспособность микроорганизмов (инокулянтов) на семени до
          3-х недель;
        </li>
        <li>
          Снижает потери эффективности биопрепаратов вследствие разложения и
          смывания;
        </li>
        <li>
          Дает возможность высевать обработанные микроорганизмами семена в почву
          с минимальным запасом влаги;
        </li>
        <li>
          Эффективно работает в условиях засухи, при высокой кислотности и
          температуре почвы.
        </li>
      </ul>
      <h3>Норма расхода</h3>
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Норма расхода, л/т</strong>
            </td>
            <td>
              <strong>Способ, время, особенности применения</strong>
            </td>
          </tr>
          <tr>
            <td>Соя, нут и чечевица</td>
            <td>1,0</td>
            <td>
              Предпосевая обработка семян. Расход рабочей жидкости - 10 л/т
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      <strong>Упаковка:</strong> «Bag-in-Box» – полипропиленовый пакет объемом 2
      л. в картонной коробке.
    </div>
  );

  return (
    <>
      <Head>
        <title>Адьюгрейн - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Адьюгрейн" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default adjugrejn;
