import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const adjugrejn10 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2020/09/adjugrejn-10-e1600439890453.png"
          rel="attachment wp-att-3224"
        ></a>
        Композиция полисахаридов природного происхождения
      </strong>
      Адьюгрейн® 10% Поверхностно-активное вещество (ПАВ) для обработки по
      вегетации. Предназначен для закрепления биологических и химических СЗР, на
      листовой поверхности растений. Защищает от смывания. Способствует
      пролонгации действия препаратов, снижает потери влаги растением.
      Препаративная форма: вязкая жидкость светло-коричневого цвета.
      <h3>Преимущества</h3>
      <ul>
        <li>Образует биополимерную пленку;</li>
        <li>
          Удерживает биопрепараты и химические СЗР на листовой поверхности.
        </li>
        <li>
          Снижает потери эффективности в следствии разложения и смывания
          биопрепаратов;
        </li>
        <li>
          Способствует более полному усвоению микро и макроэлементов при
          внекорневой подкормке.
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Поверхностно-активные полимеры образуют на поверхности листа дышащую
      пленку, которая удерживает биопрепараты, химические СЗР и влагу.
      <h3>Способ приготовления рабочей жидкости</h3>
      Препарат разводят в воде в соотношении 1:1 , тщательно перемешивают до
      образования однородного раствора. Полученный маточный раствор применяют
      для приготовления баковых смесей с биопрепаратами, микроэлементами и
      химическими СЗР. При использовании с другими препаратами порядок
      приготовления смеси следующий: химические протравливатели, микроэлементы,
      водный раствор Адьюгрейна 10%, а после тщательного перемешивания –
      Респекта 25%, Бактофорт.
      <h3>Норма расхода</h3>
      <table>
        <tbody>
          <tr>
            <td>
              <strong> Культура</strong>
            </td>
            <td>
              <strong>Норма расхода, % (л/га)</strong>
            </td>
            <td>
              <strong>Способ, время, особенности применения</strong>
            </td>
          </tr>
          <tr>
            <td>
              Зерновые, Зернобобовые, Технические, Овощные, Сады, Виноградники
            </td>
            <td>0,1 рабочего раствора (1л на 1000 л воды)</td>
            <td>
              ОБработка растений в период вегетации. При приготовлении баковых
              смесей включают в состав готовой рабочей жидкости.
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      Упаковка: 1,0 л, 5,0 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Адьюгрейн 10% - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Адьюгрейн 10%" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default adjugrejn10;
