import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const alfafeniksks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/flutriafol/">Флутриафол</a> 250
        г/л
      </strong>
      Cистемный фунгицид превентивного и куративного действия для защиты от
      широкого спектра возбудителей болезней растений.
      <h2>Преимущества</h2>
      <ul>
        <li>Широкий спектр лечебного и защитного действия.</li>
        <li>
          Быстро проникает в растение и обеспечивает надежную защиту от внешней
          и внутренней инфекции.
        </li>
        <li>Гибкость в применении (независимо от фазы развития культуры).</li>
        <li>Устойчив к смыванию дождем уже через час после опрыскивания.</li>
        <li>Имеет длительный период защитного действия (до 6-8 недель).</li>
        <li>Нефитотоксичний.</li>
        <li>Применение многократно окупает затраты на обработку.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,5</span>
            </td>
            <td>
              <span>Пшеница озимая</span>
            </td>
            <td>
              <span>
                Ржавчина бурая, ржавчина стеблевая, ржавчина желтая, мучнистая
                роса, септориоз, пиренофороз
              </span>
            </td>
            <td>
              <span>
                Опрыскивание в период вегетации в фазы появления флагового листа
                – начало колошения.
              </span>
              <span>Расход рабочей жидкости – до 300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/alfahimgrupp/">АльфаХимгрупп</a>
      <strong>Упаковка</strong>: 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Альфа Феникс, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Альфа Феникс, КС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default alfafeniksks;
