import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const alfastim = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/Alfasti-ber.jpeg"></a>
        Стимулятор роста растений
      </strong>
      Активирует наиболее важные метаболические реакции, регулирует усвоение и
      использование питательных элементов, стимулирует выделения корневой
      системы и повышает проницаемость клеточных стенок корней. Обладает
      иммуностимулирующим действием. Обладает свойствами антиокислителя и
      адаптогена. Повышает устойчивость к водному дефициту, солевому и
      химическому стрессам, воздействию атак патогенов и вредителей.
      <h2>Состав (вес/объём/%)</h2>
      Тритерпеновые кислоты 100 г/л L-аминокислоты 50 г/л Карбогидраты 50 г/л
      Ауксино-цитокининовый комплекс 10 г/л Мембраноактивные вещества 10 г/л
      Витамины (B1, B7, PP) 5 г/л
      <h2>Назначение</h2>
      <ul>
        <li>Снижает осыпание завязей.</li>
        <li>Стимулирует рост корневой системы.</li>
        <li>Увеличивает площадь листовой поверхности.</li>
        <li>
          Ускоряет энергию прорастания и повышает полевую всхожесть семян.
        </li>
        <li>Активизирует собственные защитные функции растения.</li>
        <li>
          Активирует свободноживущие азотофиксаторы и эндомикоризные
          фосфорфиксирующие организмы.
        </li>
        <li>Активирует симбиотическую микрофлору.</li>
        <li>Восстанавливает активный рост после природных стрессов.</li>
        <li>Интенсифицирует обменные процессы.</li>
        <li>Повышает продуктивное кущение и активизирует фотосинтез.</li>
        <li>Увеличивает азотофиксирующую активность клубеньковых бактерий.</li>
        <li>Увеличивает коэффициент использования минеральных удобрений.</li>
        <li>Усиливает транспорт агрохимикатов в клетки растения.</li>
        <li>Увеличивает количество и качество плодов.</li>
      </ul>
      <h3>Оптимальные дозировки</h3>
      30-50 мл/га при расходе рабочего раствора 50-300 л.
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/tochka-rosta/">Точка Роста</a>
      <strong>Упаковка: </strong>1 л
    </div>
  );

  return (
    <>
      <Head>
        <title>АЛЬФАСТИМ® - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="АЛЬФАСТИМ®" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default alfastim;
