import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const alfadikvatvr = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/category/dikvat/">
        <strong>Дикват 150 г/л</strong>
      </a>
      Предуборочный десикант для подсолнуха и рапса.
      <h2>Преимущества препарата</h2>
      <ul>
        <li>
          Чрезвычайно быстрое действие препарата и убедительный результат.
        </li>
        <li>
          Возможность начать сбор урожая на 10 дней раньше обычных сроков.
        </li>
        <li>Дает возможность получить семена с низкой влажностью.</li>
        <li>Уничтожает вегетирующие сорняки.</li>
        <li>
          Не оказывает отрицательного влияния на качество семян, не изменяет его
          кислотно- жировой состав.
        </li>
        <li>Низкие затраты на проведение десикации.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>2 2 (А)</td>
            <td>Подсолнечник</td>
            <td>Десикация</td>
            <td>
              Опрыскивание посевов в начале побурения корзинок. Расход рабочей
              жидкости –200-300 л/га, при авиаобработке – 50-100 л/га
            </td>
          </tr>
          <tr>
            <td>2 2 (А)</td>
            <td>Рапс яровой и озимый</td>
            <td>Десикация</td>
            <td>
              Опрыскивание посевов при побурении семян в стручках среднего
              яруса. Расход рабочей жидкости –200-300 л/га, при авиаобработке –
              50-100 л/га
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/alfahimgrupp/">Альфахимгрупп</a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Альфа-Дикват, ВР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Альфа-Дикват, ВР"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default alfadikvatvr;
