import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const alfostab = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/Snimok-ekrana-2021-01-28-v-19.26.28.jpg"></a>
        Фосфид алюминия 560 г/кг
      </strong>
      Препарат эффективен против насекомых и клещей: долгоносики амбарный,
      рисовый и кукурузный, хрущак мучной (виды), рыжий мукоед, капровый жук,
      кожеед ветчинный, мукоед темный и суринамский, зерновой точильщик, жук
      табачный, козявка мавританская, зерновка фасолевая, притворяшка
      австралийский, мучной малый хрущяк, огневка амбарная, огневка тропическая,
      моль зерновая, клещ амбарный, клещ домашний, клещ гнилостный. Препарат
      действует на грызунов, проникающих на склад извне.
      <h2>Преимущества</h2>
      Эффективен против вредителей запасов, кроме клещей.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>
                5 г/м<sup>3</sup>
              </span>
            </td>
            <td>
              <span>Незагруженные зернохранилища</span>
            </td>
            <td>
              <span>Насекомые - вредители запасов (кроме клещей)</span>
            </td>
            <td>
              <span>
                Фумигация при температуре воздуха выше 15 °С. Экспозиция - 5
                суток. Произведение концентрации на время экспозиции ПКЭ - 25
                г•ч/м<sup>3</sup>. Допуск людей и загрузка складов после полного
                проветривания и при содержании фосфина в воздухе рабочей зоны -
                не выше ПДК.
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>9 г/т</span>
            </td>
            <td>
              <span>
                Зерно продовольственное, семенное, фуражное насыпью в складах, в
                силосах элеваторов и затаренное в мешки под пленкой.
              </span>
            </td>
            <td>
              <span>Насекомые - вредители запасов (кроме клещей)</span>
            </td>
            <td>
              <span>
                Фумигация при температуре зерна выше 15 °С. Экспозиция 5
                суток. ПКЭ 25 г•ч/м<sup>3</sup>. Дегазация не менее 10 сут.
                Реализация при остатке фосфина не выше МДУ. Допуск людей после
                полного проветривания и при содержании фосфина в воздухе рабочей
                зоны не выше ПДК
              </span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производство: </strong>ЗемлякоФФ
      <strong>Упаковка: </strong>1 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Алфос, ТАБ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Алфос, ТАБ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default alfostab;
