import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const alkantara = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Среднеранний заразихоустойчивый гибрид с максимальной устойчивостью к
      засушливым условиям. Надежный результат в условиях экстремальной засухи.
      Тип гибрида: Устойчивый к новым расам заразихи Группа спелости:
      Среднеранний Назначение: Линолевый Масличность: 49-51% Высота растений:
      140-160 см Устойчивость к расам заразихи: A–G Технология возделывания:
      Классическая
      <table>
        <tbody>
          <tr>
            <td>
              <strong> Преимущество</strong>
            </td>
            <td>
              <strong>Рекомендации по технологии</strong>
            </td>
          </tr>
          <tr>
            <td>
              Максимальная устойчивость к засухе в портфеле Сингенты. Очень
              быстрый старт на начальных этапах развития растения. Раннее
              цветение позволяет избежать стресса высоких температур. Порог
              стерилизации пыльцы равен 35°С, что на 2-3°С выше стандартов
              рынка. Пригоден для малозатратного земледелия.
            </td>
            <td>
              Пластичен к срокам сева. Стабильный результат даже в условиях
              бедных почв, пригоден для малозатратного земледелия. Избегать
              загущения посевов.
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>АЛЬКАНТАРА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="АЛЬКАНТАРА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default alkantara;
