import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const amitsidbor = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/wp-content/uploads/2021/04/berkanabio-amicid-bor.jpeg"></a>
      Амицид Бор – это препарат на основе аминокислот, содержащий высокую
      концентрацию бора в легкодоступной для растений форме, и усиленный
      росторегуляторами. Препарат применяется по вегетации посредством листовых
      подкормок. Амицид Бор предназначен для листовых обработок растений. При
      необходимости препарат так же может выступать, как корректор содержания
      бора в питательных растворах систем гидропоники.
      <h2>Состав</h2>N (азот) – 64 г/л В (бор) – 150 г/л L-аминокислоты – 50 г/л
      Гидроксикарбоновые кислоты – 40 г/л Кислотность: рН 1% раствора: 6,0-9,0
      Плотность: 1,32–1,42 г/см3 при 18°C.
      <h3>Преимущества препарата</h3>
      <ul>
        <li>Совместимость с большинством пестицидов и удобрений.</li>
        <li>Удобная форма – жидкость, идеально растворимая в воде.</li>
        <li>Высокая концентрация бора.</li>
        <li>
          Повышенная доступность элемента бора для растений за счет аминокислот
          и глюконовой кислоты.
        </li>
        <li>Антистрессовый эффект.</li>
        <li>Ростостимулирующие свойства.</li>
        <li>Максимальная поддержка цветения и плодообразования.</li>
      </ul>
      <h3>Способы применения и сроки</h3>
      Применение в период закладки плодовых почек способствует максимальной
      реализации генетического потенциала культуры. Применение в момент
      бутонизации – начала цветения способствует максимальной завязываемости
      плодов. Применение в фазу роста и налива урожая способствует максимальному
      накоплению сахаров и пластических веществ. Применение перед похолоданием
      (возвратными заморозками) повышает холодоустойчивость. Применение в
      условиях недостатка влаги повышает засухоустойчивость растений.
      <h3>Нормы расхода и применение</h3>
      Некорневая обработка сахарной свеклы в момент роста корнеплода и
      накопления сахаров – 0,4-1,5 л/га; Некорневая обработка подсолнечника в
      момент закладки корзинки и в начале цветения – 0,4–1,3 л/га; Некорневая
      обработка рапса в момент развития корневой системы и в момент бутонизации
      – 0,4–1,3 л/га; Некорневая обработка зернобобовых культур в начале
      цветения и накопление белков в семенах – 0,3–1,0 л/га; Некорневая
      обработка овощных культур 0,3–1,3 л/га; Некорневая обработка
      плодово-ягодных культур – 0,5–2,0 л/га; Некорневая обработка прочих с/х
      культур при наличии дефицита бора – 0,3-1,3 л/га; Некорневая обработка при
      температурных стрессах с целью повышения устойчивости растений к высоким
      или низким температурам – 0,5-1,0 л/га. Кратность обработок – 1-4
      обработки за сезон в зависимости от культуры, но не чаще, чем 1 раз в 10
      дней.
      <em>
        «АМИЦИД БОР» ЗА СЧЕТ СВОЕГО СОСТАВА ОБЛАДАЕТ ПОВЫШЕННОЙ ЭФФЕКТИВНОСТЬЮ В
        ЖАРКИЙ ЗАСУШЛИВЫЙ ПЕРИОД
      </em>
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/elitnye-agrosistemy/">
        Элитные Агросистемы
      </a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Амицид Бор - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Амицид Бор" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default amitsidbor;
