import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const anakondake = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_anakonda-ke.jpg"></a>
        <a href="https://berkanabio.ru/category/s-metolahlor/">С-Метолахлор</a>{" "}
        960 г/л
      </strong>
      Высокоэффективный довсходовый гербицид для борьбы с однолетними злаковыми
      и некоторыми двудольными сорняками.
      <h3>Спектр действия препарата</h3>
      Почвенный и довсходовый гербицид для защиты посевов свеклы, кукурузы,
      подсолнечника, сои и рапса от однолетних злаковых и некоторых двудольных
      сорняков.
      <h3>Механизм действия</h3>
      Сельскохозяйственные культуры требуют особого внимания на стадии раннего
      развития, когда особенно велика и опасна конкуренция сорняков за питание,
      влагу и свет. Механизм действия гербицида Бегин как раз и заключается в
      блокировании процесса отрастания сорняков. У злаковых сорняков действующее
      вещество проникает через колеоптиль, при этом росток скручивается и вслед
      за этим гибнет. У двудольных сорняков действующее вещество попадает через
      семядоли, также вызывая их гибель. Таким образом, поглощение препарата
      происходит в фазу прорастания сорняков, вызывая их гибель еще до появления
      всходов.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>1,3-1,6</span>
            </td>
            <td>
              <span>
                Кукуруза (на зерно), соя, подсолнечник, рапс яровой, свекла
                сахарная
              </span>
            </td>
            <td>
              <span>Однолетние злаковые и некоторые двудольные сорняки</span>
            </td>
            <td>
              <span>
                Опрыскивание до посева или до всходов культуры. В засушливых
                условиях рекомендуется мелкая заделка препарата (на глубину не
                более 5 см).
              </span>
              <span>Расход рабочей жидкости - 200-400 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/neoport/">Neoport</a>
      <strong>Упаковка: </strong>20 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Анаконда, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Анаконда, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default anakondake;
