import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const anovi = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LIDEA</strong>
      Ранний гибрид. Стабильный и высокоурожайный гибрид. Высокая устойчивость к
      холодам и полеганию. Оптимальный агрономический профиль. ФАО 180 Тип
      зерна: кремнисто-зубовидный Особенности гибрида: Анови рекомендуется
      заготавливать на корнаж. Гибрид позволяет получить ранний урожай и
      предотвратить проявления микотоксинов. Хорошая толерантность к фузариозу
      обеспечивает идеальное санитарное состояние. Высокая концентрация энергии
      и хорошие вкусовые качества зерна способствуют улучшению конверсии корма
      при использовании в кормлении свиней. Концентрированная энергия для
      высокой производительности в кормовых рационах для молочных хозяйств или
      откормочных площадок.
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Агрономический профиль</strong>
            </td>
            <td>
              <strong>Преимущества</strong>
            </td>
          </tr>
          <tr>
            <td>
              Начальные темпы роста: отлично Устойчивость к позднему полеганию:
              хорошо Толерантность к пыльной головне: отлично Толерантность к
              фузариозу початка: отлично Влагоотдача: быстрая
            </td>
            <td>
              Стабильный и высокоурожайный гибрид. Высокая устойчивость к
              холодам и полеганию. Оптимальный агрономический профиль.
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>АНОВИ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="АНОВИ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default anovi;
