import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const aqualisnpk128312mgome = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/25kg-Aqualis-12-8-312MgOME-240x376-196x265-1.png"
        rel="attachment wp-att-3313"
      ></a>
      Финальная калийная марка с низким содержанием фосфора. Применяется в конце
      вегетации и в предуборочный период. Обеспечивает ускоренной созревание,
      повышение качества продукции. Высокое содержания калия для ускоренного
      созревания, прочной и красивой кожуры на плодах большего размера. Азот
      преимущественно в нитратной форме. Магний и микроэлементы для полноценного
      созревания урожая.
      <h3>Преимущества продуктов</h3>
      <ul>
        <li>100% растворимость в воде;</li>
        <li>
          Улучшает вкусовые качества, товарный вид и сроки хранения продукции;
        </li>
        <li>Комплекс микроэлементов: B, Cu, Mn, Zn, Fe, Mo в составе</li>
        <li>Cu, Mn, Zn, Fe - в хелатной форме;</li>
        <li>Синергетический эффект при использовании с КАС-32;</li>
        <li>Повышают сахаристость корнеплодов;</li>
        <li>Повышают устойчивость к стрессовым факторам;</li>
      </ul>
      <h3>Состав питательных веществ</h3>
      <table>
        <tbody>
          <tr>
            <td>
              <ul class="composition-list">
                <li>
                  <span class="composition-element">
                    Азот общий (N), не менее{" "}
                  </span>
                  <span class="composition-percent">12,2%</span>
                </li>
                <li>
                  <span class="composition-element">
                    Общие фосфаты в пересчете на P2O5, не менее{" "}
                  </span>
                  <span class="composition-percent">8%</span>
                </li>
                <li>
                  <span class="composition-element">Калий, не менее </span>
                  <span class="composition-percent">31%</span>
                </li>
                <li>
                  <span class="composition-element">Сера, не менее </span>
                  <span class="composition-percent">3%</span>
                </li>
                <li>
                  <span class="composition-element">
                    Оксид магния, не более (MgO){" "}
                  </span>
                  <span class="composition-percent">2%</span>
                </li>
              </ul>
            </td>
            <td>
              <span class="composition-element">Микроэлементы:</span>
              <span class="sub-element">B </span>
              <span class="sub-percent">0,02%</span>
              <span class="sub-element">Cu </span>
              <span class="sub-percent">0,005%</span>
              <span class="sub-element">Mn </span>
              <span class="sub-percent">0,005%</span>
              <span class="sub-element">Zn </span>
              <span class="sub-percent">0,01%</span>
              <span class="sub-element">Fe </span>
              <span class="sub-percent">0,07%</span>
              <span class="sub-element">Mo </span>
              <span class="sub-percent">0,004%</span>
            </td>
          </tr>
        </tbody>
      </table>
      <h3>Норма расхода</h3>
      Зерновые 2-5 кг/га Плодово-ягодные 1-5 кг/га Овощи 3-5 кг/га
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/evrohim/">ЕвроХим</a>
      <strong>Упаковка:</strong> 25 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Aqualis NPK 12-8-31+2 MgO+МЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Aqualis NPK 12-8-31+2 MgO+МЭ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default aqualisnpk128312mgome;
