import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const aqualis311384mgome = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/25kg-Aqualis-3-11-384MgOME-240x376-196x265-1.png"
        rel="attachment wp-att-3324"
      ></a>
      Специальная калийная марка с низким содержанием азота. Марка, созданная
      специально для теплиц и гидропонных систем. Бесхлорный состав позволяет
      использовать на любых, даже самых чувствительных культурах. Низкое
      содержание азота позволяет не стимулировать развитие вегетативной массы, а
      высокое содержание калия и фосфора обеспечивает налив и созревание плодов.
      Микроэлементы в хелатной форме позволяют быстро и полноценно обеспечить
      растение всеми нужными для развития компонентами. Обеспечивает получение
      качественного урожая для длительного хранения без потери свежести.
      <h3>Преимущества</h3>
      <ul>
        <li>100% растворимость в воде;</li>
        <li>
          Улучшает вкусовые качества, товарный вид и сроки хранения продукции;
        </li>
        <li>Комплекс микроэлементов: B, Cu, Mn, Zn, Fe, Mo в составе;</li>
        <li>Cu, Mn, Zn, Fe - в хелатной форме;</li>
        <li>Низкое содержание азота идеально для овощных культур;</li>
        <li>Повышают сахаристость корнеплодов;</li>
        <li>Повышают устойчивость к стрессовым факторам;</li>
      </ul>
      <h3>Состав</h3>
      <table>
        <tbody>
          <tr>
            <td>
              Азот общий (N), не менее 3% Общие фосфаты в пересчете на P2O5, не
              менее 11% Калий, не менее 38% Сера, не менее 11% Оксид магния, не
              более (MgO) 4%
            </td>
            <td>
              Микроэлементы B 0,02% Cu 0,005% Mn 0,005% Zn 0,01% Fe 0,07% Mo
              0,004%
            </td>
          </tr>
        </tbody>
      </table>
      Зерновые 2-5 кг/га Сахарная свекла 2-5 кг/га Овощи 3-5 кг/га
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/evrohim/">ЕвроХим</a>
      <strong>Упаковка:</strong> 25 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Aqualis® 3-11-38+4MgO+МЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Aqualis® 3-11-38+4MgO+МЭ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default aqualis311384mgome;
