import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const aqualis202020me = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/09/25kg-Aqualis-20-20-20ME-240x376-196x265-1.png"
        rel="attachment wp-att-3279"
      ></a>
      Равновесная марка с микроэлементами поможет поддержать рост и развитие
      культуры в течение всей вегетации. Оказывает антистрессовое воздействие во
      время неблагоприятных погодных условий или после применения пестицидов.
      <h3>Преимущества</h3>
      <ul>
        <li>100% растворимость в воде;</li>
        <li>Подходят для подкормок растений на всех фазах развития;</li>
        <li>Комплекс микроэлементов: B, Cu, Mn, Zn, Fe, Mo в составе;</li>
        <li>Cu, Mn, Zn, Fe - в хелатной форме;</li>
        <li>Синергетический эффект при использовании с КАС-32;</li>
        <li>
          Идеальное решение для внекорневых подкормок, подходит для защищенного
          грунта;
        </li>
        <li>Показывает хорошие результаты при фертигации на бедных почвах;</li>
      </ul>
      <h3>Состав питательных веществ</h3>
      <table>
        <tbody>
          <tr>
            <td>
              Азот общий (N), не менее 20,2% Азота аммонийного, не менее 4%
              Азота нитратного, не менее 6% Азота амидного, не менее 10,2% Общие
              фосфаты в пересчете на P2O5, не менее 20,3% Калий, не менее 20,3%
            </td>
            <td>
              Микроэлементы: B 0,02% Cu 0,005% Mn 0,005% Zn 0,01% Fe 0,07% Mo
              0,004%
            </td>
          </tr>
        </tbody>
      </table>
      <h3>Норма расхода и рекомендации</h3>
      Зерновые 2-5 кг/га Плодовые 3-5 кг/га Овощи 3-5 кг/га
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/evrohim/">ЕвроХим</a>
      <strong>Упаковка:</strong> 25 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Aqualis® 20-20-20+МЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Aqualis® 20-20-20+МЭ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default aqualis202020me;
