import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const atlantke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/category/protiokonazol/">
        Протиоконазол 250 г/л
      </a>
      Фунгицид системного действия для защиты зерновых культур.
      <h2>Преимущества препарата</h2>
      <ul>
        <li>Универсальное применение.</li>
        <li>Быстрое начальное действие и долговременная защита.</li>
        <li>Идеальное соотношение между затратами и прибылью.</li>
        <li>Низкие нормы расхода.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,5</td>
            <td>Пшеница яровая и озимая</td>
            <td>
              Мучнистая роса, ржавчина бурая, ржавчина стеблевая, ржавчина
              желтая, гельминтоспориозная пятнистость, септориоз
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>Расход рабочей жидкости - 300 л/га.</span>
            </td>
          </tr>
          <tr>
            <td>0,5</td>
            <td>Ячмень яровой и озимый</td>
            <td>
              Сетчатая пятнистость, темно-бурая пятнистость, мучнистая роса,
              ржавчина карликовая, ринхоспориоз
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>Расход рабочей жидкости - 300 л/га.</span>
            </td>
          </tr>
          <tr>
            <td>0,5</td>
            <td>Рожь озимая</td>
            <td>
              Ржавчина бурая, ржавчина стеблевая, септориоз, ринхоспориоз,
              церкоспореллез, мучнистая роса
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>Расход рабочей жидкости - 300 л/га.</span>
            </td>
          </tr>
          <tr>
            <td>0,5</td>
            <td>Овес</td>
            <td>
              Мучнистая роса, ржавчина корончатая, красно-бурая пятнистость
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>Расход рабочей жидкости - 300 л/га.</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/kchhk/">КЧХК</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Атлант, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Атлант, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default atlantke;
