import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const avantiksekstra75emv = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/klokvintoset-meksil/">
          Клоквинтосет-мексил
        </a>{" "}
        34,5 г/л +{" "}
        <a href="https://berkanabio.ru/category/fenoksaprop-p-etil/">
          Феноксапроп-П-этил
        </a>{" "}
        69 г/л
      </strong>
      Высокоселективный гербицид для послевсходовой обработки ячменя и пшеницы
      против широкого спектра однолетних злаковых сорняков.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Высокая эффективность: активность против широкого спектра злаковых
          сорняков.
        </li>
        <li>Селективность к обрабатываемой культуре: наличие антидота.</li>
        <li>Широкий диапазон сроков применения.</li>
        <li>
          Отсутствие ограничений для применения в севообороте: быстрая
          деградация в почве.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,8-1</span>
            </td>
            <td>
              <span>Пшеница яровая и озимая, ячмень яровой</span>
            </td>
            <td>
              <span>
                Однолетние злаковые сорняки (виды щетинника, просо куриное,
                просо сорное, овсюг, метлица полевая)
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в ранние фазы развития (2-3 листа) сорняков
                независимо от фазы развития культуры (с учетом чувствительности
                сортов). Озимая пшеница обрабатывается весной.
              </span>
              <span>Расход рабочей жидкости - 150-200 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/lysterra/">LYSTERRA</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Авантикс Экстра 7.5, ЭМВ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Авантикс Экстра 7.5, ЭМВ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default avantiksekstra75emv;
