import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const baletke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/07/berkanabio-balet-ke.jpg"></a>
        2,4-Д (малолетучие эфиры С7-С9) 550 г/л + {" "}
        <a href="https://berkanabio.ru/category/florasulam/">Флорасулам</a> 7,4
        г/л
      </strong>
      Высокоэффективный двухкомпонентный гербицид для уничтожения однолетних и
      некоторых многолетних двудольных сорняков в посевах пшеницы яровой и
      озимой и ячменя ярового.
      <h2>Преимущества препарата</h2>
      <ul>
        <li>
          высокоэффективен против трудноискореняемых корнеотпрысковых сорняков;
        </li>
        <li>
          уничтожает такие опасные сорняки как бодяки, вьюнок, молокан, молочай,
          подмаренник, ромашки;
        </li>
        <li>ффективен против сорняков, устойчивых к 2,4-Д и МЦПА;</li>
        <li>широкий спектр действия;</li>
        <li>
          быстрая скорость воздействия: сорняки прекращают рост в течение суток
          после обработки;
        </li>
        <li>
          результат не зависит от погодных условий – не смывается дождем уже
          через час после обработки;
        </li>
        <li>широкое окно применения;</li>
        <li>отсутствие ограничений по севообороту;</li>
        <li>
          прекрасный компонент баковых смесей с сульфонилмочевинами и
          граминицидами;
        </li>
        <li>снижение риска возникновения резистентности у сорняков;</li>
        <li>низкая стоимость гектарной нормы;</li>
      </ul>
      <h3>Норма расхода</h3>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,3-0,5</span>
            </td>
            <td>
              <span>Пшеница озимая и яровая, ячмень яровой</span>
            </td>
            <td>
              <span>
                Однолетние, в т. ч. устойчивые к 2,4-Д и 2М-4Х, и некоторые
                многолетние двудольные сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе кущения культуры и ранние фазы роста
                сорняков. Озимые обрабатываются весной.
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,5</span>
            </td>
            <td>
              <span>Пшеница озимая и яровая, ячмень яровой</span>
            </td>
            <td>
              <span>
                Однолетние, в т. ч. устойчивые к 2,4-Д и 2М-4Х, и некоторые
                многолетние двудольные сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе выхода в трубку (1-2 междоузлия)
                культуры и ранние фазы роста сорняков (с учетом чувствительности
                сортов) в случае преобладания подмаренника цепкого; если
                погодные условия не позволили произвести обработку раньше срока.
                Озимые обрабатывают весной.
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="table_content_wrap">
        <strong>Производитель:</strong>{" "}
        <a href="https://berkanabio.ru/category/lysterra/">LYSTERRA</a>
      </div>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Балет, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Балет, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default baletke;
