import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const bazissts = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/rimsulfuron/">Римсульфурон</a>{" "}
        500 г/кг +{" "}
        <a href="https://berkanabio.ru/category/tifensulfuron-metil/">
          Тифенсульфурон-метил
        </a>{" "}
        250 г/кг
      </strong>
      Послевсходовый гербицид избавляет от большинства известных сорняков,
      засоряющих посевы кукурузы.
      <h2>Преимущества</h2>
      <ul>
        <li>
          эффективно уничтожает и не допускает повторного появления всех
          известных злаковых сорняков;
        </li>
        <li>
          обладает широким спектром действия, применения иных гербицидов не
          требуется;
        </li>
        <li>используется как профилактическая и лечебная мера;</li>
        <li>
          допускается использование гербицида в любую из фаз вегетации сорных
          трав;
        </li>
        <li>
          не фитотоксичен;оказывает благоприятное действие на увеличение
          севооборота;
        </li>
        <li>
          удобен в использовании, легко дозируется и расходуется экономно;
        </li>
        <li>действует быстро, достаточно одной обработки.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,02</span>
            </td>
            <td>
              <span>Кукуруза</span>
            </td>
            <td>
              <span>Однолетние злаковые и двудольные сорные растения</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 2-5 листьев культуры и ранние фазы
                роста сорняков в смеси с 200 мл/га ПАВ Тренд 90, Ж.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,025</span>
            </td>
            <td>
              <span>Кукуруза</span>
            </td>
            <td>
              <span>
                Многолетние и однолетние злаковые и двудольные сорные растения
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 2-5 листьев культуры при высоте
                многолетних злаковых сорняков 10-15 см и ранние фазы роста
                однолетних сорняков в смеси с
              </span>
              <span>200 мл/га ПАВ Тренд 90, Ж.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/djupon/">Дюпон</a>
      <strong>Упаковка: </strong>0,1 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Базис, СТС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Базис, СТС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default bazissts;
