import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const biolipostim = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/234234234biolipostim_10l.png"></a>
        Комплексный препарат для повышения эффективности пестицидов,
        биопрепаратов, жидких и водорастворимых удобрений.{" "}
      </strong>
      Биолипостим по сравнению с химическими аналогами лучше по качеству,
      экологически чистый, биоразлагаемый и без консервантов. Биолипостим
      обладает многофункциональными свойствами: прилипатель, увлажнитель,
      пленкообразователь с клеящими свойствами. Обладает диспергирующим эффектом
      при приготовлении баковых смесей, то есть способствует равномерному
      распределению действующих веществ во всем объеме баковой смеси.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Образует пленку в течение 20-30 минут, независимо от внешних условий
          (кроме наличия в момент обработки сильных осадков)
        </li>
        <li>
          Препятствует стеканию, испарению и потере препаратов с листовой
          поверхности, смыванию дождем, росой, ветром
        </li>
        <li>
          Способствует удержанию средств защиты растений и удобрений 20-30 дней,
          в зависимости от интенсивности осадков
        </li>
        <li>Сохраняет влагу в растениях</li>
        <li>
          Позволяет улучшить смачиваемость и увеличить площадь контакта
          действующего вещества препаратов с листовой поверхностью.
        </li>
      </ul>
      Работает в широком интервале температур от +5 до +30˚С
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Биолипостим - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Биолипостим" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default biolipostim;
