import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const bionekskemi151125 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/Bioneks_Kemi-Rastvorimyy-NPK_Mg_S-151125_1_2_7.jpeg"></a>
        NPK + Mg=15:11:25+1,2%
      </strong>
      Микроэлементы в хелатной форме. Универсальное водорастворимое
      биоактивированное удобрение для корневых и внекорневых подкормок всех
      сельскохозяйственных культур открытого и закрытого грунта.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Микроэлементный комплекс: B-0,025%, Mo-0,005%, Co-0,01%, Cu-0,01%,
          Fe-0,06%, Mn-0,05%, S-6,0%;
        </li>
        <li>Микроэлементы Co, Cu, Mn, Fe в полимерно-хелатной форме;</li>
        <li>Фитоспорин-М - 1%;</li>
        <li>Гигроскопичный порошок и гранулы;</li>
      </ul>
      <h3>Норма расхода</h3>
      При опрыскивании 2-4 кг на 100 - 200 л воды/га; При поливе 2-4 кг на 1000
      л воды.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО &quot;НВП БашИнком&quot;
      </a>
      <strong>Упаковка:</strong> 20 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Бионекс-Кеми (15+11+25) - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Бионекс-Кеми (15+11+25)"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default bionekskemi151125;
