import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const bionekskemi35006007 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/99434piya.png"></a>
        NPK + S + Mg = 35:0:0+6,0+0,7%
      </strong>
      Микроэлементы в хелатной форме.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Микроэлементный комплекс: B-0,7%, Mo-0,005%, Co-0,001%, Cu-0,01%, Zn -
          0,01%, Mn-0,01%;
        </li>
        <li>Микроэлементы Co, Cu, Zn в хелатной форме;</li>
        <li>Фитоспорин-М - 1%;</li>
        <li>БМВ - гуматы - 0,5%</li>
        <li>Гигроскопичный порошок и гранулы;</li>
      </ul>
      Для внекорневой азотно-серной подкормки сахарной свеклы, рапса и других
      с/х культур, с усиленными антистрессовыми, иммуностимулирующими,
      ростоускоряющими и фунгицидными свойствами.
      <h3>Нормы расхода</h3>
      При опрыскивании 2-4 кг на 100 - 200 л воды/га; При поливе 2-4 кг на 1000
      л воды.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО &quot;НВП БашИнком&quot;
      </a>
      <strong>Упаковка:</strong> 20 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Бионекс-Кеми 35:0:0+6,0+0,7 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Бионекс-Кеми 35:0:0+6,0+0,7"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default bionekskemi35006007;
