import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const biopolimikmo = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/111f344bd.png"
        rel="attachment wp-att-3330"
      ></a>
      Для предпосевной (предпосадочной) обработки семян, внекорневой подкормки
      всех сельскохозяйственных культур, чувствительных к недостатку молибдена.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Сбалансированная легкодоступная форма молибдена в виде хелата (EDTA),
          легко проникающего через листовую поверхность, обеспечивает
          максимальное усвоение, предотвращая окисление элементов;
        </li>
        <li>
          Усиленное пролонгированное действие за счет образования эластичной
          пленки на поверхности листа;
        </li>
        <li>Компенсирует нехватку молибдена в почве;</li>
        <li>Активизирует процессы азотфиксации;</li>
      </ul>
      <h3>Норма расхода</h3>
      Совместимость в баковых смесях: совместим с микробиологическими средствами
      защиты растений, регуляторами роста и агрохимикатами.
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Способ внесения</strong>
            </td>
            <td>
              <strong>Доза применения</strong>
            </td>
            <td>
              <strong>Норма расхода рабочего раствора</strong>
            </td>
          </tr>
          <tr>
            <td>Предпосевная обработка семян</td>
            <td>0,3-0,5 л/т</td>
            <td>10 л/т</td>
          </tr>
          <tr>
            <td>Внекорневая подкормка растений</td>
            <td>0,3-0,5 л/га</td>
            <td>50-200 л/га (800-1000 л/га плодово-ягодные культуры)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> 
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Канистра:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Биополимик - Mo - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Биополимик - Mo"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default biopolimikmo;
