import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const biopolimikkompleksnyj = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2019/09/biopolimik_kompleks.jpg"
          rel="attachment wp-att-3462"
        ></a>
        Микроэлементы в хелатной форме
      </strong>
      Содержит набор жизненно необходимых микроэлементов в полимерно - хелатной
      форме с усиленным пролонгированным действием за счет образования
      эластичной полимерной пленки на поверхности листа. Обладает фунгицидными
      свойствами. Предназначен для внекорневых подкормок и предпосевной
      обработки семян.
      <h2>Состав</h2>
      Макроэлементы: NPK=3:0:0 Микроэлементный комплекс: B - 0,2%, Mo - 0,5%, Со
      - 0,1%, S - 6%, Cu - 0,6%, Fe - 3,2%, Mn - 2,0%; Микроэлементы Co, Cu, Mn,
      Fe в полимерно-хелатной форме Фитоспорин-М - 0,5%. БМВ гуматы - 0,5%.
      <h3>Рекомендовано</h3>
      Для внекорневой подкормки всех сельскохозяйственных культур
      <h3>Норма расхода</h3>
      0,3 - 0,5 л/т (обработка семян) 0,3 - 0,5 л/га (обработка посевов)
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО "НВП БашИнком"
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Биополимик (комплексный) - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Биополимик (комплексный)"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default biopolimikkompleksnyj;
