import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const biopolimikco = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/2222833b7fcb57e72d.png"
        rel="attachment wp-att-3333"
      ></a>
      Для предпосевной (предпосадочной) обработки семян, внекорневой подкормки
      всех сельскохозяйственных культур, чувствительных к недостатку кобальта.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Сбалансированная легкодоступная форма кобальта в виде хелата (EDTA),
          легко проникающего через листовую поверхность, обеспечивает
          максимальное усвоение, предотвращая окисление элементов;
        </li>
        <li>
          Усиленное пролонгированное действие за счет образования эластичной
          пленки на поверхности листа;
        </li>
        <li>Компенсирует нехватку кобальта в почве;</li>
        <li>Активизирует процессы азотфиксации;</li>
        <li>Стимулирует нуклеиновый обмен и образование белков;</li>
        <li>
          Снижает разложение хлорофилла в темное время суток и увеличивает
          интенсивность дыхания;
        </li>
        <li>
          Ускоряет темпы образования хлорофилла в листьях, предотвращает
          разрушение хлоропластов;
        </li>
        <li>Повышает иммунитет растения и содержание витамина B12;</li>
        <li>
          Улучшает качество урожая и повышает урожай сельскохозяйственных
          культур
        </li>
      </ul>
      <h3>Норма расхода</h3>
      Совместимость в баковых смесях: совместим с микробиологическими средствами
      защиты растений, регуляторами роста и агрохимикатами.
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Способ внесения</strong>
            </td>
            <td>
              <strong>Доза применения</strong>
            </td>
            <td>
              <strong>Норма расхода рабочего раствора</strong>
            </td>
          </tr>
          <tr>
            <td rowspan="2">Зернобобовые (горох, чечевица, нут, соя)</td>
            <td>Предпосевная обработка семян</td>
            <td>0,2-0,3 л/т</td>
            <td>10 л/т</td>
          </tr>
          <tr>
            <td>Внекорневая подкормка</td>
            <td>0,1-0,2 л/га</td>
            <td>50-200 л/га</td>
          </tr>
          <tr>
            <td>Для всех с/х культур</td>
            <td>Внекорневая и корневая подкормка</td>
            <td>0,1-0,2 л/га</td>
            <td>50-200 л/га 800-1000 л/га</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> 
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Канистра:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Биополимик - Co - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Биополимик - Co"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default biopolimikco;
