import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const bioslipbvzh = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        Бластоспоры штамма Beauveria bassiana (титр не менее 1х108 КОЕ/мл)
      </strong>
      Направленное действие против широкого спектра насекомых-вредителей.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Широкий круг насекомых-вредителей, без явных предпочтений к
          представителям какого-либо одного семейства.
        </li>
        <li>
          Штамм гриба Beauveria bassiana активен в отношении не только личинок,
          но и имаго насекомых, что особенно актуально для борьбы с
          жесткокрылыми вредителями.
        </li>
        <li>Препарат не оказывает влияния на природных энтомофагов.</li>
        <li>
          Пропагулы гриба длительное время сохраняются в окружающей среде, кроме
          того, гриб способен к бессимптомному эндофитному существованию в
          растениях, в отсутствие насекомого-хозяина, что в совокупности
          обеспечивает высокую степень выживаемости гриба в окружающей среде и
          длительный эффект от применения препарата.
        </li>
        <li>
          Срок ожидания отсутствует, плоды, обработанные препаратом готовы к
          употреблению.
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Когда спора гриба оказывается на поверхности насекомого, инициируется
      процесс ее прорастания. Постепенно, преодолевая покровные ткани
      насекомого, гриб попадает в гемолимфу, где начинает активно размножаться.
      Быстрое распространение по телу насекомого достигается благодаря
      способности гриба к образованию бластоспор, каждая из которых является
      самостоятельной инфекционной единицей. Кроме того, находясь в гемолимфе,
      Beauveria bassiana продуцирует различные токсины, в том числе боверицин,
      вызывающие паралич мускулатуры насекомых, вследствие чего последние не
      могут передвигаться и питаться. При этом происходит разрастание мицелия
      гриба, внутри тела насекомого, а незадолго до его гибели — на поверхности
      тела появляются проросшие сквозь покровы конидиеносцы. Гибель насекомого,
      в зависимости от внешних условий и фазы его развития, наступает на 2-7
      сутки
      <h3>Период защитного действия</h3>
      Период защитного действия зависит от погодных условий и плотности и
      восприимчивости популяции вредителя. При влажной погоде пропагулы гриба
      дольше сохраняют жизнеспособность и эффективнее заражают насекомых; более
      того, в таких условиях эффективнее происходит инфицирование незараженных
      вредителей спорами гриба, появившимися после гибели зараженных насекомых.
      В этом случае период защитного действия длится не менее трех недель. В
      сухую солнечную погоду период защитного действия сокращается
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/bionovatik/">Bionovatik</a>
      <strong>Упаковка:</strong> 1 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Биослип БВ Ж - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Биослип БВ Ж" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default bioslipbvzh;
