import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const bogatyjnpk848kalijnyjme = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2020/09/212-bogatyj-848.png"
          rel="attachment wp-att-3258"
        ></a>
        Биоактивированные по молекулярному весу БМВ-гуматы калия Фитоспорин-М –
        титр не менее 1х106 живых клеток и спор на 1 мл.
      </strong>
      <h3>Назначение</h3>
      <ul>
        <li>Для подкормки с/х культур в период вегетации;</li>
        <li>Для омоложения растений во второй половине вегетации;</li>
        <li>
          Для усиления антистрессовыми, ростоускоряющими, иммуностимулирующими и
          фунгцицидными свойствами;
        </li>
      </ul>
      <h3>Преимущество</h3>
      <ul>
        <li>
          Комплексное питание всех с/х культур в виде корневых и внекорневых
          подкормок;
        </li>
        <li>Антистресс, ростоускорение, иммуностимуляция;</li>
        <li>Повышение устойчивости к заболеваниям;</li>
        <li>Повышение качественных показателей с/х продукции;</li>
      </ul>
      <h3>Состав</h3>
      <table>
        <tbody>
          <tr>
            <td>N</td>
            <td>P2O5</td>
            <td>K2O</td>
            <td>B</td>
            <td>S</td>
            <td>Cu</td>
            <td>Zn</td>
            <td>Mn</td>
            <td>Co</td>
            <td>Mo</td>
            <td>Ni</td>
            <td>Li</td>
            <td>Se</td>
            <td>Cr</td>
          </tr>
          <tr>
            <td>8</td>
            <td>4</td>
            <td>8</td>
            <td>0,5</td>
            <td>0,04</td>
            <td>0,01</td>
            <td>0,01</td>
            <td>0,05</td>
            <td>0,002</td>
            <td>0,007</td>
            <td>0,002</td>
            <td>0,0005</td>
            <td>0,0002</td>
            <td>0,0001</td>
          </tr>
        </tbody>
      </table>
      Микроэлементы Cu, Zn, Mn, Co, Ni, Li, Cr- в хелатной форме
      <h3>Норма расхода и применение</h3>
      <table>
        <tbody>
          <tr>
            <td>Внекорневая подкормка растений</td>
            <td>1-3 л/га на 300-800 л. воды</td>
          </tr>
          <tr>
            <td>Корневая подкормка растений</td>
            <td>1,5-2 л/га на 1000 л воды</td>
          </tr>
        </tbody>
      </table>
      <strong>Производство: </strong>
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Богатый NPK 8:4:8 Калийный+МЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Богатый NPK 8:4:8 Калийный+МЭ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default bogatyjnpk848kalijnyjme;
