import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const borogumcuzn = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/Borogum_M_Cu_Zn.jpg"></a>
        Микроэлементы в хелатной форме
      </strong>
      Жидкое борное удобрение, усиленное медью и цинком, содержит набор
      микроэлементов в хелатной форме. Повышает урожайность зерновых культур,
      стимулирует рост корневой системы, повышает устойчивость к болезням, а
      также увеличивает выход семян в семеноводстве.
      <h2>Состав</h2>
      <ul>
        <li>
          Микроэлементный комплекс: B-4,0%, Cu-0,5%, Zn-0,5%;Co - 0,001%, Ni -
          0,001%, Li - 0,0002%, Mo-0,002%, Mn - 0,02%, S - 1,8%, Se - 0,00004%,
          Cr - 0,0002%, полисахара;
        </li>
        <li>Микроэлементы: Co, Cu, Mn, Zn, Cr, Ni, Li в хелатной форме;</li>
        <li>БМВ-гуматы калия, Фитоспорин-М - 1%.</li>
      </ul>
      <h3>Норма расхода</h3>
      0,2 - 0,3 л/т - предпосевная обработка семян 0,8 - 1,0 л/га на 50 - 200 л
      воды - внекорневая подкормка
      <strong>Производитель:</strong> 
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Борогум Cu-Zn - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Борогум Cu-Zn" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default borogumcuzn;
