import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const difilajnke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_difilajn-ke.jpg"></a>
        <a href="https://berkanabio.ru/category/s-metolahlor/">С-Метолахлор</a>{" "}
        960 г/л
      </strong>
      Высокоэффективный довсходовый селективный гербицид против однолетних
      злаковых и некоторых двудольных сорняков в посевах сахарной свеклы,
      кукурузы, подсолнечника, сои, ярового рапса.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Защищает важнейшие культуры в начальный, наиболее критический период
          развития.
        </li>
        <li>
          Высокоэффективен против широкого спектра однолетних злаковых и
          двудольных сорняков.
        </li>
        <li>
          Обладает высокой избирательной способностью в отношении
          рекомендованных культур.
        </li>
        <li>
          Устраняет конкуренцию с сорными растениями в начальный период роста
          растений.
        </li>
        <li>Не оказывает фитотоксичности и последействия.</li>
        <li>Имеет продолжительный период действия.</li>
        <li>
          Прекрасно совмещается с препаратами на основе кломазона – Алгоритмом и
          Коммандом, проявляя синергетический эффект в подавлении сорной
          растительности.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>1,3-1,6</span>
            </td>
            <td>
              <span>Кукуруза, соя, подсолнечник, рапс яровой</span>
            </td>
            <td>
              <span>Однолетние злаковые и некоторые двудольные сорняки</span>
            </td>
            <td>
              <span>
                Опрыскивание почвы до посева или до всходов культуры. В
                засушливых условиях рекомендуется мелкая заделка препарата (на
                глубину не более 5 см).
              </span>
              <span>Расход рабочей жидкости – 200 – 400 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1,3-2</span>
            </td>
            <td>
              <span>Свекла сахарная</span>
            </td>
            <td>
              <span>Однолетние злаковые и некоторые двудольные сорняки</span>
            </td>
            <td>
              <span>
                Опрыскивание почвы до посева или до всходов культуры. В
                засушливых условиях рекомендуется мелкая заделка препарата (на
                глубину не более 5 см).
              </span>
              <span>Расход рабочей жидкости – 200 – 400 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/pestitsidy/fmrus/">ФМРус</a>
      <strong>Упаковка: </strong>20 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Дифилайн, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Дифилайн, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default difilajnke;
