import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const dikvaterrsupervr = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_dikvaterr-super.jpg"></a>
        <a href="https://berkanabio.ru/category/dikvat/">Дикват</a> 150 г/л
      </strong>
      Десикант для решения проблем с неравномерным и медленным созреванием семян
      многих культур.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Ускоряет созревание и делает его равномерным по всем органам растения,
          что позволяет провести уборку в более ранние сроки в любых погодных
          условиях.
        </li>
        <li>Снижает влажность семян, уменьшая затраты на сушку.</li>
        <li>Сокращает потери семян при уборке.</li>
        <li>
          Позволяет приступить к уборке уже через 5-7 дней после обработки.
        </li>
        <li>Не смывается дождем через 10 минут после обработки.</li>
        <li>Кроме культурных растений, высушивает сорняки.</li>
        <li>
          Останавливает развитие и распространение болезней (белая и серая гнили
          подсолнечника, фитофтороз картофеля и многих других).
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>2</span>
            </td>
            <td>
              <span>Подсолнечник</span>
            </td>
            <td>
              <span>Десикация</span>
            </td>
            <td>
              <span>Опрыскивание в начале побурения корзинок.</span>
              <span>
                Расход рабочей жидкости - 200-300 л/га, при авиаобработке
                -50-100 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>2 (А)</span>
            </td>
            <td>
              <span>Подсолнечник</span>
            </td>
            <td>
              <span>Десикация</span>
            </td>
            <td>
              <span>Опрыскивание в начале побурения корзинок.</span>
              <span>
                Расход рабочей жидкости - 200-300 л/га, при авиаобработке
                -50-100 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1</span>
            </td>
            <td>
              <span>Подсолнечник</span>
            </td>
            <td>
              <span>Десикация</span>
            </td>
            <td>
              <span>
                Опрыскивание в начале побурения корзинок в смеси с мочевиной (30
                кг/га).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/gk-zemlyakoff/">
        ЗемлякоФФ
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Дикватерр Супер, ВР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Дикватерр Супер, ВР"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default dikvaterrsupervr;
