import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const dks3006 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>BAYER</strong>
      Простой раннеспелый гибрид зернового направления. Хррошая влагоотдача,
      мощная корневая система, засухоустойчивость и устойчивость к полеганию.
      ФАО 190 Тип зерна: Зубовидный Количество зёрен в початке: 480 шт
      <strong>Растение</strong>
      Облиственный стебель высотой 230-250 см. Полуэректоидное расположение
      листьев.
      <strong>Початок</strong>
      Высота крепления 85-90 см. Цилиндрической формы. Длина 22-26 см. Диаметр
      3,5 - 4,5 см.
      <table>
        <tbody>
          <tr>
            <td colspan="2">
              <strong>Особенности (от 0 до 3)</strong>
            </td>
          </tr>
          <tr>
            <td>
              Начальная энергия роста - 2 Холодостойкость - 2
              Засухоустройчивость - 3 Резистентность к пузырчатой головне - 3
              Резистентность к фузариозу - 3
            </td>
            <td>
              Устойчивость к корневому и стеблевому полеганию - 3 Ремонтантность
              - 3 Влагоотдача - 3 Стабильность и пластичность - 2 Раннее
              цветение - нет
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ДКС 3006 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ДКС 3006" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default dks3006;
