import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const dolchevita = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Lidea</strong>
      Очень ранний гибрид Цветение: Очень ранний Созревание: Очень ранний Высота
      растения: среднее Корзинка: приподнятая Тип гибрида: Линолевый Масличность
      49 %
      <table>
        <tbody>
          <tr>
            <td>Преимущества</td>
            <td>Рекомендации</td>
          </tr>
          <tr>
            <td>
              Классическая технология Очень ранний гибрид с отличной энергией
              всходов Толерантен к основным заболеваниям Отличное опыление
              Низкий риск полегания
            </td>
            <td>
              Густота посева: Зона достаточного увлажнения: 60-65 тыс. семян/га
              Засушливые условия: 55-60 тыс. семян/гаЗаразихоустойчивость:
              Неустойчивый
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Агрономический профиль</strong>
      Толерантность к фомопсису: средне Толерантность к вертициллезу: средне
      Толерантность к белой гнили: средне Толерантность к пепельной гнили:
      отлично Толерантность к ржавчине: средне Устойчивость к полеганию: хорошо
      Начальные темпы роста: хорошие
    </div>
  );

  return (
    <>
      <Head>
        <title>ДОЛЬЧЕВИТА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ДОЛЬЧЕВИТА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default dolchevita;
