import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const dunkanklp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Среднеранний, заразихоустойчивый гибрид для производственной системы
      Clearfield® Plus, отличающийся одновременно высокой стабильностью и
      высоким потенциалом урожайности. Тип гибрида: для производственной системы
      Clearfield® Plus Группа спелости: среднеранний Назначение: линолевый
      Масличность: 49-51% Высота растений: 150-170 см (в зависимости от
      влагообеспеченности) Устойчивость к расам заразихи: A–G Технология
      возделывания: производственная система Clearfield® Plus
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Высокая устойчивость к болезням: склеротинии, пероноспорозу и
              фомопсису защитит урожай в середине и в конце вегетации растения,
              а также снизит потери перед уборкой. Стабильно высокий урожай в
              южных и умеренных широтах Российской Федерации на различных типах
              почв. Гибрид выдерживает максимально допустимые дозы гербицида без
              увеличения вегетационного периода с сохранением потенциала
              урожайности. Высокий выход масла благодаря высоким урожайности и
              масличности.
            </td>
            <td>
              Не использовать адьюванты/микроэлементы/баковые смеси вместе с
              гербицидами для производстенной системы Сlearfield Plus®.
              Использовать для надежного контроля заразихи. Сеять в оптимальные
              сроки. Для лучшего результата применять Бор. Избегать загущения
              посевов.
            </td>
          </tr>
        </tbody>
      </table>
         
    </div>
  );

  return (
    <>
      <Head>
        <title>ДУНКАН КЛП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ДУНКАН КЛП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default dunkanklp;
