import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const ekspressvdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/tribenuron-metil/">
          Трибенурон-метил
        </a>{" "}
        750 г/кг
      </strong>
      Послевсходовый гербицид для борьбы с двудольными сорняками в посевах
      гибридов подсолнечника.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Контролирует широкий спектр сорняков, в том числе амброзию, бодяки,
          осоты и др.
        </li>
        <li>
          Послевсходовое применение позволяет корректировать дозировку, а при
          необходимости готовить баковые смеси.
        </li>
        <li>
          Благодаря послевсходовому применению эффективность не зависит от
          влажности почвы.
        </li>
        <li>
          Обладает высокой селективностью к гибридам подсолнечника фирмы
          «Пионер» с признаком устойчивости Express Sun компании «Дюпон».
        </li>
        <li>
          Не предъявляет ограничений для культур севооборота. Быстро
          разлагается, не оставляя остатков в продукции и окружающей среде.
        </li>
        <li>
          Удобен в транспортировке, хранении и применении. Соответствует
          стандартам качества компании «Дюпон».
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>25-50</span>
            </td>
            <td>
              <span>
                Подсолнечник, устойчивый к трибенурон-метилу (гербициду
                Экспресс, ВДГ 750 г/кг трибенурон-метила)
              </span>
            </td>
            <td>
              <span>
                Однолетние и некоторые многолетние двудольные сорные растения
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе от 2-4 до 6-8 настоящих листьев
                культуры в ранние фазы роста сорных растений (2-4 листа) в
                чистом виде или в смеси с 200 мл/га ПАВ Тренд 90, Ж (90% водный
                раствор этоксилата изодецилового спирта). В случае необходимости
                пересева высевать зерновые культуры. Расход рабочей жидкости –
                200-300 л/га
              </span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/djupon/">Дюпон</a>
      <strong>Упаковка: </strong>0,2 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Экспресс, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Экспресс, ВДГ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default ekspressvdg;
