import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const ekspertnekstks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/desmedifam/">Десмедифам</a> 160
        г/л +{" "}
        <a href="https://berkanabio.ru/category/fenmedifam/">Фенмедифам</a> 160
        г/л
      </strong>
      Гербицид, предназначенный для борьбы с однолетними сорняками на посевах
      сахарной, столовой и кормовой свеклы.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Новая препаративная форма увеличивает эффективность действующих
          веществ препарата.
        </li>
        <li>
          Предназначен для эффективной борьбы с однолетними двудольными
          сорняками, включая виды щирицы, на посевах свеклы.
        </li>
        <li>
          Прекрасно совмещается в баковых смесях с другими гербицидами для
          расширения спектра действия.
        </li>
        <li>Проявляет быстрый гербицидный эффект.</li>
        <li>Не изменяет своих свойств при колебаниях температуры.</li>
        <li>
          Позволяет уменьшить фитотоксическое воздействие препарата на культуру
          даже на самых ранних стадиях ее развития.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>3</span>
            </td>
            <td>
              <span>Свекла сахарная, кормовая</span>
            </td>
            <td>
              <span>Однолетние двудольные сорняки, в т.ч. щирица</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 4 настоящих листьев культуры и
                ранние фазы роста сорняков.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1,5</span>
            </td>
            <td>
              <span>Свекла сахарная, кормовая</span>
            </td>
            <td>
              <span>Однолетние двудольные сорняки, в т.ч. щирица</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 2-4 листьев сорняков (по первой и
                второй волне).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1</span>
            </td>
            <td>
              <span>Свекла сахарная, кормовая</span>
            </td>
            <td>
              <span>Однолетние двудольные сорняки, в т.ч. щирица</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе семядолей сорняков (по первой,
                второй и третьей волне).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/gk-zemlyakoff/">
        ЗемлякоФФ
      </a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Эксперт Некст, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Эксперт Некст, КС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default ekspertnekstks;
