import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const eksperttrioofke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_ekspert-trio-of-ke-.jpg"></a>
        <a href="https://berkanabio.ru/category/desmedifam/">Десмедифам</a> 71
        г/л +{" "}
        <a href="https://berkanabio.ru/category/fenmedifam/">Фенмедифам</a> 91
        г/л +{" "}
        <a href="https://berkanabio.ru/category/etofumezat/">Этофумезат</a> 112
        г/л
      </strong>
      Высокозффективный системный послевсходовый гербицид для борьбы с
      однолетними двудольными сорняками, а также некоторыми однолетними
      злаковыми на сахарной, столовой и кормовой свекле.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Отлично подавляет однолетние двудольные и некоторые злаковые сорняки
          на ранней стадии их развития.
        </li>
        <li>
          Прекрасно совмещается в баковых смесях с другими гербицидами для
          расширения спектра действия.
        </li>
        <li>Проявляет быстрый гербицидный эффект.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>3</span>
            </td>
            <td>
              <span>Свекла сахарная и кормовая</span>
            </td>
            <td>
              <span>
                Однолетние двудольные, в т.ч. щирица, и некоторые однолетние
                злаковые сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 4 настоящих листьев культуры и
                ранние фазы роста сорняков.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1,5</span>
            </td>
            <td>
              <span>Свекла сахарная и кормовая</span>
            </td>
            <td>
              <span>
                Однолетние двудольные, в т.ч. щирица, и некоторые однолетние
                злаковые сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 2-4 листьев сорняков (по первой и
                второй волне с интервалом 7-14 дней).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1</span>
            </td>
            <td>
              <span>Свекла сахарная и кормовая</span>
            </td>
            <td>
              <span>
                Однолетние двудольные, в т.ч. щирица, и некоторые однолетние
                злаковые сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе семядолей сорняков (по первой,
                второй и третьей волне с интервалом 7-14 дней).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/gk-zemlyakoff/">
        ЗемлякоФФ
      </a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Эксперт Трио ОФ, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Эксперт Трио ОФ, КЭ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default eksperttrioofke;
