import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const ekstrahelatmarkaca = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/d36c8a42c1eb3bb07a57d496845a06df.png"
        rel="attachment wp-att-3358"
      ></a>
      Для внекорневой подкормки с/х культур чувствительных к недостатку кальция.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Содержит кальций в максимально доступной форме, наиболее усвояемой
          растениями;
        </li>
        <li>
          Способствуют развитию корневой системы растений и стимулирует
          активность клубеньковых бактерий, фиксирующих азот из воздуха;
        </li>
        <li>
          Повышает устойчивость растений к фитопатогенам путем укрепления
          клеточной стенки;
        </li>
        <li>Уменьшает полегаемость растений;</li>
        <li>Положительно влияет на обмен углеводов и белковых веществ;</li>
        <li>Регулирует водный баланс;</li>
        <li>Улучшает количественные и качественные показатели урожая;</li>
        <li>
          Обеспечивает быстрое и эффективное проникновение микроэлемента через
          листовую поверхность при некорневой подкормке;
        </li>
      </ul>
      <h3>Состав</h3>
      Кальций ( Са), г/кг, не менее 60,0 Азот общий (N), г/кг, не менее 40,0
      Массовая доля влаги, %, не более 12,0
      <h3>Норма расхода</h3>
      Совместим со всеми пестицидами, жидкими и водорастворимыми удобрениями,
      хорошо растворим в рабочем растворе. Внимание! Не смешивать с продуктами,
      производными от неорганических соединений кальция без предварительного
      теста! Готовить маточный раствор, медленно всыпая продукт при
      одновременном помешивании! Примечание: доза препарата может быть увеличена
      до 1,5 кг/га при низком содержании кальция в почве и планировании высокого
      урожая. Для коррекции питания рекомендуется листовая диагностика с
      использованием переносной лаборатории «ФИТОСКАН».
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Способ внесения</strong>
            </td>
            <td>
              <strong>Доза применения</strong>
            </td>
            <td>
              <strong>Норма расхода рабочего раствора</strong>
            </td>
          </tr>
          <tr>
            <td>Зерновые культуры</td>
            <td>Внекорневая подкормка (до и после цветения)</td>
            <td>0,3-0,5 кг/га</td>
            <td>50-200 л/га</td>
          </tr>
          <tr>
            <td>Плодово-ягодные культуры ( виноград)</td>
            <td>Внекорневая подкормка ( до и после цветения)</td>
            <td>0,5-1,2 кг/га</td>
            <td>50-200 л/га 800-1000 л/га</td>
          </tr>
          <tr>
            <td>Картофель, овощные культуры</td>
            <td>Внекорневая и корневая подкормки (до и после цветения)</td>
            <td>0,5-0,8 кг/га</td>
            <td>50-200 л/га 800-1000 л/га</td>
          </tr>
        </tbody>
      </table>
      Примечание: доза препарата может быть увеличена до 1,5 кг/га при низком
      содержании микроэлемента в почве и планировании высокого урожая.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Упаковка:</strong> 5 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Экстра-Хелат марка Ca - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Экстра-Хелат марка Ca"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default ekstrahelatmarkaca;
