import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const ekstrahelatmarkacu = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/444444d8648.png"
        rel="attachment wp-att-3343"
      ></a>
      Для предпосевной обработки семян, внекорневой и корневой подкормок с/х
      культур, чувствительных к недостатку меди и серы. Подавляет возбудителей
      болезней на растениях и в почве.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Содержит медь в максимально доступной форме, наиболее усвояемой
          растениями;
        </li>
        <li>
          Обладает фунгицидными свойствами, подавляет грибковые и бактериальные
          заболевания растений;
        </li>
        <li>
          Принимает участие в усвоении минеральных удобрений, способствует
          лучшему азотному и углеводному обмену;
        </li>
        <li>Увеличивает устойчивость к полеганию;</li>
        <li>Улучшает количественные и качественные показатели урожая;</li>
        <li>
          Обеспечивает быстрое и эффективное проникновение микроэлемента через
          листовую поверхность при некорневой подкормке;
        </li>
        <li>Повышает показатели засухо – и морозоустойчивости растений;</li>
      </ul>
      <h3>Состав</h3>
      Медь (Сu), %, не менее 100,0 Сера (S), %, не менее 50,0 Массовая доля
      влаги, %, не более 12 ,0
      <h3>Норма расхода</h3>
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Время, особенности применения</strong>
            </td>
            <td>
              <strong>Доза применения </strong>
            </td>
            <td>
              <strong>Норма расхода рабочего раствора </strong>
            </td>
          </tr>
          <tr>
            <td>  Зерновые культуры</td>
            <td>
               Предпосевная обработка семян. Внекорневая подкормка ( в фазе
              кущения - флаговый лист)
            </td>
            <td>  0,2-0,3 кг/т 0,3-0,5 кг/га</td>
            <td>     10 л/т 50-200 л/га</td>
          </tr>
          <tr>
            <td>  Картофель, овощные культуры</td>
            <td>
                Предпосевная обработка клубней. Внекорневая и корневая подкормки
              (до и после цветения)
            </td>
            <td>  0,2-0,3 кг/т 0,6 - 1 кг/га</td>
            <td>     10 л/т 50-200 л/га</td>
          </tr>
          <tr>
            <td>  Плодово-ягодные культуры</td>
            <td>  Внекорневая и корневая подкормки (до и после цветения)</td>
            <td>     0,5-0,7 кг</td>
            <td>  50-200 л/га 800-1000 л/га</td>
          </tr>
        </tbody>
      </table>
      <strong>Примечание:</strong> доза препарата может быть увеличена до 1,5
      кг/ га при низком содержании микроэлемента в почве и планирование высокого
      урожая. Мешок, 5 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Экстра-Хелат марка Cu - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Экстра-Хелат марка Cu"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default ekstrahelatmarkacu;
