import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const ekstrahelatmarkamg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a
        href="https://berkanabio.ru/wp-content/uploads/2020/10/555555510dd1.png"
        rel="attachment wp-att-3348"
      ></a>
      Для внекорневой и корневой подкормок с/х культур, чувствительных к
      недостатку магния и серы.
      <h3>Преимущества</h3>
      <ul>
        <li>
          Содержит магний в максимально доступной форме, наиболее усвояемой
          растениями Активно стимулирует обменные процессы (фотосинтез, перенос
          энергии);
        </li>
        <li>
          Благоприятно влияет на усвоение фосфора и других элементов питания;
        </li>
        <li>Активирует окислительно-восстановительные процессы;</li>
        <li>Улучшает количественные и качественные показатели урожая;</li>
        <li>
          Обеспечивает быстрое и эффективное проникновение микроэлемента через
          листовую поверхность при некорневой подкормке;
        </li>
      </ul>
      <h3>Состав</h3>
      Магний (Mg), г/кг, не менее 37 Сера (S), г/кг, не менее 50 Массовая доля
      влаги, %, не более 12,0
      <h3>Норма расхода</h3>
      Совместим со всеми пестицидами, жидкими и водорастворимыми удобрениями,
      хорошо растворим в рабочем растворе. Примечание: доза препарата может быть
      увеличена до 1,5 кг/га при низком содержании магния в почве и планировании
      высокого урожая. Для коррекции питания рекомендуется листовая диагностика
      с использованием переносной лаборатории «ФИТОСКАН».
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Способ внесения</strong>
            </td>
            <td>
              <strong>Доза  применения</strong>
            </td>
            <td>
              <strong>Норма расхода рабочего раствора</strong>
            </td>
          </tr>
          <tr>
            <td>Зерновые культуры</td>
            <td>Внекорневая подкормка ( в фазе кущения- флаговый лист)</td>
            <td>0,3-0,5 кг/га</td>
            <td>50-200 л/га</td>
          </tr>
          <tr>
            <td>Картофель, овощные культуры</td>
            <td>Внекорневая и корневая подкормки ( до и после цветения)</td>
            <td>0,5-1,0 кг/га</td>
            <td>50-200 л/га 800-1000 л/га</td>
          </tr>
          <tr>
            <td>Кукуруза</td>
            <td>Внекорневая подкормка (в фазе 6-7 листьев)</td>
            <td>0,5-0,8 кг/га</td>
            <td>50-200 л/га</td>
          </tr>
          <tr>
            <td>Подсолнечник</td>
            <td>
              Внекорневая подкормка ( в фазе бутонизации, стадия "звезда")
            </td>
            <td>0,5-0,8 кг/га</td>
            <td>50-200 л/га</td>
          </tr>
          <tr>
            <td>Плодово-ягодные культуры</td>
            <td>Внекорневая и корневая подкормки ( до и после цветения)</td>
            <td>0,5-0,7 кг/га</td>
            <td>50-200 л/га 800-1000 л/га</td>
          </tr>
        </tbody>
      </table>
      Примечание: доза препарата может быть увеличена до 1,5 кг/га при низком
      содержании микроэлемента в почве и планировании высокого урожая.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Упаковка:</strong> 5 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Экстра-Хелат марка Mg - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Экстра-Хелат марка Mg"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default ekstrahelatmarkamg;
