import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const eljumismd = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio-eljumis-md.jpg"></a>
        <a href="https://berkanabio.ru/category/mezotrion/">Мезотрион</a> 75 г/л
        +{" "}
        <a href="https://berkanabio.ru/category/nikosulfuron/">Никосульфурон</a>{" "}
        30 г/л
      </strong>
      Новый, легкий в использовании гербицид, созданный для упрощения контроля
      многолетних, однолетних злаковых и двудольных сорняков в посевах кукурузы
      в послевсходовый период.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Комплексный контроль злаковых и двудольных однолетних и многолетних
          сорняков.
        </li>
        <li>
          Наиболее широкое окно применения среди известных гербицидов,
          используемых на кукурузе, – 3–6 (8) листьев культуры.
        </li>
        <li>
          Отсутствие фитотоксичности для культуры даже при позднем применении.
        </li>
        <li>
          Легкость применения: контроль широкого спектра сорняков с помощью
          одного гербицида – нет необходимости искать партнера.
        </li>
        <li>
          Современная формуляция – масляная дисперсия повышает устойчивость
          препарата на обработанной поверхности и его проникновение в растение.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>1-2</span>
            </td>
            <td>
              <span>Кукуруза</span>
            </td>
            <td>
              <span>
                Однолетние и некоторые многолетние двудольные и злаковые сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 3-6 листьев культуры и ранние фазы
                роста сорняков (2-6 листьев у однолетних и при высоте 10-20 см у
                многолетних сорняков). При необходимости пересева в год
                применения можно высевать только кукурузу.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/singenta/">Syngenta</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Элюмис, МД - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Элюмис, МД" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default eljumismd;
