import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const epaa10 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/23423u.jpeg"></a>
        Универсальный биологический липкоген
      </strong>
      Отечественный препарат, полученный на основе микробных полисахаридов
      ксантана или энпосана, с добавлением некоторых безопасных химических
      компонентов, обладает исключительными реологическими свойствами, которые
      стабильны в широком диапазоне температур, рН, концентраций различных
      солей.
      <h2>Применение</h2>
      <ul>
        <li>
          для равномерного нанесения, распределения и удержания на растениях и
          семенах пестицидов, бактериальных препаратов, регуляторов роста и
          микроудобрений, а также их сложных композиций;
        </li>
        <li>
          для повышения на 20-30% эффективности действия пестицидов, элементов
          питания и регуляторов роста растений;
        </li>
        <li>
          для уменьшения поражения сельскохозяйственных культур патогенными
          микроорганизмами;
        </li>
        <li>
          для повышения эффективности агромероприятий и урожайности в целом.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      для обработки семян - 0,15-0,20 л на 1 тонну семян; для опрыскивания
      растений - 0,15-0,30 л на 1 га посевов.
      <strong>Производство:</strong> ООО АгроТехЦентр "КолХоз"
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>ЭПАА-10 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЭПАА-10" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default epaa10;
