import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const esbella = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Bayer</strong>
      Лидер по устойчивости к заразихе и продуктивности в раннем сегменте.
      Группа спелости: Раннеспелый, 100-105 дней Устойчивость к заразихе: &gt; G
      Потенциал урожайности: 50 ц/га Высота растений / Размер корзинки: 150-160
      см / 22 см Засухоустойчивость: Высокий уровень Масличность: до 49-52 %
      Наклон корзинки: Вниз Жаростойкость: Высокий уровень
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Рекомендации</strong>
            </td>
          </tr>
          <tr>
            <td>
              Стабильный и пластичный гибрид. Отличная выполненность корзинки.
              Переносит загущение. Высокий потенциал урожайности. Раннеспелое
              растение с хорошим иммунитетом к основным болезням. Пригоден для
              позднего сева.
            </td>
            <td>
              Избегать изреженного посева. Предпочтителен сев в оптимальные
              сроки. Не злоупотреблять азотными удобрениями. Для всех регионов
              возделывания подсолнечника
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЕС БЕЛЛА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЕС БЕЛЛА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default esbella;
