import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const esgenezis = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Bayer</strong>
      Стабильный, урожайный, раннеспелый, устойчивый к заразихе и болезням
      гибрид для системы Clearfield Plus. Подходит для технологии No till и Mini
      till. Группа спелости: Раннеспелый, 100-105 дней Устойчивость к заразихе:
      Гомозиготный тип устойчивости к новым расам заразихи, A–G Потенциал
      урожайности: 50 ц/га Высота растений / Размер корзинки: 150-170 см / 22 см
      Засухоустойчивость: Высокий уровень Масличность: до 49-52 % Наклон
      корзинки: Вниз Жаростойкость: Высокий уровень
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Рекомендации</strong>
            </td>
          </tr>
          <tr>
            <td>
              Быстрый старт и раннее развитие.Отличный потенциал урожайности в
              сочетании с раннеспелостью. Стабилен — широкий ареал адаптации.
              Надежен даже в условиях экстремальной засухи. Отличный иммунитет к
              болезням, в том числе к ржавчине и ЛМРУстойчив к полеганию. Ранняя
              уборка. Отсутствие фито токсичности после обработки гербицидом —
              нет задержки развития. Отличное опыление и выполненность корзинки
              в любых условиях
            </td>
            <td>
              Своевременная борьба с сорняками и вредителями. Своевременная
              уборка. При глубокой обработки почвы уровень засухоустойчивости
              повышается. Гибрид для всех регионов возделывания подсолнечника
            </td>
          </tr>
        </tbody>
      </table>
           
    </div>
  );

  return (
    <>
      <Head>
        <title>ЕС ГЕНЕЗИС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЕС ГЕНЕЗИС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default esgenezis;
