import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const esizida = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Bayer</strong>
      Гибрид с высокими показателями. Группа спелости: Среднераниий, 105-110
      дней Устойчивость к заразихе: A-G Потенциал урожайности: 50 ц/га Высота
      растений / Размер корзинки Высота растений / Размер корзинки: 150-160 см /
      22 см Засухоустойчивость: Высокий уровень Масличность: до 50–52 % Наклон
      корзинки: 1/2 вниз Жаростойкость: Выше среднего
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Рекомендации</strong>
            </td>
          </tr>
          <tr>
            <td>
              Стабильно высокая урожайность в различных почвенно-климатических
              условиях. Высокий потенциал урожайности. Устойчив к стресовым
              условиям и понижению уровня агротехники. Устойчив к полеганию.
              Быстрый старт и ранее развитие. Эффективно использует элементы
              питания
            </td>
            <td>
              Проводить своевременную уборку. Защита от сорняков и вредителей.
              Рекомендован для возделывания в Южном, Центрально-Черноземном и
              Приволжском регионах  
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЕС ИЗИДА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЕС ИЗИДА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default esizida;
