import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const esmonaliza = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Bayer</strong>
      Ранний высокоурожайный гибрид для регионов без заразихи. Группа спелости:
      Раннеспелый, 100-105 дней Устойчивость к заразихе: Устойчив к заразихе рас
      А–Е Потенциал урожайности: до 45 ц/га Высота растений / Размер корзинки:
      150-170 см / 22 см Засухоустойчивость: Высокий уровень Масличность: до
      49-52 % Наклон корзинки: Вниз Жаростойкость: Умеренная
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Рекомендации</strong>
            </td>
          </tr>
          <tr>
            <td>
              Раннеспелое растение с хорошим иммунитетом к заболеваниям. Высокая
              масса 1000 семян. Устойчив к загущению. Отличное опыление и
              заполненность центра корзинки. Пластичен к срокам сева и глубине
              заделки. Высокая энергия роста на начальных этапах развития.
            </td>
            <td>
              Рекомендуются оптимальные сроки уборки. Проводить эффективную
              борьбу с сорняками и вредителями. Для регионов без поражения
              новыми расами Заразихи.
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЕС МОНАЛИЗА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЕС МОНАЛИЗА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default esmonaliza;
