import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const evrolajtningvrk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/imazamoks/">Имазамокс</a> 33 г/л
        + <a href="https://berkanabio.ru/category/imazapir/">Имазапир</a> 15 г/л
      </strong>
      Прекрасное средство удалить нежелательную растительность с посевов
      подсолнечника на ранних и более поздних этапах вегетации.
      <h2>Преимущество</h2>
      <ul>
        <li>
          уникальный гербицид, эффективный против всех сорных культур на
          плантации подсолнечника;
        </li>
        <li>высокоэффективный и экономичный в использовании;</li>
        <li>однократного применения за сезон бывает достаточно;</li>
        <li>пригоден к применению на необработанном грунте;</li>
        <li>действует в отношении самых стойких сорняков;</li>
        <li>появления резистентности не наблюдалось;</li>
        <li>не фитотоксичен;</li>
        <li>удобно дозировать и регулировать срок обработки;</li>
        <li>
          одновременно проникает в сорное растение посредством корневой системы
          и через зеленые части.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1-1,2</td>
            <td>
              Подсолнечник (сорта и гибриды, устойчивые к гербициду
              Евро-Лайтнинг)
            </td>
            <td>Однолетние злаковые и двудольные сорняки</td>
            <td>
              Опрыскивание посевов в ранние фазы роста сорняков (2-4 листьев) и
              4-5 настоящих листьев у культуры. Ограничения по севообороту:
              можно высевать пшеницу, рожь не ранее, чем через 4 месяца;
              люцерну, сою, ячмень, овес, кукурузу, горох (через 9 месяцев).
              Картофель, томаты, табак, лук, просо, салат, подсолнечник, огурцы,
              морковь можно высевать через 19 месяцев, сахарную и столовую
              свеклу, рапс – через 26 месяцев. Расход рабочей жидкости – 200-300
              л/га
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/basf/">БАСФ</a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Евро-Лайтнинг, ВРК - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Евро-Лайтнинг, ВРК"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default evrolajtningvrk;
