import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const evrolajtningpljusvrk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/category/imazamoks/">Имазамокс 16,5 г/л</a>{" "}
      + <a href="https://berkanabio.ru/category/imazapir/">Имазапир 7,5 г/л</a>
      Это уникальная возможность уничтожения широкого спектра сорняков в посевах
      подсолнечника с помощью послевсходового внесения гербицида с гибкими
      сроками применения.
      <h2>Преимущества препарата</h2>
      <ul>
        <li>
          Гибкость в выборе нормы и времени применения гербицида в зависимости
          от региональных особенностей;
        </li>
        <li>
          Эффективность практически не зависит от количества осадков – действует
          через листья и длительно через грунт;
        </li>
        <li>
          Возможно использование в системах минимальной и нулевой (no-till)
          обработки грунта.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1,6-2,5</td>
            <td>
              Подсолнечник на семена и масло (сорта и гибриды, устойчивые к
              гербициду Евро-Лайтнинг Плюс)
            </td>
            <td>Однолетние злаковые и двудольные сорняки</td>
            <td>
              <span>
                Опрыскивание посевов в ранние фазы роста сорняков (2-4 листьев)
                и 4-5 настоящих листьев у культуры.
              </span>
              <span>
                Ограничения по севообороту: пшеницу и рожь можно высевать не
                ранее, чем через 4 месяца; люцерну, сою, ячмень, овес, кукурузу,
                горох - через 9 месяцев после применения препарата. Картофель,
                томаты, табак, лук, просо, салат, подсолнечник, огурцы, морковь
                можно высевать через 19 месяцев; сахарную и столовую свеклу,
                рапс – через 26 месяцев.
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/basf/">БАСФ</a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Евро-Лайтнинг Плюс, ВРК - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Евро-Лайтнинг Плюс, ВРК"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default evrolajtningpljusvrk;
