import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const feniksduoks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/tiofanat-metil/">
          Тиофанат-метил
        </a>{" "}
        310 г/л +{" "}
        <a href="https://berkanabio.ru/category/flutriafol/">Флутриафол</a> 187
        г/л
      </strong>
      Инновационный двухкомпонентный системный фунгицид с широким спектром
      активности для защиты от комплекса распространенных болезней
      <h2>Преимущество</h2>
      <ul>
        <li>Абсолютная безопасность для окружающей среды и самих растений;</li>
        <li>Длительный период защитного действия;</li>
        <li>
          Объединяет в себе лечебный, профилактический и фумигационный эффекты;
        </li>
        <li>
          Повышает урожайность путем продления периода вегетации растений;
        </li>
        <li>Быстро распространяется и полностью защищает культуру;</li>
        <li>Предотвращает возникновение резистентности у патогенов;</li>
      </ul>
      <h3>Норма расхода</h3>
      <div class="table_content_wrap">
        <table class="main_content">
          <tbody>
            <tr class="head">
              <td class="width_12_prc">
                <strong>Нор­ма</strong>
              </td>
              <td>
                <strong>Куль­ту­ра</strong>
              </td>
              <td>
                <strong>Вред­ный объ­ект</strong>
              </td>
              <td>
                <strong>Спо­соб, вре­мя об­ра­бот­ки</strong>
              </td>
            </tr>
            <tr class="uneven">
              <td class="width_12_prc t_a_center_f_s_11">0,5-0,6</td>
              <td class="width_20_prc left_border left_border">
                Пшеница озимая
              </td>
              <td class="width_19_prc left_border left_border">
                Мучнистая роса, ржавчина бурая и стеблевая
              </td>
              <td class="width_27_prc left_border left_border">
                Опрыскивание в период вегетации. Расход рабочей жидкости – 300
                л/га
              </td>
            </tr>
            <tr class="even" id="finish_row">
              <td class="width_12_prc t_a_center_f_s_11">0,6</td>
              <td class="width_20_prc left_border left_border">
                Пшеница озимая
              </td>
              <td class="width_19_prc left_border left_border">
                Септориоз листьев и колоса
              </td>
              <td class="width_27_prc left_border left_border">
                Опрыскивание в период вегетации. Расход рабочей жидкости – 300
                л/га
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/alfahimgrupp/">АльфаХимгрупп</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Феникс Дуо, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Феникс Дуо, КС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default feniksduoks;
