import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const fitaktivekstra = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/fitaktiv-ekstra.png"></a>
        Биологически активный регулятор роста
      </strong>
      Применять препарат ЭКСТРА при любых некорневых обработках с пестицидами,
      при двухкратном снижении норм последних. Не превышать рекомендованные
      дозы. Фуллерен усиливает действие действующих веществ, инсектицидов в 2
      раза, фунгицидов в 3-4 раза. 3,8 руб/10 литров воды, обработка по листу
      100 руб/ 1 га.
      <h2>Состав</h2>
      ауксин-фуллереновые комплексы, не менее 0,5 г/л - повышают неспецифическую
      сопротивляемость к широкому спектру вредных воздействий химической и
      биологической природы. 2-этил-индол-3-n-пропилено 3,6:1,2{60}фуллерен, 0,5
      г/л, регулятор роста, адаптоген, усиливает иммунную систему растения.
      Индолил -3 -масляная кислота 0,05 г/л, стимулятор корневой системы
      (действующее вещество, препарата Корневин).
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/npo-binam/">НПО “БИНАМ”</a>
      <strong>Упаковка:</strong> 1 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Фитактив Экстра - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Фитактив Экстра"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default fitaktivekstra;
