import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const floraksks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/2-4-d-2-etilgeksilovyj-efir/">
          2,4-Д (2-этилгексиловый эфир)
        </a>{" "}
        550 г/л +{" "}
        <a href="https://berkanabio.ru/category/florasulam/">Флорасулам</a> 7,4
        г/л
      </strong>
      Мощный двухкомпонентный гербицид для защиты посевов зерновых колосовых
      культур от широкого спектра двудольных сорняков.
      <h2>Преимущество</h2>
      <ul>
        <li>
          имеет широкий спектр действия против однолетних и многолетних
          двудольных сорняков, в том числе устойчивых к 2,4–Д;
        </li>
        <li>
          препарат, эффективный одновременно против подмаренника цепкого и
          различных видов ромашки и осота;
        </li>
        <li>может использоваться при температуре от + 5°С;</li>
        <li>
          отличается длительным сроком внесения – начиная со стадии кущения до
          стадии образования второго междоузлия;
        </li>
        <li>хорошо подавляет переросшие сорняки;</li>
        <li>
          действует быстро, поэтому первые симптомы заметны уже через сутки
          после применения;
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Ни­ме­не­ния</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,3-0,4</span>
            </td>
            <td>
              <span>Пшеница озимая и яровая, ячмень яровой</span>
            </td>
            <td>
              <span>
                Однолетние, в т. ч. устойчивые к 2,4-Д и 2М-4Х, и некоторые
                многолетние двудольные сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе кущения культуры и ранние фазы роста
                сорняков. Озимые обрабатываются весной.
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,5</span>
            </td>
            <td>
              <span>Пшеница озимая и яровая, ячмень яровой</span>
            </td>
            <td>
              <span>
                Однолетние, в т. ч. устойчивые к 2,4-Д и 2М-4Х, и некоторые
                многолетние двудольные сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе выхода в трубку (1-2 междоузлия)
                культуры и ранние фазы роста сорняков (с учетом чувствительности
                сортов) в случае преобладания подмаренника цепкого; если
                погодные условия не позволили произвести обработку раньше срока.
                Озимые обрабатывают весной.
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/afd-kemikals/">АФД Кемикалс</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Флоракс, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Флоракс, КС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default floraksks;
