import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const fluoronvdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio-fluoron-vdg.jpg"></a>
        <a href="https://berkanabio.ru/category/triflusulfuron-metil/">
          Трифлусульфурон-метил
        </a>{" "}
        500 г/кг
      </strong>
      Системный гербицид для защиты сахарной свеклы от двудольных сорняков, в
      т.ч. злостных и трудноискоренимых.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Высокоэффективный гербицид в борьбе со многими видами двудольных
          сорняков, в т.ч. вьюнком полевым, канатником, щирицей запрокинутой,
          видов горцев.
        </li>
        <li>
          Не фитотоксичен по отношению к свекле, не обладает последействием на
          последующие культуры севооборота.
        </li>
        <li>
          Проявляет эффективность при неблагоприятных погодных условия,обладает
          быстрым действием.
        </li>
        <li>
          Прекрасно совмещается с препаратами на основе десмедифама и
          фенмедифама, отличный компонент для баковых смесей.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,03</td>
            <td>Свекла сахарная</td>
            <td>Однолетние двудольные сорняки</td>
            <td>
              Опрыскивание посевов в фазе сорняков семядоли - 2 настоящих листа
              и при необходимости повторно через 7-15 дней по второй волне
              сорняков в фазе 2-х настоящих листьев в смеси с 200 мл/га ПАВ Неон
              99 (Неонол АФ<sub>9-12 </sub>) при каждой обработке.Расход рабочей
              жидкости - 200-300 л/га
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/fmrus/">ФМРус</a>
      <strong>Упаковка: </strong>0,6 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Флуорон, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Флуорон, ВДГ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default fluoronvdg;
