import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const galaktionke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_galaktion-ke.jpg"></a>
        <a href="https://berkanabio.ru/category/galoksifop-r-metil/">
          Галоксифоп-Р-метил
        </a>{" "}
        104 г/л к-ты
      </strong>
      Системный противозлаковый гербицид.
      <h2>Преимущества</h2>
      <ul>
        <li>Уничтожает однолетние и многолетние злаковые сорняки.</li>
        <li>
          Применяется после всходов сельскохозяйственных культур, в период роста
          сорняков.
        </li>
        <li>
          Обладает системным действием, быстро поглощается листьями сорняков и
          переносится к их точкам роста, корням и корневищам.
        </li>
        <li>Селективен по отношению к широколистным культурам.</li>
        <li>Обеспечивает высочайшую эффективность при малых нормах расхода;</li>
        <li>
          Может применяться в баковых смесях с гербицидами, предназначенными для
          борьбы с широколистными сорняками, и с инсектицидами.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,5</span>
            </td>
            <td>
              <span>
                Свекла сахарная и кормовая, подсолнечник, соя, рапс яровой
              </span>
            </td>
            <td>
              <span>
                Однолетние злаковые (виды щетинника, просо куриное, просо
                сорное) сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание сорняков в период их активного роста (в фазе от 2-6
                листьев до кущения).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1</span>
            </td>
            <td>
              <span>Свекла сахарная и кормовая, рапс яровой</span>
            </td>
            <td>
              <span>Многолетние злаковые (пырей ползучий) сорняки</span>
            </td>
            <td>
              <span>Опрыскивание посевов при высоте сорняков 10-15 см.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/gk-zemlyakoff/">
        ЗемлякоФФ
      </a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Галактион, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Галактион, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default galaktionke;
