import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const gallonke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_gallon-ke.jpg"></a>
        <a href="https://berkanabio.ru/category/galoksifop-r-metil/">
          Галоксифоп-Р-метил
        </a>{" "}
        104 г/л кислоты
      </strong>
      Высокоэффективный гербицид для борьбы со злаковыми сорняками в посевах
      подсолнечника, свеклы сахарной и кормовой, рапса и сои.
      <h2>Преимущества</h2>
      <ul>
        <li>Подавляет однолетние и многолетние злаковые сорняки.</li>
        <li>Полностью уничтожает корневища пырея ползучего.</li>
        <li>
          Применяется после всходов сельскохозяйственных культур, в период
          активного роста сорняков.
        </li>
        <li>
          Обладает системным действием, быстро поглощается листьями сорняков и
          переносится к точкам роста, корням и корневищам.
        </li>
        <li>
          Благодаря системному действию уничтожаются корни и корневища злаковых
          сорняков, что исключает повторное отрастание.
        </li>
        <li>Селективен по отношению к широколистным культурам.</li>
        <li>Высокоэффективен при малых нормах расхода.</li>
        <li>
          Может применяться в баковых смесях с гербицидами, предназначенными для
          борьбы с широколистными сорняками, и с инсектицидами.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,5</span>
            </td>
            <td>
              <span>
                Свекла сахарная и кормовая, подсолнечник, соя, рапс яровой
              </span>
            </td>
            <td>
              <span>
                Однолетние злаковые сорняки (виды щетинника, просо куриное,
                просо сорное)
              </span>
            </td>
            <td>
              <span>
                Опрыскивание сорняков в период их активного роста (в фазе от 2-6
                листьев до кущения).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1,0</span>
            </td>
            <td>
              <span>
                Свекла сахарная и кормовая, подсолнечник, рапс яровой, соя
              </span>
            </td>
            <td>
              <span>Многолетние злаковые сорняки (пырей ползучий)</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов при высоте пырея ползучего 10-15 см.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/fmrus/">ФМРус</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Галлон, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Галлон, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default gallonke;
