import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const gardogoldks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/category/s-metolahlor/">
        С-Метолахлор 312,5 г/л
      </a>{" "}
      +{" "}
      <a href="https://berkanabio.ru/category/terbutilazin/">
        Тербутилазин 187,5 г/л
      </a>
      Селективный довсходовый гербицид на основе двух действующих веществ для
      защиты подсолнечника от широкого спектра однолетних широколистных и
      злаковых сорняков.
      <h2>Преимущества препарата</h2>
      <ul>
        <li>Первый комбинированный гербицид для подсолнечника.</li>
        <li>
          Синергизм действия двух действующих веществ обеспечивает высокую
          продолжительность действия препарата.
        </li>
        <li>
          Широкий спектр действия против однолетних двудольных и злаковых
          сорняков, в т.ч. канатника, дурнишника (эффективность на уровне 30%
          при почвенном применении и до 80% при попадании на всходы сорняка) и
          амброзии.
        </li>
        <li>Отсутствие фитотоксического действия на подсолнечник.</li>
        <li>
          Эффективная работа в самых экстремальных условиях (дожди, засуха).
        </li>
        <li>Отсутствие необходимости немедленной заделки.</li>
        <li>
          Повышение урожайности за счет лучшей защиты и уменьшения
          фитотоксичности.
        </li>
        <li>
          Отсутствие влияния на последующие культуры в севообороте, препарат
          полностью разлагается в почве в течение периода вегетации.
        </li>
        <li>Высокая экономическая отдача.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>3-4</td>
            <td>Подсолнечник</td>
            <td>Однолетние злаковые и двудольные сорняки</td>
            <td>
              <span>Опрыскивание почвы до всходов культуры.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>4-4,5</td>
            <td>Кукуруза</td>
            <td>Однолетние злаковые и двудольные сорные растения</td>
            <td>
              <span>
                Опрыскивание почвы до всходов культуры или в ранние фазы роста
                (3-5 листьев) культурных и сорных (1-4 листа) растений. Расход
                рабочей жидкости – 200 – 300 л/га
              </span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/singenta/">Сингента</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Гардо Голд, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Гардо Голд, КС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default gardogoldks;
