import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const generaliskl = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Lidea</strong>
      Среднеспелый гибрид Цветение: среднеспелый Созревание: среднеспелый Высота
      растения: высокое Корзинка: приподнятая Тип гибрида: линолевый
      Масличность: 50-51%
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации</td>
          </tr>
          <tr>
            <td>
              Технология Clearfield® Гибрид интенсивного типа с высоким
              потенциалом Стабильная урожайность на высоком агрофоне Высокая
              масличность
            </td>
            <td>
              Зона достаточного увлажнения: 60-65 тыс. семян/га Засушливые
              условия: 55-60 тыс. семян/гаOR Master Premium: устойчивость к
              агрессивным расам заразихи
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Агрономический профиль</strong>
      Толерантность к фомопсису: хорошо Толерантность к вертициллезу: хорошо
      Толерантность к белой гнили: средне Толерантность к пепельной гнили:
      хорошо Толерантность к ржавчине: слабо Устойчивость к полеганию: средне
      Начальные темпы роста: хорошие
    </div>
  );

  return (
    <>
      <Head>
        <title>ГЕНЕРАЛИС КЛ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ГЕНЕРАЛИС КЛ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default generaliskl;
