import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const globalnoepotepleniemozhetuvelichiturozhai = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      В своем последнем исследовании ученые решили использовать новые доступные
      образцы культур и данные полевых экспериментов, чтобы ответить на вопрос о
      том, как глобальное потепление повлияет на сельское хозяйство Многие
      исследования утверждают, что по мере повышения температуры зерновые
      культуры во всем мире будут страдать. Средние значения температуры
      становятся непригодными для традиционно выращиваемых культур, при этом
      жара, засуха и редкие экстремальные осадки приобретают все более
      распространенный характер. Однако картина может оказаться несколько иной,
      пишет www.gismeteo.ru со ссылкой на Nature Climate Change. «Большая часть
      дискуссии вокруг климатических воздействий фокусируется только на
      изменениях температуры и количестве осадков. Для того чтобы адекватно
      адаптироваться к меняющимся условиям, мы должны понимать все вовлеченные
      факторы», — отметила Дельфина Деринг, ученый-эколог из Колумбийского
      университета, принимавшая участие в исследовании. Эксперименты,
      проведенные в 1980-х годах, показали, что высокое содержание углекислого
      газа в воздухе способствует наращиванию биомассы растений. Начиная с 1960
      года средний глобальный уровень углекислого газа в атмосфере вырос более
      чем на четверть. В настоящее время он составляет около 400 частей на
      миллион и, как ожидается, продолжит увеличиваться вместе с ростом
      температуры. В новой работе исследователи изучили, как повышение
      температуры и количества углекислого газа, наряду с изменениями в осадках
      и облачности, совместно могут повлиять на сельскохозяйственные культуры.
      Удивительно, но ученые обнаружили, что если рассматривать увеличение
      углекислого газа в атмосфере в сочетании с водным и тепловым стрессом, то
      становится очевидным, что, находясь в таких условиях, растения начнут
      более эффективно использовать воду к 2080 году. Таким образом, полученные
      данные показывают, что в то время как сельскохозяйственные культуры могут
      пострадать на начальном этапе, итог будет обратным — повышение уровня
      углекислого газа в атмосфере может компенсировать растениям тепловой
      стресс. Эти выводы особенно важны в отношении корректировки методов
      ведения сельского хозяйства по мере изменения климата. Результаты
      исследования были опубликованы 18 апреля в журнале Nature Climate Change.
      Источник:{" "}
      <a href="http://www.agroxxi.ru/zhurnal-agroxxi/novosti-nauki/globalnoe-poteplenie-mozhet-uvelichit-urozhai.html?utm_source=twitterfeed&amp;utm_medium=twitter">
        www.agroxxi.ru
      </a>
    </div>
  );

  return (
    <>
      <Head>
        <title>Глобальное потепление может увеличить урожаи - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Глобальное потепление может увеличить урожаи"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default globalnoepotepleniemozhetuvelichiturozhai;
