import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const gumi20kalijnyj = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/GUMI_20-Kaliynyy-NPK-112.jpeg"></a>
        Биоактивированные по малекулярному весу и макро- микроэлементному
        составу гуматы калия
      </strong>
      Наделяет растение гербицидными и температурными иммунными свойствами.
      Ускоряет рост растения, помогает перенести температурный стресс и
      благоприятно действует после применения гербицидов, восполняет нехватку
      калия. Содержит калий, азот, фосфор и микроэлементы в хелатной форме.
      <h2>Состав</h2>
      <ul>
        <li>калиевые соли гуминовых кислот</li>
        <li>макроэлементы: NPK = 1:1:2</li>
        <li>
          микроэлементы: B-0,17%, Cu-0,01%, Co-0,002%, Mn-0,05%, Zn-0,01%,
          Mo-0,007%, Se-0,0001%, Ni-0,002%, Li-0,0005%, S - 0,015%, Cr-0,0007%
        </li>
        <li>микроэлементы Сo, Cu, Mn, Zn, Cr, Ni, Li в хелатной форме</li>
      </ul>
      <strong>Производство:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО "НВП БашИнком"
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Гуми 20 Калийный - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Гуми 20 Калийный"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default gumi20kalijnyj;
