import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const gumi20mbogatyj569 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/Bogatyy-NPK-569-Kaliynyy_ME.jpeg"></a>
        Биоактивированные по молекулярному весу и составу БМВ-гуматы натрия,
        обогащенные биофунгицидом Фитоспорин-М - 2%
      </strong>
      Эффективное биоактивированное удобрение с полным набором макро- и
      микроэлементов в наиболее доступной для растений хелатной форме, с
      усиленными антистрессовыми, ростоускоряющими, иммуностимулирующими и
      фунгицидными свойствами.
      <h2>Состав</h2>
      <ul>
        <li>NPK=5:6:9;</li>
        <li>
          микроэлементный комплекс: B-0,7%, Cu-0,01%, Co-0,002%, Zn-0,01%,
          Mn-0,05%, Mo-0,001%, Ni-0,002%, Li-0,0005%, S-0,04%, Se-0,0002%,
          Cr-0,001%;
        </li>
        <li>микроэлементы Co, Cu, Mn, Zn, Cr, Ni, Li в хелатной форме;</li>
      </ul>
      <h2>Норма расхода</h2>
      0,2 - 0,5 л/т предпосевная обработка семян; 0,2 - 1,0 л/га, 50 л - 200 л
      воды/га при внекорневой подкормке; 0,5 - 1 л на 1000 л воды при корневой
      подкормке.
      <strong>Производство: </strong>
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО "НВП БашИнком"
      </a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Гуми-20М Богатый 5-6-9 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Гуми-20М Богатый 5-6-9"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default gumi20mbogatyj569;
