import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const habbl = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LIDEA</strong>
      Среднеранний гибрид. Стабильный урожай на зерно в различных зонах
      выращивания. Высокая устойчивость к ломкости стебля и позднему полеганию.
      Хорошая толерантность к болезням. ФАО 240 Тип зерна: кремнисто-зубовидный:
      более 50% кремнистый Особенности гибрида: Гибрид эффективен для
      выращивания на крупу. Полевые наблюдения: хорошая толерантность к
      грибковым заболеваниям.
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Агрономический профиль</strong>
            </td>
            <td>
              <strong>Преимущества</strong>
            </td>
          </tr>
          <tr>
            <td>
              Начальные темпы роста: отлично Устойчивость к позднему полеганию:
              отлично Толерантность к пыльной головне: отлично Толерантность к
              фузариозу початка: отлично
            </td>
            <td>
              Стабильный урожай на зерно в различных зонах выращивания. Высокая
              устойчивость к ломкости стебля и позднему полеганию. Хорошая
              толерантность к болезням
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ХАББЛ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ХАББЛ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default habbl;
