import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const imidalittps = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/03/berkanabio_imidalit-tps-.jpg"></a>
        <a href="https://berkanabio.ru/category/bifentrin/">
          Бифентрин (Талстар)
        </a>{" "}
        50 г/л +{" "}
        <a href="https://berkanabio.ru/category/imidakloprid/">Имидаклоприд</a>{" "}
        500 г/л
      </strong>
      Системный инсектицид контактного и кишечного действия для предпосевной
      обработки семян против комплекса вредителей всходов.
      <h2>Преимущества</h2>
      <ul>
        <li>Низкая норма применения.</li>
        <li>Легкость в использовании.</li>
        <li>Отсутствие аллергентности.</li>
        <li>Жидкая прилипаемая форма.</li>
        <li>Отсутствие раздражающей способности.</li>
        <li>Совместимость с другими препаратами.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния пре­па­ра­та</strong>
            </td>
            <td>
              <strong>Куль­ту­ра, об­ра­ба­ты­ва­емый объ­ект</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,4-0,5</td>
            <td>Ячмень</td>
            <td>Хлебные блошки, злаковые мухи</td>
            <td>Обработка семян. Расход рабочей жидкости – до 10 л/т</td>
          </tr>
          <tr>
            <td>0,4-0,5</td>
            <td>Пшеница</td>
            <td>Злаковые мухи, проволочники, хлебные блошки</td>
            <td>Обработка семян. Расход рабочей жидкости – до 10 л/т</td>
          </tr>
          <tr>
            <td>0,5</td>
            <td>Пшеница</td>
            <td>Хлебная жужелица</td>
            <td>Обработка семян. Расход рабочей жидкости – до 10 л/т</td>
          </tr>
          <tr>
            <td>6-8</td>
            <td>Рапс</td>
            <td>Крестоцветные блошки</td>
            <td>Обработка семян. Расход рабочей жидкости – до 18 л/т</td>
          </tr>
          <tr>
            <td>6-8</td>
            <td>Капуста</td>
            <td>Крестоцветные блошки, капустные мухи</td>
            <td>Обработка семян. Расход рабочей жидкости – до 18 л/т</td>
          </tr>
          <tr>
            <td>0,1</td>
            <td>Картофель</td>
            <td>Проволочники, колорадский жук, тли</td>
            <td>
              Обработка клубней перед посадкой. Расход рабочей жидкости – до 10
              л/т
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> 
      <a href="https://berkanabio.ru/category/pestitsidy/fmrus/">ФМРус</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Имидалит, ТПС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Имидалит, ТПС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default imidalittps;
