import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const izzapovyshenijaaktsizanatoplivozatratyagrarievvyrastutna7mlrdrublej =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        В России с 1 апреля повышаются акцизы на топливо. Соответствующий закон
        подписал президент страны Владимир Путин. В частности, налоговые ставки
        акцизов на бензин со следующего месяца повысятся на 2 рубля за литр, на
        дизельное топливо и средние дистилляты – на 1 рубль за литр. Согласно
        подсчетам Министерства финансов, повышение акцизов приведет к
        5-процентному росту цен на топливо. За счет этого бюджет страны
        пополнится примерно на 90 миллиардов рублей. В Департаменте
        растениеводства, химизации и защиты растений уже подсчитали, сколько
        потеряет российский АПК от повышения акцизов на топливо. «Мы теряем в
        целом по стране 7 миллиардов рублей. У нас появляется дополнительная
        финансовая нагрузка», — сообщил директор департамента Петр Чекмарев на
        заседании Межведомственной комиссии по организации весенних полевых
        работ в Сибирском Федеральном округе в среду, 2 марта. Потребности АПК в
        дизтопливе на текущий год оцениваются в 4,28 млн тонн, в бензине – в 820
        тыс. тонн (в прошлом году – 4,279 млн тонн и 810 тыс. тонн
        соответственно). По состоянию на 15 февраля в российских хозяйствах
        имелось 339,9 тыс. тонн дизельного топлива и 49 тыс. тонн бензина, что
        на 18% больше, чем на аналогичную дату прошлого года. Источник: 
        <a href="http://agroinfo.com/iz-za-povysheniya-akciza-na-toplivo-zatraty-agrariev-vyrastut-na-7-mlrd-rublej-0303201603/">
          agroinfo.com
        </a>
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Из-за повышения акциза на топливо затраты аграриев вырастут на 7
            млрд. рублей - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Из-за повышения акциза на топливо затраты аграриев вырастут на 7 млрд. рублей"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default izzapovyshenijaaktsizanatoplivozatratyagrarievvyrastutna7mlrdrublej;
