import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const jachmen = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      In{" "}
      <a href="http://en.wikipedia.org/wiki/Marketing" title="Marketing">
        marketing
      </a>
      , a <b>product</b> is anything that can be offered to a{" "}
      <a
        href="http://en.wikipedia.org/wiki/Market_(economics)"
        title="Market (economics)"
      >
        market
      </a>{" "}
      that might satisfy a want or need.
      <sup class="reference" id="cite_ref-1">
        <a href="http://en.wikipedia.org/wiki/Product_(business)#cite_note-1">
          [1]
        </a>
      </sup>{" "}
      In{" "}
      <a
        class="mw-redirect"
        href="http://en.wikipedia.org/wiki/Retailing"
        title="Retailing"
      >
        retailing
      </a>
      , products are called{" "}
      <a
        class="mw-redirect"
        href="http://en.wikipedia.org/wiki/Merchandise"
        title="Merchandise"
      >
        merchandise
      </a>
      . In{" "}
      <a
        href="http://en.wikipedia.org/wiki/Manufacturing"
        title="Manufacturing"
      >
        manufacturing
      </a>
      , products are bought as{" "}
      <a href="http://en.wikipedia.org/wiki/Raw_material" title="Raw material">
        raw materials
      </a>{" "}
      and sold as{" "}
      <a
        class="mw-redirect"
        href="http://en.wikipedia.org/wiki/Finished_goods"
        title="Finished goods"
      >
        finished goods
      </a>
      .{" "}
      <a href="http://en.wikipedia.org/wiki/Commodity" title="Commodity">
        Commodities
      </a>{" "}
      are usually raw materials such as metals and agricultural products, but a
      commodity can also be anything widely available in the open market. In{" "}
      <a
        href="http://en.wikipedia.org/wiki/Project_management"
        title="Project management"
      >
        project management
      </a>
      , products are the formal definition of the{" "}
      <a
        href="http://en.wikipedia.org/wiki/Product_breakdown_structure"
        title="Product breakdown structure"
      >
        project deliverables
      </a>{" "}
      that make up or contribute to delivering the objectives of the project. In
      insurance, the policies are considered products offered for sale by the
      insurance company that created the contract.
    </div>
  );

  return (
    <>
      <Head>
        <title>Ячмень - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Ячмень" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default jachmen;
