import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const jaguarsuper75emv = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/klokvintoset-meksil/">
          Клоквинтосет-мексил
        </a>{" "}
        34,5 г/л +{" "}
        <a href="https://berkanabio.ru/category/fenoksaprop-p-etil/">
          Феноксапроп-П-этил
        </a>{" "}
        69 г/л
      </strong>
      Высокоселективный гербицид для защиты посевов пшеницы и ячменя от
      однолетних злаковых сорняков.
      <h2>Преимущества</h2>
      Ягуар Супер 7,5 применяется в качестве послевсходового гербицида широкого
      спектра действия для борьбы с сорняками в посевах зерновых культур;
      обеспечивает эффективное уничтожение наиболее распространенного и
      вредоносного сорного злака – овсюга обыкновенного. Наряду с ним все
      большее распространение и вредоносность проявляют просовидные сорняки:
      виды проса и щетинника, которые иногда становятся основной проблемой в
      посевах зерновых. Для решения этой проблемы также используется данный
      препарат – с расширенным спектром действия и широким диапазоном сроков
      применения. Обработка посевов препаратом Ягуар Супер 7,5 позволяет
      осуществлять контроль основных экономически значимых видов злаковых
      сорняков независимо от фазы развития культуры.
      <h3>Механизм действия</h3>
      Препарат поглощается наземными органами растения в течение 1–3 часов после
      применения. Благодаря системному действию препарат свободно перемещается
      во все части растения и накапливается в точках роста. На биохимическом
      уровне гербицид ингибирует биосинтез жирных кислот в меристемных тканях,
      препятствуя образованию клеточных мембран в точках роста. Отмирание точек
      роста ведет к прекращению роста и гибели сорных злаков.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,8-1</td>
            <td>Пшеница яровая и озимая, ячмень яровой</td>
            <td>
              Однолетние злаковые сорняки (виды щетинника, просо куриное, просо
              сорное, овсюг, метлица полевая)
            </td>
            <td>
              Опрыскивание посевов в ранние фазы развития (2-3 листа) сорняков
              независимо от фазы развития культуры (с учетом чувствительности
              сортов). Озимая пшеница обрабатывается весной. Расход рабочей
              жидкости - 150-200 л/га
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/neoport/">Neoport</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Ягуар Супер 7.5, ЭМВ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Ягуар Супер 7.5, ЭМВ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default jaguarsuper75emv;
