import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const junkervr = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_junker-vr.jpg"></a>
        <a href="https://berkanabio.ru/category/imazamoks/">Имазамокс</a> 40 г/л
      </strong>
      Высокоэффективный гербицид из группы имидазолинонов для борьбы с
      однолетними злаковыми и двудольными сорняками на посевах сои, гороха и
      нута.
      <h2>Преимущество</h2>
      Послевсходовый гербицид для защиты культур от широкого спектра однолетних
      двудольных и злаковых сорняков. Оказывает ярко выраженный сдерживающий
      эффект в отношении многолетних (в том числе и некоторых карантинных
      сорняков).
      <h3>Механизм действия</h3>
      Имазамокс поглощается листьями и корневой системой сорняков и ингибирует
      синтез ряда аминокислот, что приводит к гибели чувствительных сорняков.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,75-1</span>
            </td>
            <td>
              <span>Соя</span>
            </td>
            <td>
              <span>Однолетние злаковые и двудольные сорняки</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в ранние фазы роста сорняков (1-3 настоящих
                листа) и 1-3 настоящих листа культуры. На следующий год можно
                высевать все культуры, кроме сахарной свеклы (безопасный
                интервал между применением гербицида и посевом свеклы – 16
                месяцев).
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,75-1</span>
            </td>
            <td>
              <span>Горох и нут (при выращивании на зерно)</span>
            </td>
            <td>
              <span>Однолетние злаковые и двудольные сорняки</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в ранние фазы роста сорняков (1-3 настоящих
                листа) и 1-3 настоящих листа культуры. На следующий год можно
                высевать все культуры, кроме сахарной свеклы (безопасный
                интервал между применением гербицида и посевом свеклы – 16
                месяцев).
              </span>
              <span>Расход рабочей жидкости – 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/neoport/">Neoport</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Юнкер, ВР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Юнкер, ВР" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default junkervr;
