import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kakpovysiturozhajnostkulturiprietomsnizitihsebestoimost = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <h2>Выращивать надо… почву!</h2>
      Классическая агротехнология, которую сейчас применяют аграрии, создавалась
      еще при советском ценнике на удобрения и топливо. Однако из-за текущего
      диспаритетного роста цен при выполнении всех научных рекомендаций на
      основе технологий, разработанных в 80-е годы XX века, она способна
      привести хозяйство только к разорению, поскольку себестоимость выращенной
      продукции может оказаться выше закупочных цен на неё. Российскому АПК
      нужны новые подходы и технологии, позволяющие в разы сокращать
      себестоимость производства зерна. О том, что это за подходы, шла речь на
      заседании Клуба агрознатоков ИД «Крестьянин», которое мы провели совместно
      с НПО «Биоцентр» и компанией «БЕРКАНА» (Воронеж). По словам гендиректора
      НПО «Биоцентр» Александра Харченко, соревноваться с западными фермерами в
      рентабельности, перенимая западные технологии один к одному, нет смысла –
      она у них искусственная, раздутая за счет рекордной господдержки.
      Единственный вариант – не снижать собственные расходы (они часто уже
      снижены до предела), а оптимизировать их (меняя статьи затрат), попутно
      повышая урожайность культур.
      <a
        href="http://berkanabio.ru/wp-content/uploads/2019/09/krestianin-36.png"
        rel="attachment wp-att-2081"
      ></a>
      Как ни странно, на данном пути у аграриев есть огромные резервы. Как
      обеспечить, например, восстановление естественного (природного) плодородия
      почвы, и за счет него получить «бесплатную» прибавку урожая? Продолжение в
      статье:{" "}
      <a href="http://berkanabio.ru/wp-content/uploads/2019/09/Krestyanin36.pdf">
        Крестьянин № 36 (1421), 4 – 10 сентября 2019
      </a>
    </div>
  );

  return (
    <>
      <Head>
        <title>
          Как повысить урожайность культур и при этом снизить их себестоимость?
          - Berkana
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Как повысить урожайность культур и при этом снизить их себестоимость?"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kakpovysiturozhajnostkulturiprietomsnizitihsebestoimost;
