import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kanonke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/category/galoksifop-r-metil/">
        Галоксифоп-Р-метил
      </a>{" "}
      104 г/л Гербицид для защиты посевов свеклы сахарной и кормовой,
      подсолнечника, сои рапса ярового от однолетних злаковых (виды щетинника,
      просо куриное,просо сорное) и многолетних злаковых (пырей ползучий)
      сорняков.
      <h2>Преимущество</h2>
      Гербицид для защиты посевов от однолетних и многолетних злаковых сорняков.
      Применяется после всходов сельскохозяйственных культур, в период активного
      роста сорняков. Обладает системным действием, быстро поглощается листьями
      сорняков и переносится к их точкам роста, корням и корневищам и
      обеспечивает высочайшую эффективность при малых нормах расхода.
      <h2>Норма расхода и применение</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,5</td>
            <td>Свекла сахарная и кормовая, подсолнечник, соя, рапс яровой</td>
            <td>
              Однолетние злаковые сорняки (виды щетинника, просо куриное, просо
              сорное)
            </td>
            <td>
              Опрыскивание сорняков в период их активного роста (в фазе от 2-6
              листьев до кущения). Расход рабочей жидкости – 200-300 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Свекла сахарная и кормовая, подсолнечник, рапс яровой</td>
            <td>Многолетние злаковые сорняки (пырей ползучий)</td>
            <td>
              Опрыскивание посевов при высоте пырея ползучего 10-15 см. Расход
              рабочей жидкости – 200-300 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Интер Групп
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Канон, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Канон, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kanonke;
