import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kaptorapljusvrk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2021/02/0000-1.jpg"></a>
        <a href="https://berkanabio.ru/category/imazamoks/">
          Имазамокс 16,5 г/л
        </a>{" "}
        +{" "}
        <a href="https://berkanabio.ru/category/imazapir/">Имазапир 7,5 г/л</a>
      </strong>
      Гербицид широкого спектра действия для борьбы с однолетними злаковыми и
      двудольными сорняками в посевах подсолнечника.
      <h2>Преимущества препарата</h2>
      <ul>
        <li>
          Высокоэффективный контроль однолетних двудольных и злаковых сорняков.
        </li>
        <li>Удобное окно применения.</li>
        <li>
          Создание почвенного гербицидного экрана, обеспечивающего длительный
          контроль однолетних и некоторых многолетних сорняков, которые
          прорастают из семян, сдерживая последующие волны сорняков в течение
          почти всего периода вегетации.
        </li>
        <li>
          Упрощение процесса контроля сорной растительности благодаря
          эффективному действию гербицида через корни и листья при одноразовом
          послевсходовом применении. Надежный способ контроля всех рас заразихи.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1,6-2,5</td>
            <td>
              Подсолнечник (на семена и на масло) (гибриды, устойчивые к
              гербициду Каптора Плюс, ВРК (16,5 г/л имазамокса + 7,5 г/л
              имазапира))
            </td>
            <td>Однолетние злаковые и двудольные сорные растения</td>
            <td>
              Опрыскивание посевов в ранние фазы роста сорных растений (2-4
              листьев) и 4-5 настоящих листьев у культуры. Ограничения по
              севообороту: пшеницу и рожь можно высевать не ранее, чем через 4
              месяца; люцерну, сою, ячмень, овес, кукурузу, горох – через 9
              месяцев. Картофель, томаты, табак, лук, просо, салат,
              подсолнечник, огурцы, морковь можно высевать через 19 месяцев,
              свеклу сахарную и столовую, рапс – через 26 месяцев. Расход
              рабочей жидкости – 200-300 л/га
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/singenta/">Сингента</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Каптора Плюс, ВРК - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Каптора Плюс, ВРК"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kaptorapljusvrk;
