import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kaptoravrk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2020/08/berkanabio-kaptora-vrk.jpg"></a>
        <a href="https://berkanabio.ru/category/imazamoks/">Имазамокс</a> 33 г/л
        + <a href="https://berkanabio.ru/category/imazapir/">Имазапир</a> 15 г/л
      </strong>
      Гербицид широкого спектра действия для борьбы с однолетними злаковыми и
      двудольными сорняками в посевах подсолнечника.
      <h2>Преимущество</h2>
      <ul>
        <li>
          ​Высокоэффективный контроль однолетних двудольных и злаковых сорняков.
        </li>
        <li>Удобное окно применения.</li>
        <li>
          Создание почвенного гербицидного экрана, обеспечивающего длительный
          контроль однолетних и некоторых многолетних сорняков, которые
          прорастают из семян, сдерживая последующие волны сорняков в течение
          почти всего периода вегетации.
        </li>
        <li>
          Упрощение процесса контроля сорной растительности благодаря
          эффективному действию гербицида через корни и листья при одноразовом
          послевсходовом применении.
        </li>
        <li>Надежный способ контроля всех рас заразихи.</li>
      </ul>
      <h2>Норма расхода и применение</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1-1,2</td>
            <td>
              Подсолнечник (сорта и гибриды, устойчивые к гербициду Каптора,
              ВРК)
            </td>
            <td>Однолетние злаковые и двудольные сорняки</td>
            <td>
              Опрыскивание посевов в ранние фазы роста сорняков (2-4 листьев) и
              4-5 настоящих листьев у культуры. Ограничения по севообороту:
              можно высевать пшеницу, рожь не ранее, чем через 4 месяца;
              люцерну, сою, ячмень, овес, кукурузу, горох (через 9 месяцев).
              Картофель, томаты, табак, лук, просо, салат, подсолнечник, огурцы,
              морковь можно высевать через 19 месяцев, сахарную и столовую
              свеклу, рапс – через 26 месяцев. Расход рабочей жидкости – 200-300
              л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/singenta/">Syngenta</a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Каптора, ВРК - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Каптора, ВРК" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kaptoravrk;
