import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kleovdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/klopiralid/">Клопиралид</a> 750
        г/кг
      </strong>
      Системный послевходовый гербицид используется как самостоятельно, так и в
      качестве важного компонента в баковых смесях преимущественно для
      уничтожения проблемных сорных видов (ромашки, горца, осота, бодяка) в
      посевах многих сельскохозяйственных культур.
      <h2>Преимущества</h2>
      <ol>
        <li>
          высокая эффективность Клео, ВДГ против таких злостных,
          трудноистребляемых сорняков, как корнеотпрысковые многолетники,
          включая осот розовый (бодяк полевой) и его подвиды, осот желтый (осот
          полевой), осот голубой (молокан татарский), горчак ползучий;
        </li>
        <li>
          благодаря системным свойствам полностью уничтожает не только надземную
          часть, но и корневую систему осотов, тем самым устраняет саму
          возможность их вегетативного размножения;
        </li>
        <li>
          не обладает резистентностью в популяциях чувствительных сорных видов,
          их восприимчивость к гербициду при длительном его применении не
          изменяется.
        </li>
      </ol>
      Норма расхода
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,12</span>
            </td>
            <td>
              <span>Свекла сахарная</span>
            </td>
            <td>
              <span>Все виды ромашки, горца, осота, бодяка</span>
            </td>
            <td>
              <span>Опрыскивание посевов в фазе 1-3 пар листьев культуры.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,12</span>
            </td>
            <td>
              <span>Рапс яровой (семенные посевы)</span>
            </td>
            <td>
              <span>Все виды ромашки, горца, осота, бодяка</span>
            </td>
            <td>
              <span>Опрыскивание посевов в фазе 3-4 листьев культуры.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,12</span>
            </td>
            <td>
              <span>Лен-долгунец</span>
            </td>
            <td>
              <span>Виды ромашки, горца, осота, бодяка</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе “елочки” льна и фазе розетки
                многолетних двудольных сорняков.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,12</span>
            </td>
            <td>
              <span>Лен масличный</span>
            </td>
            <td>
              <span>Виды ромашки, горца, осота, бодяка</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе “елочки” льна и фазе розетки
                многолетних двудольных сорняков.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Агрохим ХХI
      <strong>Упаковка: </strong>1 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Клео, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Клео, ВДГ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kleovdg;
