import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kolombi = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Раннеcпелый высокоолеиновый гибрид подсолнечника для производственной
      системы Clearfield®. Высокоолеиновый гибрид для технологии Clearfield®.
      Контроль заразихи рас F и выше осуществляется с помощью гербицида системы
      Clearfield®. Тип гибрида: для производственной системы Clearfield® Группа
      спелости: раннеcпелый Назначение: высокоолеиновый Содержание олеиновой
      кислоты: до 90% Масличность: 47–49% Высота растений: 150–170 см
      Устойчивость к расам заразихи: A–E Технология возделывания:
      производственная система Clearfield®
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Генетически близок с гибриду САНАЙ МР Содержание олеиновой кислоты
              до 90% Высокие темпы роста на начальных этапах органогенеза
            </td>
            <td>
              Не рекомендуется возделывать на полях с высоким Инфекционным фоном
              фомопсиса Не применять высокие дозы азотных удобрений Не размещать
              после бобовых
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>КОЛОМБИ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="КОЛОМБИ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kolombi;
