import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const konstelans = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LIDEA</strong>
      Среднеранний гибрид. Технология Tropical Dent. Адаптивный к различным
      климатическим условиям. Быстрая влагоотдача зерном. Хорошая устойчивость к
      фузариозу стебля и пыльной головне. ФАО 260 Тип зерна:
      кремнисто-зубовидный Особенности гибрида: Гибрид обладает уникальной
      устойчивостью к возвратным холодам, что позволяет провести ранний посев и
      обеспечить оптимальный сев других культур.
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Агрономический профиль</strong>
            </td>
            <td>
              <strong>Преимущества</strong>
            </td>
          </tr>
          <tr>
            <td>
              Начальные темпы роста: отлично Устойчивость к позднему полеганию:
              отлично Толерантность к пыльной головне: хорошо Толерантность к
              фузариозу початка: отлично Влагоотдача: быстрая
            </td>
            <td>
              Технология Tropical Dent Адаптивный к различным климатическим
              условиям Быстрая влагоотдача зерном Хорошая устойчивость к
              фузариозу стебля и пыльной головне
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>КОНСТЕЛАНС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="КОНСТЕЛАНС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default konstelans;
