import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const kortikvr = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>МЦПА кислоты 300 г/л</strong>
      Гербицид для борьбы с однолетними двудольными сорняками на посевах
      зерновых культур, гороха, льна-долгунца, клевера лугового.
      <h2>Преимущества</h2>
      <ul>
        <li>
          эффективная система защиты важнейших сельскохозяйственных культур;
        </li>
        <li>подавляет широкий спектр однолетних двудольных сорняков;</li>
        <li>отличается высокой селективностью;</li>
        <li>обладает системным действием.</li>
      </ul>
      <h3>Механизм действия</h3>
      Проникает в растения через надземные органы, главным образом, через
      листья, и перемещается по всему организму, достигая точек роста, поэтому
      Кортик часто характеризуют как гербицид «ростового типа действия».
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Норма расхода препарата, л/га, кг/га</strong>
            </td>
            <td>
              <strong>Культура, обрабатываемые объекты</strong>
            </td>
            <td>
              <strong>Сорная и нежелательная растительность</strong>
            </td>
            <td>
              <strong>Способ, время обработки, ограничения</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1–1,5</td>
            <td>Пшеница и тритикале озимые</td>
            <td>Однолетние двудольные</td>
            <td>
              Опрыскивание посевов в фазу кущения – до выхода в трубку культуры
            </td>
          </tr>
          <tr>
            <td>0,8–1,2</td>
            <td>Пшеница яровая</td>
            <td>То же</td>
            <td>То же</td>
          </tr>
          <tr>
            <td>0,8–1,5</td>
            <td>Ячмень яровой</td>
            <td>То же</td>
            <td>То же</td>
          </tr>
          <tr>
            <td>0,9–1,2</td>
            <td>Лен-долгунец</td>
            <td>То же</td>
            <td>
              Опрыскивание посевов в фазу «елочки» при высоте культуры 3–10 см
            </td>
          </tr>
          <tr>
            <td>0,6–0,9</td>
            <td>Горох (на зерно)</td>
            <td>То же</td>
            <td>
              Опрыскивание посевов в фазу 3–5 настоящих листьев культуры (высота
              растений 10–15 см)
            </td>
          </tr>
          <tr>
            <td>0,9–1,2</td>
            <td>Клевер луговой</td>
            <td>То же</td>
            <td>
              Опрыскивание в год посева после появления первого тройчатого листа
              культуры
            </td>
          </tr>
          <tr>
            <td>0,9–1,2</td>
            <td>Клевер луговой под покровом ячменя</td>
            <td>То же</td>
            <td>
              Опрыскивание посевов в фазу 1–2 тройчатых листьев клевера (в фазу
              кущения ячменя)
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Neoport
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Кортик, ВР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Кортик, ВР" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default kortikvr;
