import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const krymv2017godupotratilnapodderzhkuselskogohozjajstva25mlrdrublej = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <div class="news-text-body">
        <a href="http://berkanabio.ru/wp-content/uploads/2018/02/rim.jpg"></a> 
          На госпрограммы развития сельского хозяйства Крыма в 2017 году
        из бюджетов всех уровней было выделено 2,5 млрд рублей, сообщил
        зампредседателя совета министра РК <strong>Юрий Гоцанюк</strong>.
        В общей сложности за последние три года на сельское хозяйство
        полуострова направлено 7,5 млрд рублей, в 2018 году сумма господдержки
        составит 3,6 млрд рублей. Как отметил Юрий Гоцанюк, в этом году в Крыму
        также заработает программа поддержки личных подсобных хозяйств,
        предусматривающая компенсации на строительство тепличных комплексов
        из средств республиканской казны. Приоритетными направлениями развития
        отрасли являются молочное животноводство, садоводство и виноградарство.
        За счет государственного финансирование в последние годы Крым удвоил
        площади виноградников и посадки фруктовых деревьев, полностью обеспечил
        себя мясом птицы. С 2015 года в республике создано более 250
        крестьянских и фермерских хозяйств, а в 2017 году удалось получить
        рекордный урожай зерновых — 1,733 млн тонн, что позволило увеличить
        экспорт на 77% - до 654 тысячи тонн. По итогам прошлого года Крым стал
        первым регионом России по динамике увеличения посевных площадей. В то же
        время, по предварительным данным Крымстата, объем производства продукции
        сельского хозяйства в прошлом году в сопоставимой оценке составил лишь
        94,3% к 2016 году (57,5 млрд рублей). Основной проблемой сельского
        хозяйства Крыма остается высокая себестоимость продукции по причине
        проблем с логистикой и высоких цен на энергоносители, из-за чего
        крымские товары проигрывают конкуренцию продукции из других регионов
        страны. Претензии к завышенной стоимости продуктов в Крыму
        неоднократно предъявляли антимонопольные органы.
      </div>
    </div>
  );

  return (
    <>
      <Head>
        <title>
          Крым в 2017 году потратил на поддержку сельского хозяйства 2,5 млрд
          рублей - Berkana
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Крым в 2017 году потратил на поддержку сельского хозяйства 2,5 млрд рублей"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default krymv2017godupotratilnapodderzhkuselskogohozjajstva25mlrdrublej;
