import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg30179 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Раннеспелый. Очень ранний интенсивный гибрид, высокий потенциал
      урожайности зерна. Высокая скорость отдачи влаги зерном, быстрый стартовый
      рост, раннее цветение помогает избегать стресса в середине вегетационного
      периода, высокая холодостойкость подходит для раннего посева, устойчив к
      различным видам полегания. Группа спелости: Раннеспелый Назначение: Зерно,
      Силос Тип зерна: Кремнисто-зубовидный Среднее кол-во зерен в початке: 14
      шт Среднее кол-во зерен в ряду: 34 шт Средняя высота растения: 240 см
      <table>
        <tbody>
          <tr>
            <td colspan="2">
              <strong>Толерантность к заболеваниям</strong>
              <strong></strong>
            </td>
          </tr>
          <tr>
            <td>
              Энергия начального роста - 8 Потенциал урожая зерна в своей группе
              спелости - 9 Скорость отдачи влаги перед уборкой в своей группе
              спелости - 9 Толерантность к пузырчатой головне - 7
            </td>
            <td>
              Толерантность к пыльной головне - 7 Устойчивость к полеганию - 9
              Толерантность к засухе и другим стрессовым условиям - 8
              Толерантность к фузариозу початка - 7
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 30179 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 30179" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg30179;
