import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg30189 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Раннеспелый. Ранний продукт с отличной влагоотдачей и высоким потенциалом
      урожайности, быстрый стартовый рост. Раннее цветение помогает избегать
      стресса в середине вегетационного периода, отличная устойчивость к
      фузариозу початка, для раннего посева. ФАО 170 Группа спелости:
      Раннеспелый Назначение: Зерно Тип зерна: Зубовидный Среднее кол-во зерен в
      ряду: 33 шт Среднее кол-во рядов в початке: 14-16 шт Средняя высота
      растения: 260 cм
      <table>
        <tbody>
          <tr>
            <td colspan="2">
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Энергия начального роста - 9 Потенциал урожая в своей гр. спелости
              - 9 Скорость отдачи влаги перед уборкой в своей гр. спелости - 9
              Толерантность к пузырчатой головне - 9
            </td>
            <td>
              Толерантность к пыльной головне - 8 Устойчивость к полеганию - 8
              Толерантность к засухе и другим стрессовым факторам - 9
              Толерантность к фузариозу початка - 9
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 30189 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 30189" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg30189;
