import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg50635klp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Потенциал урожайности максимально раскрывается при применении интенсивной
      технологии возделывания. Подходит для наиболее ранних сроков сева.
      Возможно возделывания по минимальной (Mini-Till) и нулевой технологии
      (No-Till) Группа спелости: среднеранний Устойчивость к заразихе: A-G
      Технология возделывания: Clearfield Plus Средний диаметр корзинки, см - 19
      Средняя масса 1000 семян, г - 75 Рекомендуемая густота на момент уборки:
      60-65 тыс./га (зона достаточного увлажнения) 55-60 тыс./га (зона
      недостаточного увлажнения)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Высокоурожайный гибрид; Оптимизирован для производственной системы
              Clearfield® Plus; Гибрид с устойчивостью к заразихе А-G рас;
              Высокая толерантность к основным болезням, включая новые расы
              ложной мучнистой росы; Максимально высокая толерантность к
              ржавчине! Отличная адаптация к различным почвенно-климатическим
              условиям и технологиям выращивания.
            </td>
            <td>
              Фомопсис - 9 Белая гниль корня - 7 Белая гниль корзинки - 7
              Пепельная гниль - 7 Фомоз - 8 Ржавчина - 9 Ложная мучнистая роса -
              8 Вертициллез - 7 Септориоз - 8
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 50635 КЛП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 50635 КЛП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg50635klp;
