import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg50270 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Подходит для возделывания в засушливых регионах с коротким вегетационным
      периодом. Рекомендуется для поздних сроков сева. Группа спелости: ранний
      Устойчивость к заразихе: А-G Рекомендуемая густота на момент уборки: 50-55
      тыс./га (зона достаточного увлажнения) 45-50 тыс./га (зона достаточного
      увлажнения)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Очень раннее созревание с быстрой влагоотдачей; Быстрый стартовый
              рост на начальных стадиях развития; Отличная адаптация к поздним
              срокам сева; Высокая стабильность урожайности в засушливых
              условиях; Устойчив к заразихе А-G рас; Толерантен к новым расам
              ложной мучнистой росы.
            </td>
            <td>
              Фомопсис - 8 Белая гниль корня - 7 Белая гниль корзинки - 8
              Пепельная гниль - 7 Фомоз - 7 Ржавчина - 8 Ложная мучнистая роса -
              9 Вертициллез - 5 Септориоз - 7
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 50270 - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 50270" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg50270;
