import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg50479sh = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Максимальный потенциал гибрид раскрывает на основе применения интенсивной
      технологии возделывания. Не рекомендуется для возделывания на полях с
      агрессивными расами заразихи (&gt;F рас). Группа спелости: ранний
      Устойчивость к заразихе: A-F Технология возделывания: Экспресс Средний
      диаметр корзинки, см - 18 Средняя масса 1000 семян, г - 70 Рекомендуемая
      густота на момент уборки: 55-60тыс./га (зона достаточного увлажнения)
      50-55 тыс./га (зона недостаточного увлажнения)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Высокопродуктивный гибрид нового поколения; Оптимизирован для
              гербицидов Экспресс(тм) Экспресс(тм)Голд; Максимальная
              толерантность ко всем известным расам ЛМР; Отличная толерантность
              к основным болезням (особенно стеблевым формам); Подходит как для
              ранних, так и для поздних сроках сева; Пластичен для различных
              условий выращивания.
            </td>
            <td>
              Фомопсис - 9 Белая гниль корня - 7 Белая гниль корзинки - 7
              Пепельная гниль - 8 Ложная мучнистая роса - 9 Ржавчина - 7
              Вертициллез - 7 Септориоз - 7
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 50479 СХ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 50479 СХ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg50479sh;
