import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg5463kl = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Подходит для возделывания в засушливых регионах с риском поражения
      заразихой. В районах с распространением ржавчины рекомендуется поздний
      срок сева и проведение фунгицидной обработки. Группа спелости: ранний
      Устойчивость к заразихе: A-G Технология возделывания: Clearfield Средний
      диаметр корзинки, см - 18 Средняя масса 1000 семян, г - 72 Рекомендуемая
      густота на момент уборки: 55-60 тыс./га (зона достаточного увлажнения)
      50-55 тыс./га (зона недостаточного увлажнения)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Очень ранний гибрид с высоким потенциалом урожайности; Устойчив к
              гербициду Евро-Лайтнинг® производственной системы Clearfield®;
              Отличная пластичность в условиях засухи; Устойчивость к заразихе
              рас А-G; Отличная адаптация к поздним срокам сева.
            </td>
            <td>
              Фомопсис - 7 Белая гниль корня - 7 Белая гниль корзинки - 6
              Пепельная гниль - 6 Фомоз - 8 Ржавчина - 5 Ложная мучнистая роса -
              7 Вертициллез - 7 Септориоз - 6
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 5463 КЛ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 5463 КЛ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg5463kl;
