import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg5555klp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Гибрид предназначен для засушливых условий! не рекомендуется загущать
      посевы и применять повышенные дозы азотных удобрений. Возможно
      возделывание по минимальной (Mini-Till) и нулевой технологии (No-Till).
      Группа спелости: среднеранний Устойчивость к заразихе: A-G Технология
      возделывания: Clearfield Plus Средний диаметр корзинки, см - 18 Средняя
      масса 1000 семян, г - 71 Рекомендуемая густота на момент уборки: 50-55
      тыс./га (зона недостаточного увлажнения)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Высокий потенциал урожайности; Отличная адаптация к засушливым
              условиям возделывания; Гибрид для производственной системы
              Clearfield® Plus; Высокая стабильность в стрессовых условиях;
              Устойчивость к заразихе A-G рас; Очень быстрая влагоотдача при
              созревании.
            </td>
            <td>
              Фомопсис - 5 Белая гниль корня - 6 Белая гниль корзинки - 6
              Пепельная гниль - 6 Фомоз - 6 Ржавчина - 7 Ложная мучнистая роса -
              7 Вертициллез - 7 Септориоз - 6
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 5555 КЛП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 5555 КЛП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg5555klp;
