import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lg5542kl = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>LG</strong>
      Гибрид предназначен для засушливых условий! Не рекомендуется загущать
      посевы и применять повышенные дозы азотных удобрений. Возможно
      возделывание по экстенсивной технологии. Группа спелости: среднеранний
      Устойчивость к заразихе: A-G Технология возделывания: Clearfield Средний
      диаметр корзинки, см - 18 Средняя масса 1000 семян, г - 72 Рекомендуемая
      густота на момент уборки: 50-55 тыс./га (зона недостаточного увлажнения)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к заболеваниям</strong>
            </td>
          </tr>
          <tr>
            <td>
              Высокая урожайность и стабильность в стрессовых условиях;;
              Устойчив к гербициду Евро-Лайтнинг® производственной системы
              Clearfield®; Отличная адаптация к засушливым условиям
              возделывания; Гибрид с устойчивостью к заразихе рас А-G;
              Адаптирован для выращивания по минимальной (Mini-Till) и нулевой
              технологии (No-Till).
            </td>
            <td>
              Фомопсис - 6 Белая гниль корзинки - 6 Белая гниль корзинки - 6
              Пепельная гниль - 6 Фомоз - 6 Ржавчина - 7 Ложная мучнистая роса -
              7 Вертициллез - 8 Септориоз - 6
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>ЛГ 5542 КЛ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ЛГ 5542 КЛ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lg5542kl;
