import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const lonterrvdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio-lonterr-vdg.jpg"></a>
        <a href="https://berkanabio.ru/category/klopiralid/">Клопиралид</a> 750
        г/кг
      </strong>
      Селективный системный послевходовый, гербицид широкого спектра действия.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Высокая эффективность против трудноискоренимых сорняков (видов осот,
          ромашки, горца, бодяка полевого) многолетних двудольных сорняков,
          включая бодяк и осот.
        </li>
        <li>Отличается высокой биологической эффективностью.</li>
        <li>
          Выраженное системное действие – уничтожает надземную часть и корневую
          систему сорных растений.
        </li>
        <li>Уничтожает осоты на всех стадиях развития.</li>
        <li>Характеризуется высокой селективностью к защищаемым культурам.</li>
        <li>
          Обеспечивает защитное действие в течение всего вегетационного периода.
        </li>
        <li>
          Идеальный компонент с эффектом синергизма при использовании в баковых
          смесях с другими гербицидами.
        </li>
      </ul>
      Норма расхода
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,12</span>
            </td>
            <td>
              <span>Свекла сахарная</span>
            </td>
            <td>
              <span>Все виды ромашки, горца, осота, бодяка</span>
            </td>
            <td>
              <span>Опрыскивание посевов в фазе 1-3 пар листьев культуры.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,12</span>
            </td>
            <td>
              <span>Пшеница озимая и яровая, ячмень яровой, овес</span>
            </td>
            <td>
              <span>
                Однолетние двудольные (виды ромашки, горца) и некоторые
                многолетние (осот, бодяк) сорняки
              </span>
            </td>
            <td>
              <span>Опрыскивание посевов весной в фазе кущения культуры.</span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/gk-zemlyakoff/">
        ЗемлякоФФ
      </a>
      <strong>Упаковка: </strong>0,6 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Лонтерр, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Лонтерр, ВДГ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default lonterrvdg;
