import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const magnijsernokislyj7vodnyj = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/wp-content/uploads/2019/09/345345301.40.png"></a>
      Магний сернокислый семиводный (сульфат магния) - магниевое удобрение,
      хорошо растворимое в воде и не подвергающееся слеживанию. Имеет вид
      кристаллического порошка белого цвета.
      <strong>Химическая формула:</strong> MgSO4 * 7H2O Магний сернокислый
      используют в качестве удобрения в сельском хозяйстве, в производстве
      синтетических моющих средств, в медицине как успокаивающее, в химической
      промышленности - при производстве пербората натрия. Т.к. сульфат магния
      хорошо водорастворим, он может применяться через любые системы полива для
      проведения подкормок овощных, декоративных и других культур. При основном
      внесении применяется совместно с азотными и фосфорными удобрениями.
      <h2>Норма расхода и применение</h2>
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культура</strong>
            </td>
            <td>
              <strong>Доза применения препарата</strong>
            </td>
            <td>
              <strong>Способ, время, особенности применения препарата</strong>
            </td>
          </tr>
          <tr>
            <td rowspan="2">Огурцы</td>
            <td>70-100 кг/га</td>
            <td>
              Основное внесение весной совместно с азотными и фосфорными
              удобрениями
            </td>
          </tr>
          <tr>
            <td>30-50 кг/га</td>
            <td>
              Корневые подкормки (совместно с азотными удобрениями) с интервалом
              10-15 дней (4-5 раз в вегетационный период).
            </td>
          </tr>
          <tr>
            <td rowspan="2">Томаты</td>
            <td>70-100 кг/га</td>
            <td>
              Основное внесение весной совместно с азотными и фосфорными
              удобрениями.
            </td>
          </tr>
          <tr>
            <td>30-50 кг/га</td>
            <td>
              Корневые подкормки (совместно с азотными удобрениями) с интервалом
              10-20 дней (4-5 раз в вегетационный период).
            </td>
          </tr>
          <tr>
            <td>Овощные, ягодные, декоративные культуры</td>
            <td>120-150 кг/га</td>
            <td>
              Основное внесение весной совместно с азотными и фосфорными
              удобрениями.
            </td>
          </tr>
          <tr>
            <td>Плодовые деревья</td>
            <td>
              30-35 г/м<sup>2</sup> приствольного круга
            </td>
            <td>Подкормка весной</td>
          </tr>
          <tr>
            <td>Все кльтуры</td>
            <td>1,5-2,0% 75-100 кг/га Расход рабочей жидкости 50-200 л/га</td>
            <td>
              Некорневая подкормка (опрыскивание) в период вегетации
              (формирование плодов и корнеплодов) 1 раз в 3-4 недели.
            </td>
          </tr>
          <tr>
            <td>Защищенный грунт</td>
            <td>Концентрация раствора 0,1-0,2%</td>
            <td>
              Подкормка через системы полива, дождевания или капельного полива.
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Буйский химзавод
      <strong>Упаковка:</strong> 25 кг, 750 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Магний сернокислый 7-водный - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Магний сернокислый 7-водный"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default magnijsernokislyj7vodnyj;
