import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const majsterpauermd = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        Йодосульфурон-метил-натрий 1 г/л + Тиенкарбазон-метил 10 г/л +
        Форамсульфурон 31,5 г/л + Ципросульфамид 15 г/л
      </strong>
      Универсальный послевсходовый гербицид для контроля полного спектра сорных
      растений в посевах кукурузы.
      <h2>Преимущество</h2>
      Полный контроль сорняков: - высокая эффективность против всех видов
      сорняков в посевах кукурузы в любых почвенно-климатических условиях; -
      баковые смеси не нужны. Почвенный «экран»: - контроль 2-й волны сорняков.
      Новая препаративная форма (масляная дисперсия): - эффект «сжигания»
      вегетирующих сорняков; -прилипатели не нужны. «Мягкий» для культуры: -
      благодаря антидоту нового поколения.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>1,25-1,5</span>
            </td>
            <td>
              <span>Кукуруза (зеленая масса, зерно, силос)</span>
            </td>
            <td>
              <span>
                Однолетние и многолетние двудольные и злаковые сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 3-6 листьев культуры и ранние фазы
                роста сорняков.
              </span>
              <span>Расход рабочей жидкости - 150-250 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/bajer/">Байер</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>МайсТер Пауэр, МД - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="МайсТер Пауэр, МД"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default majsterpauermd;
