import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const mantravrk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/imazamoks/">Имазамокс</a> 33 г/л
        + <a href="https://berkanabio.ru/category/imazapir/">Имазапир</a> 15 г/л
      </strong>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>1-1,2</span>
            </td>
            <td>
              <span>
                Подсолнечник (сорта и гибриды, устойчивые к имидазолинонам)
              </span>
            </td>
            <td>
              <span>Однолетние злаковые и двудольные сорняки</span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в ранние фазы роста сорняков (2-4 листьев)
                и 4-5 настоящих листьев у культуры. Ограничения по севообороту:
                можно высевать пшеницу, рожь не менее, чем через 4 месяца;
                люцерну, сою, ячмень, овес, кукурузу, горох-через 9 месяцев.
                Картофель, томаты, табак, лук, просо, салат, подсолнечник,
                огурцы, морковь можно высевать через 19 месяцев, сахарную и
                столовую свеклу, рапс – через 26 месяцев. Расход рабочей
                жидкости – 200-300 л/га
              </span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Агрохим-XXI
      <strong>Упаковка: </strong>10 л  
    </div>
  );

  return (
    <>
      <Head>
        <title>Мантра, ВРК - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Мантра, ВРК" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default mantravrk;
