import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const mas15t = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>MAS SEEDS</strong>
      Раннеспелый. Самый сухой при уборке в своем сегменте. Высокая
      засухоустойчивость, хорошая влагоотдача, экономия затрата на сушку,
      максимальная толерантность к фузариозу початка. ФАО 200 Тип зерна:
      кремнистый-зубовидный Группа спелости: раннеспелый Использование: Зерно
      Кол-во рядов: 14 Кол-во зерен в ряду: 26-30 Масса 1000 семян: 300-330
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Aгрономия</strong> (1-3 низкий | 4-6 средний | 7-9 хороший
              близкий к отличному)
            </td>
            <td>
              <strong>Толерантность к болезням</strong> (1-3 низкий | 4-6
              средний | 7-9 хороший близкий к отличному)
            </td>
          </tr>
          <tr>
            <td>
              Развитие на ранних этапах - 7 Эффект Stay green - 7 Влагоотдача -
              9 Полегание - 7 Засухоустойчивость - 9
            </td>
            <td>
              Устойчивость к гельминтоспориозу - 7 Фузариоз стебля - 6 Фузариоз
              початка - 8
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>МАС 15.Т - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="МАС 15.Т" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default mas15t;
