import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const mas34b = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>MAS SEEDS</strong>
      Среднеранний. Феноменальный потенциал урожайности. Потенциально достигает
      160 ц/га, высокая пластичность в условиях жаркого континентального
      климата. Быстрая влагоотдача. ФАО 300 Группа спелости: среднеранний
      Использование: Зерно Высота растения: средненизкая Тип зерна: зубовидный
      Кол-во рядов: 16-18 Кол-во зерен в ряду: 28-32 Масса 1000 семян: 320-340
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Aгрономия</strong> (1-3 низкий | 4-6 средний | 7-9 хороший
              близкий к отличному)
            </td>
            <td>
              <strong>Толерантность к болезням</strong> (1-3 низкий | 4-6
              средний | 7-9 хороший близкий к отличному)
            </td>
          </tr>
          <tr>
            <td>
              Развитие на ранних этапах - 9 Эффект Stay green - 6 Влагоотдача -
              8 Полегание - 7 Засухоустойчивость - 8
            </td>
            <td>
              Устойчивость к гельминтоспориозу - 8 Фузариоз стебля - 6 Фузариоз
              початка - 7
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>МАС 34.Б - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="МАС 34.Б" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default mas34b;
