import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const mas80d = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Masseeds</strong>
      МАС 80.Д способен к быстрой влагоотдаче в конце жизненного цикла растения.
      Оптимально подходит для позднего сева и северных регионов и, как
      результат, уборка с максимально низкой влажностью. Цветение: раннеспелый
      Группа спелости: раннеспелый Количество дней вегетации: 90 - 95 Тип:
      линолевый Высота растения: средненизкая Форма корзинки: выпуклая Положение
      корзинки: полностью наклонена Масса 1000 семян: 52 - 60 Содержание масла
      (%): 52 % Сумма температур (начиная от 6°)
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Толерантность к болезням</strong>
            </td>
          </tr>
          <tr>
            <td>
               Идеален для регионов, где нужен ультрараний подсолнечник.
              Стабилен вне зависимости от региона возделывания. Быстрое
              созревание и влагоотдача. Низкорослое растение. Технологичен для
              уборки.
            </td>
            <td>
              Ложная мучнистая роса: RM9 Фомопсис: 8 Склеротиния корзинки: 8
              Склеротиния стебля: 8
              <em>
                1-3 низкий | 4-6 средний | 7-9 хороший близкий к отличному
              </em>
            </td>
          </tr>
        </tbody>
      </table>
         
    </div>
  );

  return (
    <>
      <Head>
        <title>МАС 80.Д - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="МАС 80.Д" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default mas80d;
