import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const mas92kp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Masseeds</strong>
      Инвестируй в лучший результат! Цветение: среднеранний Группа спелости:
      среднеспелый Количество дней вегетации: 105 - 110 Тип: линолевый Высота
      растения: средневысокая Форма корзинки: выпуклая Положение корзинки:
      наклонена Масса 1000 семян: 53 - 59 Содержание масла (%): 51 %
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к болезням</strong>
            </td>
          </tr>
          <tr>
            <td>
              НОВАЯ ТЕХНОЛОГИЯ CLEARFIELD PLUS. Новая технология Clearfield
              Plus. Уничтожение максимального спектра сорняков. Улучшенная
              генетика. Отличная стрессоустойчивость. Гарантия хорошего урожая в
              любых условиях.
            </td>
            <td>
              Ложная мучнистая роса: RM9 Фомопсис: 8 Склеротиния корзинки: 9
              Склеротиния стебля: 9
              <em>
                1-3 низкий | 4-6 средний | 7-9 хороший близкий к отличному
              </em>
            </td>
          </tr>
        </tbody>
      </table>
      Толерантность к болезням Ложная мучнистая роса RM9 Фомопсис 8 Склеротиния
      корзинки 9 Склеротиния стебля 9 1-3 низкий | 4-6 средний | 7-9 хороший
      близкий к отличному Рекомендации Оптимальные условия Неблагоприятные
      условия Адаптация + + + + + + + + Густота стояния (раст./га) 60 000 55 000
      МАС 92.КП подходит для полей с любым типов почвы и потенциалом. Наилучшие
      результаты урожайности достигаются при раннем севе. Отличная устойчивость
      к болезням обеспечивает сохранность растений до самой уборки.
    </div>
  );

  return (
    <>
      <Head>
        <title>МАС 92.КП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="МАС 92.КП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default mas92kp;
