import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const mas91g = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Masseeds</strong>
      Повышенная устойчивость к заразихе. Технологичная уборка Форма корзинки:
      слегка выпуклая, наклонена Цветение: среднераннее Высота растения: низкая
      Масличность: 49% Масса 1000 зерен :  45-50 г
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Толерантность к болезням</strong>
            </td>
          </tr>
          <tr>
            <td>
              Устойчивость к агрессивным расам заразихи до G+. Низкорослый
              гибрид (технологичная уборка) Стрессоустойчивость в период
              цветения (отличное опыление, выполненные корзинки). Экстенсивная
              технология возделывания (подходит для регионов с ограниченным
              количеством влаги: Дон, Волга, Урал).
            </td>
            <td>
              Устойчивость к засухе: 9. Устойчивость к полеганию: 8.
              Устойчивость к заразихе – 7 рас:  (A-G). Устойчивость к ложной
              мучнистой росе: RM8. Устойчивость к фомопсису: 8. Устойчивость к
              гнилям стебла, корзинки: 8.
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>Мас 91.Г - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Мас 91.Г" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default mas91g;
