import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const meridianvr = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_meridian-vr.jpg"></a>
        <a href="https://berkanabio.ru/category/klopiralid/">Клопиралид</a> 267
        г/л + <a href="https://berkanabio.ru/category/pikloram/">Пиклорам</a>,
        пиклорам (диметилэтаноламинные соли) 67 г/л
      </strong>
      Эффективный послевсходовой гербицид для борьбы с двудольными сорняками в
      посевах рапса.
      <h3>Спектр действия препарата</h3>
      Препарат на основе клопиралида и пиклорама используется для уничтожения
      однолетних и многолетних двудольных сорняков, в том числе устойчивых к
      2,4-Д и 2М-4Х, главным образом, из семейства сложноцветных и гречишных:
      ромашки, осота полевого, бодяка полевого, латука татарского, одуванчика,
      осота, горца, гречишки вьюнковой и др., в посевах рапса. Успешно
      уничтожает наиболее проблемные для посевов рапса двудольные сорняки, такие
      как осоты, ромашки, васильки, крестовник.
      <h3>Механизм действия</h3>
      Клопиралид и пиклорам обладают системным действием, легко проникает в
      растение, в основном, через листья (но может и через корни); быстро
      распространяется по всему растению, включая корневую систему, блокируя
      точки роста меристематических тканей. Действие гербицида основано на
      реакции ауксинового типа. Являясь синтетической формой натуральных
      растительных гормонов, клопиралид и пиклорам замещают натуральные гормоны
      растения, блокируя их функции. Перенасыщение синтетическими гормонами
      приводит к нарушению ростовых процессов и гибели растений. Уничтожается
      как наземная часть, так и корневая система сорняков, включая почки
      вегетативного возобновления и корневые отпрыски осотов.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,3-0,35</span>
            </td>
            <td>
              <span>Рапс яровой и озимый</span>
            </td>
            <td>
              <span>
                Однолетние и многолетние двудольные сорняки, в т.ч. подмаренник
                цепкий, виды ромашки, горца, щирицы, мари, гречишка вьюнковая,
                виды бодяка и осота и другие
              </span>
            </td>
            <td>
              <span>
                Опрыскивание вегетирующих растений весной с фазы 3-6 настоящих
                листьев до появления цветочных бутонов у рапса.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/neoport/">Neoport</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Меридиан, ВР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Меридиан, ВР" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default meridianvr;
