import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const milenaks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2020/08/berkanabio_milena-ks.jpg"></a>
        <a href="https://berkanabio.ru/category/nikosulfuron/">Никосульфурон</a>{" "}
        40 г/л
      </strong>
      Послевсходовый системный гербицид избирательного действия для борьбы со
      злаковыми и некоторыми двудольными сорняками на посевах кукурузы.
      <h2>Преимущество</h2>
      Селективный послевсходовый гербицид избирательного действия для защиты
      кукурузы от сорняков, включая злостные сорняки, такие как пырей и гумай.
      Не фитотоксичен для культуры, что позволяет использовать препарат в
      широком диапазоне фаз развития.
      <h2>Механизм действия</h2>
      Никосульфурон проникает в растения через надземные органы и корни, хорошо
      передвигается по флоэме и ксилеме. Он подавляет биосинтез валина и
      изолейцина в растении. В результате в зонах роста сорняков прекращается
      деление клеток, что приводит к отмиранию растений.
      <h2>Норма расхода и применение</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1-1,5</td>
            <td>Кукуруза на зерно и силос</td>
            <td>
              Однолетние и многолетние злаковые и некоторые однолетние
              двудольные сорняки
            </td>
            <td>
              Опрыскивание посевов в фазе 3-6 листьев культуры и ранние фазы
              роста сорняков (2-6 листьев у однолетних и при высоте 10-20 см у
              многолетних сорняков). Расход рабочей жидкости –200-400 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/neoport/">Neoport</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Милена, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Милена, КС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default milenaks;
