import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const minselhoznazvalsrokiprinjatijareshenijapoproduktsiispalmovymmastom =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        Решение о введении маркировки продукции с пальмовым маслом в рамках
        Евразийского экономического союза (ЕАЭС) может быть принято в течение
        двух месяцев Об этом заявил первый замглавы Минсельхоза РФ Джамбулат
        Хатуов, передает РИА Новости в пятницу, 15 апреля. «Началось
        рассмотрение на нашей Евразийской площадке. Думаю, что согласие будет —
        нужна маркировка. Инициатива российской стороны уже обозначена, мы
        обратились [в комиссию ЕАЭС]. Есть существующие регламенты, я думаю, что
        в ближайшие два месяца по этому поводу решение уже появится», — сказал
        Хатуов. Он отметил, что вопрос о роли и вреде пальмового масла требует
        глубокого анализа. «Этим занимается Роспотребнадзор, и мы рассчитываем,
        что совместные мероприятия Роспотребнадзора, Россельхознадзора,
        Минсельхоза, Минпромторга будут сведены к тому, что возможное
        ненадлежащее конкурентное преимущество производителей, которые в
        нарушение существующих стандартов пытаются применять растительные масла
        вместо животных, должно быть прекращено», — подчеркнул Хатуов. Говоря о
        целесообразности введения акциза на пальмовое масло, Хатуов отметил,
        что, по его личному мнению, это преждевременная мера, которая не даст
        положительного результата. По его мнению, сегодня особое внимание надо
        уделять модернизации молочных предприятий, ужесточению определенных
        требований со стороны Роспотребнадзора на рынке готовой продукции. «Мы
        считаем, что комплексная работа будет эффективной», — указал он.
        Президент РФ Владимир Путин в четверг в ходе прямой линии 14 апреля
        поддержал предложение воронежского фермера сообщать на упаковках
        продуктов о содержании в их составе пальмового масла. Он подчеркнул, что
        решение подобных вопросов согласовывать с партнерами по ЕАЭС. При этом
        глава государства не исключил введения акцизов на пальмовое масло, если
        идея с отметкой на упаковке будет отвергнута. Читать полностью: 
        <a href="http://www.agroxxi.ru/rossiiskie-agronovosti/minselhoz-nazval-sroki-prinjatija-reshenija-po-produkcii-s-palmovym-maslom.html">
          www.agroxxi.ru
        </a>
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Минсельхоз назвал сроки принятия решения по продукции с пальмовым
            мастом - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Минсельхоз назвал сроки принятия решения по продукции с пальмовым мастом"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default minselhoznazvalsrokiprinjatijareshenijapoproduktsiispalmovymmastom;
