import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const minselhozrossiiplaniruetusovershenstvovatzakonodatelstvovsferefitosanitarnogonadzoraisemenovodstva =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        В Минсельхозе России под председательством первого заместителя Министра
        сельского хозяйства Джамбулата Хатуова состоялось совещание, на котором
        были рассмотрены предложения Уполномоченного при Президенте Российской
        Федерации по защите прав предпринимателей Бориса Титова в части
        совершенствования законодательства в сфере карантинного фитосанитарного
        надзора и семеноводства, а также перевозки крупногабаритных
        сельскохозяйственных грузов. Во встрече приняли участие представители
        Минэкономразвития России, Россельхознадзора, антимонопольной и
        таможенной служб, а также отраслевых союзов и ассоциаций. Представители
        Аппарата Уполномоченного при Президенте России отметили эффективную
        работу Минсельхоза России по разработке широкого комплекса подзаконных
        нормативных правовых актов в области карантина растений. Речь на встрече
        также шла об отраслевых вопросах, которые, по мнению представителей
        аппарата обмудсмена по защите предпринимателей, требуют дополнительной
        проработки. Директор Департамента растениеводства, механизации,
        химизации и защиты растений Минсельхоза России Петр Чекмарев подчеркнул,
        что дальнейшее совершенствование нормативной правовой базы в этой сфере
        будет способствовать повышению статуса России как крупного экспортера
        продукции растениеводства, а также росту экспортного потенциала страны и
        преодолению зависимости от импорта посевного материала. Джамбулат Хатуов
        предложил представителям Аппарата Уполномоченного ежемесячно проводить
        такие встречи, на которых заинтересованные стороны смогут обсуждать
        возникающие вопросы и совместно прорабатывать пути их решения. Источник:
        официальный сайт Минсельхоза РФ
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Минсельхоз России планирует усовершенствовать законодательство в
            сфере фитосанитарного надзора и семеноводства - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Минсельхоз России планирует усовершенствовать законодательство в сфере фитосанитарного надзора и семеноводства"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default minselhozrossiiplaniruetusovershenstvovatzakonodatelstvovsferefitosanitarnogonadzoraisemenovodstva;
