import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const minselhozrfzajmetsjastimulirovanievnedrenijanovyhtehnologijvlnovodstvoikonoplevodstvo =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        Перспективы развития льноводства и коноплеводства в России обсуждали на
        совещании в министерстве сельского хозяйства России. В видеоконференции,
        проходившей под председательством первого замминистра сельского
        хозяйства РФ Джамбулата Хатуова, приняли участие представители
        Минпромторга России, отраслевых союзов и ассоциаций, а также
        региональных органов управления агропромышленным комплексом.
        <div class="l-font">
          В ходе совещания участники обсудили текущее состояние льноводческой и
          коноплеводческой подотраслей, а также результаты реализации мер
          господдержки производства волокна. Как отмечают в Минсельхозе, на
          сегодняшний день лен и конопля являются основными источниками
          натурального волокнистого сырья в России: сказался рост цен на
          импортный хлопок. Производителям доступны льготные краткосрочные и
          инвестиционные кредиты, различные виды субсидирования, в том числе
          возмещение части понесенных затрат на создание или модернизацию
          проектов АПК. По словам Джамбулата Хатуова, в развитии льноводства и
          коноплеводства особое внимание необходимо уделить стимулированию
          технического перевооружения подотраслей и внедрению новых технологий в
          производство. Минсельхоз России совместно с Минпромторгом России и
          региональными органами власти продолжит разработку и совершенствование
          мер господдержки. Стратегия дальнейшего развития льноводства и
          коноплеводства в России планируют определить на предстоящем
          всероссийском совещании. Источник: 
          <a
            href="http://www.oilworld.ru/news/270696"
            rel="noopener"
            target="_blank"
          >
            www.oilworld.ru
          </a>
        </div>
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Минсельхоз РФ займется стимулирование внедрения новых технологий в
            льноводство и коноплеводство - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Минсельхоз РФ займется стимулирование внедрения новых технологий в льноводство и коноплеводство"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default minselhozrfzajmetsjastimulirovanievnedrenijanovyhtehnologijvlnovodstvoikonoplevodstvo;
