import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const neovdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio-neo-vdg.jpg"></a>
        <a href="https://berkanabio.ru/category/nikosulfuron/">Никосульфурон</a>{" "}
        750 г/кг
      </strong>
      Гербицид для борьбы с сорными растениями на посевах кукурузы.
      <h2>Преимущество</h2>
      <ul>
        <li>
          послевсходовый системный гербицид избирательного действия для
          кукурузы, выращиваемой на зерно или силос;
        </li>
        <li>
          превосходное действие против злаковых и некоторых двудольных сорняков,
          включая злостные многолетние,
        </li>
        <li>
          прорастающие как из семян, так и из корневищ, например, гумай, пырей;
        </li>
        <li>
          возможность применения в широком диапазоне фаз развития культуры;
        </li>
        <li>
          удобство и простота в приготовлении качественного рабочего раствора
          благодаря добавлению поверхностно
        </li>
        <li>активных веществ;</li>
        <li>короткий период распада в почве.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,08-0,1</span>
            </td>
            <td>
              <span>Кукуруза (кроме кукурузы на масло)</span>
            </td>
            <td>
              <span>
                Однолетние и многолетние злаковые и некоторые однолетние
                двудольные сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 3-6 листьев культуры и ранние фазы
                роста сорняков (2-6 листьев у однолетних и при высоте 10-20 см у
                многолетних).
              </span>
              <span>Расход рабочей жидкости - 200-400 л/га</span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,05-0,06</span>
            </td>
            <td>
              <span>Кукуруза (кроме кукурузы на масло)</span>
            </td>
            <td>
              <span>
                Однолетние и многолетние злаковые и некоторые однолетние
                двудольные сорняки
              </span>
            </td>
            <td>
              <span>Опрыскивание посевов в фазе</span>
              <span>
                3-6 листьев культуры и ранние фазы роста сорняков (2-6 листьев у
                однолетних и при высоте 10-20 см у многолетних) в смеси с 300
                мл/га ПАВ Микс, Ж.
              </span>
              <span>Расход рабочей жидкости - 200-400 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/rosagrohim/">РосАгроХим</a>
      <strong>Упаковка: </strong>250 г
    </div>
  );

  return (
    <>
      <Head>
        <title>НЭО, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="НЭО, ВДГ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default neovdg;
