import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const nitrofikszh = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2020/09/nitrifix-g-1.png"
          rel="attachment wp-att-3245"
        ></a>
        Bradirhizobium japonicum – соя , Mesorhizobiumciceri – нут, Rhizobium
        leguminosarum – горох, чечевица, Sinorhizobium meliloti – люцерна.
      </strong>
      Инокулянт для обработки семян зернобобовых культур. Предназначен для
      образования клубеньков, обеспечения растений доступным азотом и накопления
      его в почве. Жидкость коричневого цвета. Количество жизнеспособных клеток:
      не менее 2,5×109 КОЕ/мл к концу срока хранения. Условия хранения:
      температура для длительного хранения от +4 до +10°С. Температура для
      краткосрочного хранения (72 часа) от +10 до +20°С. Хранить в защищенном от
      света месте.
      <h3>Преимущества</h3>
      <ul>
        <li>Способствует своевременному образованию клубеньков;</li>
        <li>
          Обеспечивает биологическую фиксацию атмосферного азота (60-80% от
          общей потребности растения);
        </li>
        <li>Способствует накоплению азота в почве;</li>
        <li>
          Обеспечивает растение азотом по фазам максимального потребления;
        </li>
        <li>Повышает урожайность и увеличивает содержание протеина в бобах;</li>
        <li>Не требует дополнительных операционных затрат на применение;</li>
        <li>
          Является эффективной альтернативой минеральным азотным удобрениям.
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Бактерии проникают в корни бобовых растений через корневые волоски, где
      интенсивно размножаются и стимулируют вокруг своих очагов быстрое деление
      клеток с образованием клубеньков фиксирующих азот.
      <h3>Норма расхода и применение</h3>
      Рекомендуется применение инокулянта с биопротравителем «Респекта» на
      основе бактерий Pseudomonas aureofaciens, которые не угнетают клубеньковые
      бактерии. Для эффективного функционирования симбиотических связей растения
      и бактерий необходимо соблюдение следующих условий: наличие в почве
      фосфора не ниже 2,5 мг/100 г почвы;
      <a
        href="https://berkanabio.ru/nitrofiks-zh/nitrofix_g/"
        rel="attachment wp-att-3242"
      ></a>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      <strong>Упаковка:</strong> «Bag-in-Box» – полипропиленовый пакет объемом 2
      л. в картонной коробке.
    </div>
  );

  return (
    <>
      <Head>
        <title>Нитрофикс® Ж - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Нитрофикс® Ж" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default nitrofikszh;
