import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const nitraginzhbobovye = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/341234234.png"></a>
        Препарат на основе клубеньковых бактерий (рода Bradyrhizobium japonicum)
      </strong>
      Применятся для обработки семян сои, нута и других бобовых культур,
      улучшения плодородия почв
      <h2>Преимущества</h2>
      Нитрагин, Ж применятся для обработки семян сои, нута и других бобовых
      культур, улучшения плодородия почв. В 1 мл препарата содержится не менее 5
      млрд. активных клубеньковых бактерий, которые сохраняют свою
      жизнеспособность длительное время. Так же препарат в своём составе
      содержит адъювант (прилипатель).
      <ul>
        <li>
          экономия минеральных удобрения. Симбиотическая азотфиксация
          обеспечивает до 70-80% потребности сои в азоте;
        </li>
        <li>
          азот поступает в растение по мере необходимости и максимальное
          потребление обеспечивается в критические фазы развития культуры;
        </li>
        <li>
          повышение плодородия и активизация почвенной микрофлоры благодаря
          биологическому азоту;
        </li>
        <li>увеличение урожайности сои и содержания протеина.</li>
      </ul>
      <h3>Применениние</h3>
      Для обработки одной гектарной нормы семян сои и нута необходимо
      использовать 200 мл (га /порция) Нитрагина, Ж. Гектарную норму инокулянта,
      разбавленного водой, тщательно перемешивают с гектарной порцией семян сои
      или нута. Для приготовления рабочего раствора используют только чистую
      нехлорированную воду. Обработку семян фунгицидными протравителями проводят
      не менее чем за 5 дней до инокуляции.
      <h3>Совместимость</h3>
      Не совместим!!! с химическими ртутьсодержащими протравителями и
      протравителями на основе д.в. тирам (ТМТД). Допускается совместная
      обработка в день посева в баковой смеси с протравителями только на основе
      д.в. беномил (Фундазол). Обработанные семена необходимо высеять в течение
      двух недель. Избегать воздействия прямых солнечных лучей на инокулянт и
      обработанные семена. После вскрытия упаковки препарат и приготовленный
      рабочий раствор использовать в течение суток.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/agrokom/">ООО "АгроКом"</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Нитрагин Ж (бобовые) - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Нитрагин Ж (бобовые)"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default nitraginzhbobovye;
