import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const nkfalkon = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>SYNGENTA</strong>
      Раннеспелость и урожайность. Хорошая устойчивость к стрессовым условиям.
      Отличная холодостойкость. Быстро развивается на ранних этапах вегетации.
      Назначение: зерно, силос, спирт, крупа, корнаж ФАО: 190 Тип зерна:
      кремнисто-зубовидный Потенциал урожайности зерна - 8 Засухоустойчивость -
      8 Скорость раннего развития - 10 Холодостойкость - 10 Скорость влагоотдачи
      - 7 Устойчивость к полеганию - 10
      <table>
        <tbody>
          <tr>
            <td>Преимущества</td>
            <td>Толерантность к болезням</td>
          </tr>
          <tr>
            <td>
              Устойчив к полеганию. Пригоден для пожнивного посева. Растение
              типа Stay Green - да
            </td>
            <td>гельминтоспориоз фузариоз початка стеблевые гнили</td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>НК ФАЛЬКОН - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="НК ФАЛЬКОН" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default nkfalkon;
