import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const operativnajainformatsijaobeksportezernaiproduktovegopererabotkiizrossijskojfederatsiina29fevralja2016goda =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        По данным территориальных управлений Россельхознадзора экспорт зерна и
        продуктов его переработки составил за период: с 1 января по 29 февраля
        2016 года — 4,68 млн. т,в том числе пшеницы — 2,76 млн. т (59%).
        Преимущественно отгрузка на экспорт зерна и продуктов его переработки
        осуществлялась через порты: Краснодарского края и Ростовской области. С
        начала 2015-2016 сельхозгода (с 1 июля 2015 года по 29 февралят.г.) на
        экспорт отгружено 27,60 млн. т зерна, в том числе пшеницы — 18,81 млн. т
        или 69 %. С 1 июля по 28 февраля 2014-2015 сельхозгода экспортные
        поставки зерна и продуктов его переработки составили 28,53 млн. тонн, в
        том числе пшеницы — 19,23 млн. тонн. Источник: 
        <a href="http://www.zol.ru/n/25f27">www.zol.ru</a>
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Оперативная информация об экспорте зерна и продуктов его переработки
            из Российской Федерации на 29 февраля 2016 года - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Оперативная информация об экспорте зерна и продуктов его переработки из Российской Федерации на 29 февраля 2016 года"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default operativnajainformatsijaobeksportezernaiproduktovegopererabotkiizrossijskojfederatsiina29fevralja2016goda;
