import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const opytprimeneniepreparatovseriistimiks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      https://youtu.be/PbLHlJMoWNI Опыт применения адаптивной технологии на
      протяжении 3-х лет в к/х Новая Жизнь Аннинского района Воронежской
      области. В 2014 году была получена урожайность озимой пшеницы 85 ц/га на
      площади 361 гектар, где последовательно проводилось внедрение адаптивной
      технологии. Отдельные участки давали свыше 100 ц/га. В среднем по
      хозяйству в 2014 году получили урожай озимой в 58,1 ц/га
    </div>
  );

  return (
    <>
      <Head>
        <title>Опыт применение препаратов серии Стимикс - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Опыт применение препаратов серии Стимикс"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default opytprimeneniepreparatovseriistimiks;
