import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const organitn = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="http://berkanabio.ru/organit-n/organit-n-2/"
          rel="attachment wp-att-1274"
        ></a>
        Биоудобрения. 
      </strong>
      Улучшение питания сельско-хозяйственных культур путем фиксации
      атмосферного азота.
      <strong>Состав:</strong> Клетки штамма Azospirillum zeae (титр не менее
      1х109 КОЕ/мл).
      <strong>Период защитного действия:</strong> В зависимости от погодных
      условий сохраняется на период от 20 до 60 суток.
      <strong>Совместимость:</strong> Совместим с химическими СЗР в баковых
      смесях.
      <strong>Условия и срок хранения:</strong> Препарат хранят в упаковке
      предприятия — изготовителя в сухих, чистых, вентилируемых, защищенных от
      воздействия прямых солнечных лучей и атмосферных осадков помещениях при
      температуре от +50С до +150С и относительной влажности не более 75% в
      течение 12 месяцев со дня изготовления. После вскрытия препарат можно
      использовать в течение 7 суток. Рабочий раствор использовать в течение 24
      часов после приготовления.
      <strong>Препаративная форма:</strong> Непрозрачная жидкость от светло —
      коричневого до темно-коричневого цвета.
      <strong>Класс опасности:</strong> IV (малоопасное)
      <h2>Механизм действия</h2>
      Основная функция препарата — улучшение азотного питания
      сельскохозяйственных культур, за счет способности бактерий Azospirillum
      zeae фиксировать атмосферный азот и переводить его в формы, пригодные для
      потребления растением. Также препарат позволяет улучшить ростовые
      характеристики культурных растений, за счет синтеза ряда веществ
      фитогормональной природы.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/bionovatik/">Bionovatik</a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Organit N - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Organit N" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default organitn;
