import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const orgamicaf = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="http://berkanabio.ru/wp-content/uploads/2018/12/Orgamica-F-1.jpg"
          rel="attachment wp-att-1291"
        ></a>
        Биофунгицид. 
      </strong>
      Направленное действие против возбудителей болезней сельскохозяйственных
      культур. Разлагает стерню.
      <strong>Состав:</strong> Конидии штамма Trichoderma asperellum (титр не
      менее 1х108 КОЕ/мл).
      <strong>Период защитного действия:</strong> После обработки семян фунгицид
      Orgamica F действует на корнях растений в течение всего периода вегетации.
      На стеблях и листьях растений биопрепарат действует в течение 10-15 дней,
      в зависимости от степени инфицированности и погодных условий.
      <strong>Совместимость:</strong> Совместим в баковых смесях с большинством
      пестицидов. Однако, возможно проявление физико-химической несовместимости
      препаратов, поэтому рекомендуется перед смешиванием и применением провести
      тест на совместимость.
      <strong>Условия и срок хранения:</strong> Препарат хранить в упаковке
      предприятия — изготовителя в сухих, чистых, вентилируемых, защищенных от
      воздействия прямых солнечных лучей и атмосферных осадков помещениях при
      температуре от +50С до +150С в течение 10 месяцев со дня изготовления.
      После вскрытия препарат можно использовать в течение 7 суток. Рабочий
      раствор использовать в течение 24 часов после приготовления.
      <h2>Механизм действия</h2>
      Механизм действия этого препарата обусловлен способностью гриба:
      <ul>
        <li>
          колонизировать максимально возможное жизненное пространство и
          поглощать максимальное количество подходящих питательных веществ, в
          местах своего применения. Создавая, таким образом, неблагоприятные
          условия для фитопатогенных организмов;
        </li>
        <li>
          атаковать возбудителей заболеваний растений прежде, чем те достигнут
          корневой системы сельскохозяйственных культур. Гриб из состава
          препарата способен быстро расти и опутывает своими гифами мицелий
          фитопатогена, проникая внутрь и извлекая питательные вещества. В
          конечном итоге фитопатоген погибает и исключается из данного
          агробиоценоза.
        </li>
      </ul>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/bionovatik/">Bionovatik</a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Orgamica F - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Orgamica F" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default orgamicaf;
