import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const peterburgskijtraktornyjzavodnachalpostavljattraktorakirovetsvkanadu =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        В конце мая АО «Петербургский тракторный завод» (дочернее предприятие
        ОАО «Кировский завод» отгрузил в адрес своего официального дилера в
        Канаде — компании MTZ Equipment LTD два трактора К-744Р4 в комплектации
        «Премиум». За последние четверть века это первые «Кировцы», которые
        отправлены на северо-американский континент. Ранее, в 1980-е годы,
        Кировский завод поставил в Канаду в общей сложности порядка 300
        тракторов серии К-701А. В 2016 году местным аграриям предстоит
        познакомиться с «Кировцами» последнего, 5-го поколения. Отгруженные в
        Канаду модернизированные тракторы К-744Р4 с двигателем Mercedes
        мощностью 428 л.с. имеют максимально широкую комплектацию, которая, в
        частности, включает механизм отбора мощности (МОМ), маятниковое
        прицепное устройство (МПУ), систему позиционного регулирования навесного
        устройства (EHR), комплект сдваивания колес (КСК), а также ряд других
        полезных опций. Современный дизайн, новая кабина с панорамным
        остеклением, обеспечивающая комфорт, ставят нынешний «Кировец» в один
        ряд с машинами лучших западных производителей при весьма привлекательной
        цене. Ориентировочно в конце июня тракторы должны прибыть к месту
        назначения и поступить в распоряжение компании MTZ Equipment LTD. Уже в
        июле, сразу после ввода в эксплуатацию и предварительных испытаний,
        дилер планирует начать серию демонстрационных показов «Кировцев» для
        потенциальных потребителей из числа канадских фермеров и обучение
        сервисных специалистов. С 9 по 12 ноября 2016 года машины К-744Р4 будут
        впервые представлены на выставке Agri-Trade Equipment Expo, которая
        пройдет в канадской провинции Альберта, в городе Ред-Дир. Источник:{" "}
        <a href="http://kzgroup.ru/rus/m/2244/kirowtsy_wozwraschayutsya_w_kanadu.html">
          kzgroup.ru
        </a>
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Петербургский тракторный завод начал поставлять трактора «Кировец» в
            Канаду - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Петербургский тракторный завод начал поставлять трактора «Кировец» в Канаду"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default peterburgskijtraktornyjzavodnachalpostavljattraktorakirovetsvkanadu;
