import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const pledzhsp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Флумиоксазин 500 г/кг</strong>
      Гербицид для борьбы с однолетними двудольными и злаковыми сорняками.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Длительное почвенное действие позволяет контролировать большинство
          сорняков в течение сезона.
        </li>
        <li>Высокая скорость подавления сорняков.</li>
        <li>Нет последействия на последующие культуры в севообороте.</li>
        <li>Разумная цена.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния пре­па­ра­та</strong>
            </td>
            <td>
              <strong>Куль­ту­ра, об­ра­ба­ты­ва­емый объ­ект</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,1-0,12</td>
            <td>Соя, подсолнечник</td>
            <td>Однолетние двудольные и злаковые сорные растения</td>
            <td>
              Опрыскивание почвы до всходов культуры (сразу после посева или в
              течение 2-3 дней после него. В течение 12 месяцев после применения
              препарата не рекомендуется высевать свеклу сахарную, столовую,
              кормовую. Расход рабочей жидкости – 200-300л/га
            </td>
            <td>60(1)</td>
            <td>-(2)</td>
          </tr>
          <tr>
            <td>0,08</td>
            <td>Соя, подсолнечник</td>
            <td>Однолетние двудольные сорные растения</td>
            <td>
              Опрыскивание посевов в фазе 2-4 настоящих листьев культуры. В
              течение 12 месяцев после применения препарата не рекомендуется
              высевать свеклу сахарную, столовую, кормовую. Расход рабочей
              жидкости – 200-300л/га
            </td>
            <td>60(1)</td>
            <td>-(2)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Суми Агро
      <strong>Упаковка: </strong>0,2 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Пледж, СП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Пледж, СП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default pledzhsp;
