import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const polidonaminopljus = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2019/09/2019040965bed7c.png"
          rel="attachment wp-att-3458"
        ></a>
        Гидролизат растительных белков (содержание свободных аминокислот 8-10%),
        бетаины, полисахариды, композиция биополимеров и мембраноактивных
        компонентов.
      </strong>
      Антистрессовый состав с максимально высоким содержанием аминокислот и
      низкомолекулярных пептидов в комплексе с биологически активными
      компонентами. Вносится совместно с пестицидами и растворами минеральных
      удобрений.
      <h2>Состав (вес/объём/%)</h2>
      L-аминокислоты* и олигопептиды** 600 г/л Азот (N общий) 180 г/л *Аланин,
      Аргинин, Аспарагиновая кислота, Аспарагин, Валин, Глутаминовая кислота,
      Глутамин, Глицин, Гистидин, Гидрооксипролин, Пролин, Лейцин, Изолейцин,
      Лизин, Гидрооксилизин, Метионин, Серин, Треонин, Триптофан, Тирозин,
      Дийодтирозин, Фенилаланин, Цистеин **Олигопептиды: ди/три- пептиды
      <h3>Назначение</h3>
      <ul>
        <li>Стимулирует рост корневой системы.</li>
        <li>
          Ускоряет энергию прорастания и повышает полевую всхожесть семян.
        </li>
        <li>Повышает урожайность.</li>
        <li>Активизирует фотосинтез и интенсифицирует обменные процессы.</li>
        <li>Повышает продуктивное кущение.</li>
        <li>Снижает осыпание завязей.</li>
        <li>
          Усиливает стрессоустойчивость к заморозкам, низким/высоким
          температурам, градобою, к химическому и осмотическому стрессам.
        </li>
        <li>Улучшает усвоение элементов питания.</li>
        <li>
          Улучшает приживаемость рассады и саженцев многолетних культур, готовит
          к перезимовке.
        </li>
        <li>Увеличивает коэффициент использования минеральных удобрений.</li>
        <li>Активизирует собственные защитные функции растения.</li>
        <li>Восстанавливает активный рост после природных стрессов.</li>
        <li>Усиливает транспорт агрохимикатов в клетки растения.</li>
        <li>
          Усиливает антибактериальную, противогрибковую, антивирусную
          устойчивости.
        </li>
        <li>Повышает качество продукции.</li>
        <li>Улучшает равномерность размера и окраски плодов.</li>
        <li>
          Увеличивает эффективность гербицидов и средств защиты растений при
          совместном применении.
        </li>
      </ul>
      <h3>Оптимальные дозировки</h3>
      0,2-1,0 л/га, при расходе рабочего раствора 100-300 л.
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/tochka-rosta/">Точка Роста</a>
      <strong>Упаковка: </strong>10 л  
    </div>
  );

  return (
    <>
      <Head>
        <title>ПОЛИДОН® АМИНО ПЛЮС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="ПОЛИДОН® АМИНО ПЛЮС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default polidonaminopljus;
