import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const polidonaminostart = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2019/09/201904109a6e558.png"
          rel="attachment wp-att-3460"
        ></a>
        Гидролизат растительных белков (содержание свободных аминокислот 8-10%),
        бетаины, полисахариды, композиция биополимеров и мембраноактивных
        компонентов
      </strong>
      Специальный состав макро-, мезо- и микроэлементов в комплексе с
      аминокислотами и низкомолекулярными пептидами для начальных этапов
      вегетации Технология применения агрохимиката ПОЛИДОН® Амино Старт
      предусматривает использование типовых технических средств, предназначенных
      для выполнения агрохимических работ. Некорневые подкормки рекомендовано
      проводить с использование штанговых, вентиляторных, ранцевых
      опрыскивателей. В бак опрыскивателя наливают воду до 2/3 объема, при
      включенном перемешивающем устройстве добавляют необходимое количество
      удобрения, доливают воду до расчетного объема, раствор перемешивают и
      проводят подкормки.
      <h2>Состав (вес/объём/%)</h2>
      L-аминокислоты* и олигопептиды** 200 г/л Азот (N общий) 130 г/л Фосфор
      (P2O5) 75 г/л Калий (К2О) 25 г/л Магний (MgO) 15 г/л Железо (Fe) 6 г/л
      Марганец (Mn) 3 г/л Цинк (Zn) 3 г/л Медь (Cu) 3 г/л Бор (B) 3 г/л Молибден
      (Mo) 1 г/л Кобальт (Co) 0.05 г/л *Аланин, Аргинин, Аспарагиновая кислота,
      Аспарагин, Валин, Глутаминовая кислота, Глутамин, Глицин, Гистидин,
      Гидрооксипролин, Пролин, Лейцин, Изолейцин, Лизин, Гидрооксилизин,
      Метионин, Серин, Треонин, Триптофан, Тирозин, Дийодтирозин, Фенилаланин,
      Цистеин **Олигопептиды: ди/три- пептиды Действующие вещества: гидролизат
      растительных белков (содержание свободных аминокислот 8-10%), бетаины,
      полисахариды, композиция биополимеров и мембраноактивных компонентов.
      <h3>Назначение</h3>
      <ul>
        <li>Повышает урожайность.</li>
        <li>
          Усиливает энергию прорастания и повышает полевую всхожесть семян.
        </li>
        <li>Стимулирует рост корневой системы.</li>
        <li>
          Активизирует фотосинтез и интенсифицирует обменные процессы в ранние
          фазы вегетации.
        </li>
        <li>Повышает продуктивное кущение.</li>
        <li>
          Усиливает стрессоустойчивость к заморозкам, низким/высоким
          температурам, градобою, к химическому и осмотическому стрессу.
        </li>
        <li>
          Улучшает приживаемость рассады и саженцев многолетних культур, готовит
          к перезимовке.
        </li>
        <li>Увеличивает коэффициент использования минеральных удобрений.</li>
        <li>Активизирует собственные защитные функции растения.</li>
        <li>Усиливает транспорт агрохимикатов в клетки растения.</li>
        <li>Повышает качество продукции.</li>
      </ul>
      <h3>Оптимальные дозировки</h3>
      0,5-1,0 л/га, при расходе рабочего раствора 100-300 л.
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/tochka-rosta/">Точка Роста</a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>ПОЛИДОН® АМИНО СТАРТ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="ПОЛИДОН® АМИНО СТАРТ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default polidonaminostart;
