import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const polidonaminonpk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2019/09/201904118682255b8ab.png"
          rel="attachment wp-att-3456"
        ></a>
        Специальный антистрессовый состав с высоким содержанием аминокислот и
        низкомолекулярных пептидов в комплексе с азотом и фосфитом калия
      </strong>
      Увеличивает синтез фитоалексинов, тем самым стимулирует защиту от
      патогенов. Применяется на всех сельскохозяйственных культурах в
      критические периоды роста и развития. Вносится совместно с пестицидами и
      растворами минеральных удобрений.
      <h2>Состав (вес/объём/%)</h2>
      L-аминокислоты* и олигопептиды** 250 г/л Фосфор (P2O5) 200 г/л Калий (К2О)
      150 г/л Азот (N общий) 100 г/л *Аланин, Аргинин, Аспарагиновая кислота,
      Аспарагин, Валин, Глутаминовая кислота, Глутамин, Глицин, Гистидин,
      Гидрооксипролин, Пролин, Лейцин, Изолейцин, Лизин, Гидрооксилизин,
      Метионин, Серин, Треонин, Триптофан, Тирозин, Дийодтирозин, Фенилаланин,
      Цистеин **Олигопептиды: ди/три- пептиды Действующие вещества: гидролизат
      растительных белков (содержание свободных аминокислот 8-10%), бетаины,
      полисахариды, композиция биополимеров и мембраноактивных компонентов.
      <h3>Назначение</h3>
      <ul>
        <li>Повышает урожайность.</li>
        <li>Оптимизирует вегетативное развитие культур.</li>
        <li>Усиливает синтез защитных белков.</li>
        <li>Активизирует фотосинтез и интенсифицирует обменные процессы.</li>
        <li>Восстанавливает активный рост после стрессов.</li>
        <li>Увеличивает коэффициент использования минеральных удобрений.</li>
        <li>Усиливает транспорт агрохимикатов в клетки растения.</li>
        <li>Повышает качество продукции.</li>
      </ul>
      <h3>Оптимальные дозировки</h3>
      0,5-1,0 л/га, при расходе рабочего раствора 100-300 л.
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/tochka-rosta/">Точка Роста</a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>ПОЛИДОН® АМИНО NPK - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="ПОЛИДОН® АМИНО NPK"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default polidonaminonpk;
