import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const polidonkompleks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a
          href="https://berkanabio.ru/wp-content/uploads/2019/09/20190524010271f9.png"
          rel="attachment wp-att-3442"
        ></a>
        Сбалансированный состав микроэлементов в хелатной форме
      </strong>
      Применяется на всех сельскохозяйственных культурах в критические периоды
      роста и развития. Вносится совместно с пестицидами и растворами
      минеральных удобрений.
      <h2>Состав (вес/объём/%)</h2>
      Железо (Fe) 45 г/л Марганец (Mn) 25 г/л Медь (Cu) 15 г/л Цинк (Zn) 15 г/л
      Азот (N общий) 5 г/л Бор (B) 5 г/л Молибден (Mo) 5 г/л Кобальт (Co) 0.5
      г/л
      <h3>Преимущества</h3>
      <ul>
        <li>Устраняет дефицит элементов питания.</li>
        <li>Восполняет дефицит микроэлементного питания.</li>
        <li>
          Ускоряет энергию прорастания и повышает полевую всхожесть семян.
        </li>
        <li>Повышает урожайность и качественные показатели.</li>
        <li>Увеличивает рост корневой системы.</li>
        <li>
          Увеличивает коэффициент использования минеральных удобрений из почвы.
        </li>
        <li>Интенсифицирует обменные процессы.</li>
        <li>Повысишает продуктивное кущение и активизирует фотосинтез.</li>
        <li>Активизирует собственные защитные функции растения.</li>
        <li>Восстановливает активный рост после природных стрессов.</li>
        <li>Усиливает транспорт агрохимикатов в клетки растения.</li>
        <li>Увеличивает азотофиксирующую активность клубеньковых бактерий.</li>
        <li>Усиливает цветение, оплодотворение и формирование завязей.</li>
        <li>Увеличивает плодообразование.</li>
        <li>Усиливает синтез хлорофилла.</li>
        <li>Повышает стрессоустойчивость.</li>
        <li>Увеличивает количество углеводов.</li>
        <li>
          Увеличивает коэффициент использования вносимых минеральных удобрений.
        </li>
      </ul>
      <h3>Оптимальные дозировки:</h3>
      0,3-0,5 л/га, при расходе рабочего раствора 100-300 л.
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/tochka-rosta/">Точка Роста</a>
      <strong>Упаковка: </strong>10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>ПОЛИДОН® КОМПЛЕКС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="ПОЛИДОН® КОМПЛЕКС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default polidonkompleks;
