import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const prestizhks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/03/berkanabio-prestizh-ks.jpg"></a>
        <a href="https://berkanabio.ru/category/imidakloprid/">Имидаклоприд</a>{" "}
        140 г/л +{" "}
        <a href="https://berkanabio.ru/category/pencikuron/">Пенцикурон</a> 150
        г/л
      </strong>
      Инсекто-фунгицидный протравитель для обработки клубней картофеля против
      грызущих и сосущих вредителей (в т.ч. почвообитающих), а также некоторых
      болезней.
      <h2>Преимущества</h2>
      <ul>
        <li>Высокая технологичность обработки.</li>
        <li>
          Снижение трудоёмкости выращивания картофеля: одна операция равна двум
          обработкам (от вредителей и болезней).
        </li>
        <li>
          Антистрессовый эффект: повышение устойчивости картофеля к биотическим
          и абиотическим воздействиям окружающей среды и, как следствие,
          увеличение всхожести, улучшение побегообразования и роста вегетативной
          массы, усиление фотосинтетических процессов.
        </li>
        <li>Улучшение качества продукции.</li>
        <li>Низкая токсичность (III класс).</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния пре­па­ра­та</strong>
            </td>
            <td>
              <strong>Куль­ту­ра, об­ра­ба­ты­ва­емый объ­ект</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,7-1</td>
            <td>Картофель</td>
            <td>
              Проволочники, колорадский жук, тли - переносчики вирусов,
              ризоктониоз, парша обыкновенная
            </td>
            <td>
              Обработка клубней до или во время посадки. Расход рабочей жидкости
              - 10 л/т
            </td>
          </tr>
          <tr>
            <td>0,7-1</td>
            <td>Картофель</td>
            <td>Ризоктониоз, парша обыкновенная</td>
            <td>
              Обработка клубней до или во время посадки. Расход рабочей жидкости
              - 10 л/т
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/bajer/">Байер</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Престиж, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Престиж, КС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default prestizhks;
