import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const rekssks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/06/reks-s-ks.jpg"></a>
        <a href="https://berkanabio.ru/category/epoksikonazol/">
          Эпоксиконазол
        </a>{" "}
        125 г/л
      </strong>
      Системный фунгицид для защиты зерновых культур.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Эффективен против септориозов, ржавчины и других заболеваний зерновых
          культур;
        </li>
        <li>
          Быстро проникает в растение (30 мин.) и останавливает развитие
          инфекции – «стоп-эффект»;
        </li>
        <li>Обладает профилактическим и лечебным свойствами;</li>
        <li>Эффективная защита от патогенов при оптимальных затратах;</li>
      </ul>
      <h3>Норма расхода</h3>
      <div class="table_content_wrap">
        <table class="main_content">
          <tbody>
            <tr>
              <td>
                <strong>Нор­ма</strong>
              </td>
              <td>
                <strong>Куль­ту­ра</strong>
              </td>
              <td>
                <strong>Вред­ный объ­ект</strong>
              </td>
              <td>
                <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
              </td>
            </tr>
            <tr class="uneven">
              <td class="width_12_prc t_a_center_f_s_11">
                <span>0,6-0,8</span>
              </td>
              <td class="width_20_prc left_border left_border">
                <span>Пшеница озимая и яровая</span>
              </td>
              <td class="width_19_prc left_border left_border">
                <span>
                  Мучнистая роса, ржавчина бурая, стеблевая, септориоз, желтая
                  пятнистость (пиренофороз), темно-бурая пятнистость, комплекс
                  пятнистостей колоса: септориоз, фузариоз, оливковая плесень
                </span>
              </td>
              <td class="width_27_prc left_border left_border">
                <span>
                  Опрыскивание в период вегетации в зависимости от времени
                  появления первых признаков одного из заболеваний или
                  заблаговременно (профилактическое опрыскивание).
                </span>
                <span>Расход рабочей жидкости - 300 л/га.</span>
              </td>
            </tr>
            <tr class="even" id="finish_row">
              <td class="width_12_prc t_a_center_f_s_11">
                <span>0,6-0,8</span>
              </td>
              <td class="width_20_prc left_border left_border">
                <span>Ячмень яровой</span>
              </td>
              <td class="width_19_prc left_border left_border">
                <span>
                  Мучнистая роса, ржавчина карликовая, стеблевая, темно-бурая
                  пятнистость, сетчатая пятнистость, желтая пятнистость
                  (пиренофороз), комплекс пятнистостей колоса: септориоз,
                  фузариоз, оливковая плесень
                </span>
              </td>
              <td class="width_27_prc left_border left_border">
                <span>
                  Опрыскивание в период вегетации в зависимости от времени
                  появления первых признаков одного из заболеваний или
                  заблаговременно (профилактическое опрыскивание).
                </span>
                <span>Расход рабочей жидкости - 300 л/га.</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/basf/">БАСФ</a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Рекс С, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Рекс С, КС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default rekssks;
