import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const rekspljusse = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/06/reks-pljus-se.jpg"></a>
        <a href="https://berkanabio.ru/category/fenpropimorf/">Фенпропиморф</a>{" "}
        250 г/л +{" "}
        <a href="https://berkanabio.ru/category/epoksikonazol/">
          Эпоксиконазол
        </a>{" "}
        84 г/л
      </strong>
      Фунгицид для защиты зерновых культур на основе эпоксиконазола и
      фенпропиморфа с усиленной препаративной формой.
      <h2>Преимущество</h2>
      <ul>
        <li>Улучшенная препаративная форма;</li>
        <li>Отличные защитное и лечебное действия;</li>
        <li>Широкий спектр действия;</li>
        <li>Гибкость применения;</li>
      </ul>
      <h3>Норма расхода</h3>
      <div class="table_content_wrap">
        <table class="main_content">
          <tbody>
            <tr>
              <td>
                <strong>Нор­ма</strong>
              </td>
              <td>
                <strong>Куль­ту­ра</strong>
              </td>
              <td>
                <strong>Вред­ный объ­ект</strong>
              </td>
              <td>
                <strong>Спо­соб и ре­мя об­ра­бот­ки</strong>
              </td>
            </tr>
            <tr class="uneven">
              <td class="width_12_prc t_a_center_f_s_11">
                <span>0,8-1</span>
              </td>
              <td class="width_20_prc left_border left_border">
                <span>Пшеница яровая и озимая</span>
              </td>
              <td class="width_19_prc left_border left_border">
                <span>
                  Мучнистая роса, бурая ржавчина, стеблевая ржавчина,  желтая
                  ржавчина, пиренофороз, септориоз листьев и колоса
                </span>
              </td>
              <td class="width_27_prc left_border left_border">
                <span>
                  Опрыскивание в период вегетации профилактически или при
                  появлении первых признаков одного из заболеваний.
                </span>
                <span>Расход рабочей жидкости – 300 л/га</span>
              </td>
            </tr>
            <tr class="even" id="finish_row">
              <td class="width_12_prc t_a_center_f_s_11">
                <span>0,8-1</span>
              </td>
              <td class="width_20_prc left_border left_border">
                <span>Ячмень яровой и озимый</span>
              </td>
              <td class="width_19_prc left_border left_border">
                <span>
                  Мучнистая роса, карликовая ржавчина, стеблевая ржавчина,
                  сетчатая пятнистость, темно-бурая пятнистость, ринхоспороз
                </span>
              </td>
              <td class="width_27_prc left_border left_border">
                <span>
                  Опрыскивание в период вегетации профилактически или при
                  появлении первых признаков одного из заболеваний.
                </span>
                <span>Расход рабочей жидкости – 300 л/га</span>
              </td>
            </tr>
          </tbody>
        </table>
        <strong>Производитель:</strong>{" "}
        <a href="https://berkanabio.ru/category/basf/">БАСФ</a>
        <strong>Упаковка:</strong> 10 л
      </div>
    </div>
  );

  return (
    <>
      <Head>
        <title>Рекс Плюс, СЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Рекс Плюс, СЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default rekspljusse;
