import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const respekta = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/534534akua.png"></a>
        Биологический протравитель семян. Живые клетки бактерии Pseudomonas
        aureofaciens и продукты их метаболизма.
      </strong>
      Предназначен для контроля грибной и бактериальной инфекции на семенах, а
      также последующих этапах развития и роста растений.
      <h2>Преимущества</h2>
      <ul>
        <li>Повышает всхожесть и энергию прорастания семян;</li>
        <li>Оптимизирует рост и развитие корневой системы;</li>
        <li>
          Обеспечивает защиту растений на ранних этапах развития от комплекса
          патогенов;
        </li>
        <li>
          Длительный период защитного действия за счёт колонизации ризосферы;
        </li>
        <li>Укрепляет иммунный статус культуры;</li>
        <li>Переводит фосфор в доступную для растений форму;</li>
        <li>Совместим с инокулянтами, не угнетает клубеньковые бактерии.</li>
      </ul>
      <h3>Механизм действия</h3>
      Бактерии Pseudomonas aureofaciens продуцируют широкий спектр
      антибиотических метаболитов, конкурируют за субстрат с фитопатогенными
      микроорганизмами, синтезируют фитогормоны, стимулирующие рост и развитие
      растений, и индуцирующие иммунитет, а также сидерофоры, связывающие
      трёхвалентное железо и ограничивающие рост фитопатогенов.
      <h2>Норма расхода</h2>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      <strong>Упаковка:</strong> 2 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Респекта® - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Респекта®" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default respekta;
