import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const respekta25 = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/345k34kuca.png"></a>
        Биофунгицид для обработки в период вегетации. Живые клетки бактерии
        Pseudomonas aureofaciens и продукты метаболизма.
      </strong>
      Предназначен для контроля грибной и бактериальной инфекции период
      вегетации, а также для снятия стресса, вызванного применением пестицидов
      или неблагоприятными условиями окружающей среды.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Высокая антагонистическая активность против широкого спектра
          возбудителей болезней растений;
        </li>
        <li>
          Эффективен как при профилактическом, так и при лечебном применении;
        </li>
        <li>Стимулирует рост и развитие растений;</li>
        <li>Укрепляет иммунный статус культуры;</li>
        <li>Не вызывает резистентности патогенов;</li>
        <li>Улучшает фосфорное питание растений;</li>
        <li>Повышает урожайность и качество урожая;</li>
        <li>
          Не имеет сроков ожидания, возможно применение в любую фазу развития
          культуры;
        </li>
        <li>
          Не теряет своей эффективности в широком диапазоне температур от +5 до
          39°С;
        </li>
        <li>Совместим с инокулянтами, не угнетает клубеньковые бактерии;</li>
        <li>
          Возможно применение в баковых смесях с химическими средствами защиты
          растений.
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Бактерии Pseudomonas aureofaciens продуцируют широкий спектр
      антибиотических метаболитов, конкурируют за субстрат с фитопатогенными
      микроорганизмами, синтезируют фитогормоны, стимулирующие рост и развитие
      растений и индуцирующие иммунитет, а также сидерофоры, связывающие
      трёхвалентное железо и ограничивающие рост фитопатогенов.
      <h2>Норма расхода</h2>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      <strong>Упаковка:</strong> 5 л, 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Респекта® 25% - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Респекта® 25%" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default respekta25;
