import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const rizomaks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/345435.jpg"></a>
        Микоризный препарат увеличивающий всасывающую поверхность корневой
        системы. Споровомицелиальный комплекс микоризного гриба Glomus spp.
      </strong>
      Предназначен для стимуляции роста корневой системы, улучшения возможностей
      водного обмена и минерального питания растений, повышения устойчивости к
      неблагоприятным факторам внешней среды (антистрессант), почвенным
      патогенам и нематодам.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Быстрое (в течение 3-5 дней после обработки) образование
          симбиотических связей с растением;
        </li>
        <li>Способствует быстрому росту и развитию корневой системы;</li>
        <li>Снимает стресс после пикировки и пересадки;</li>
        <li>
          Позволяет эффективно использовать имеющуюся в грунте влагу и
          увеличивает устойчивость к краткосрочным неблагоприятным факторам
          внешней среды;
        </li>
        <li>
          Способствует максимальному использованию элементов почвенных питания
          (макро- и микро-) и внесённых минеральных удобрений;
        </li>
        <li>
          Повышает устойчивость растения к патогенам и нематодам, находящимся в
          почве;
        </li>
        <li>
          Улучшает качественные показатели сельскохозяйственной продукции.
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Микоризный гриб образует симбиотические связи с растением, увеличивает
      площадь и массу корневой системы, а так же улучшает поглощающую
      способность и усвояемость элементов питания из неподвижной части гумуса. В
      результате симбиоза растение обеспечивает микоризу доступными углеводами,
      а микориза – увеличивает доступность влаги, способствует лучшему усвоению
      макро и микроэлементов.
      <h2>Норма расхода</h2>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-biona/">ООО «Биона»</a>
      <strong>Упаковка:</strong> 1 л, 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Ризомакс® - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Ризомакс®" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default rizomaks;
