import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const rizobashzh = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Универсальный инокулянт для бобовых культур</strong>
      Высокоэффективный универсальный ино
      <a href="https://berkanabio.ru/wp-content/uploads/2019/09/rizobash_soya.png"></a>
      кулянт основных бобовых сельско-хозяйственных культур: соя, нут, горох,
      чечевица, козлятник – для фиксации атмосферного азота с
      ростостимулирующими свойствами.
      <h2>Состав</h2>
      <ul>
        <li>
          Жизнеспособные клетки клубеньковых бактерий Bradyrhizobium japonicum,
          Mesorhizobium (Rhizobium) ciceri,
        </li>
        <li>
          Rhizobium galegae, Rhizobium leguminosarum (не менее 1×109 КОЕ/мл);
        </li>
        <li>Витамины, фитогормоны, полисахариды и т. д.;</li>
        <li>Стабилизатор-антиоксидант.</li>
      </ul>
      <h3>Механизм действия</h3>
      Фиксация атмосферного азота (в условиях симбиоза с бобовыми культурами) и
      превращение его в форму, доступную для усвоения бобовыми растениями.
      Синтез ростостимулирующих веществ (витаминов, фитогормонов ауксинов,
      гиббереллинов и т. д.).
      <h2>Преимущества</h2>
      <ul>
        <li>Высокая концентрация азотфиксирующих клубеньковых бактерий;</li>
        <li>
          Жидкая форма инокулянта и инновационный прилипатель позволяют надежно
          закрепиться на поверхности семян;
        </li>
        <li>Заменяет 50-70 кг д.в. и выше азотных удобрений;</li>
        <li>Повышает урожайность зернобобовых культур на 15-20 %;</li>
        <li>Увеличивает содержание протеина в урожае бобовых культур;</li>
        <li>
          Улучшает пищевой режим почвы и активизирует почвенную микрофлору;
        </li>
        <li>
          Имеет эффект последействия – увеличение урожайности последующей
          культуры севооборота;
        </li>
        <li>
          Гарантия экологически чистой, безопасной для здоровья продукции.
        </li>
      </ul>
      <h3>Норма расхода</h3>
      2-3 л/т
      <strong>Производитель:</strong> 
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО «НВП БашИнком»
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>РизоБаш® - Ж - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="РизоБаш® - Ж" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default rizobashzh;
