import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const rossijamirovojliderpoproizvodstvupshenitsy = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="http://berkanabio.ru/wp-content/uploads/2018/02/zher.jpg"></a>
      Согласно прогнозу Международного совета по зерну (IGC), в 2017/18 МГ
      Россия, скорее всего, займет первое место в мире по производству пшеницы и
      второе по производству зерновых в целом По данным таможенной службы
      России, до 7 февраля 2018 года государство экспортировало 31,4 млн т
      зерна. Это на 36 % больше, чем за тот же период прошлого сезона, когда
      экспорт составил 23,074 млн т. Экспорт пшеницы с начала сезона 2017/18
      составил более 24,5 млн т, или 37 % больше, чем за тот же период сезона
      2016/17 (17,9 млн т). Экспорт ячменя составил 3,9 млн т, что в 1,9 раза
      больше, чем за тот же период в 2016 году. Около 2,82 млн т кукурузы было
      экспортировано. Это единственный «просевший» сектор - на 6% меньше, чем за
      тот же период прошлого сезона (около 3 млн т). Экспорт других зерновых
      увеличился на 51 %, до 220 тыс. т (по сравнению с 146 тыс. т за тот же
      период предыдущего сезона). (Источники:
      <a href="http://www.farmer.pl"> farmer.pl</a>,{" "}
      <a href="http://www.agroxxi.ru">agroxxi.ru</a>)<span id="ctrlcopy"></span>
    </div>
  );

  return (
    <>
      <Head>
        <title>Россия - мировой лидер по производству пшеницы - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Россия - мировой лидер по производству пшеницы"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default rossijamirovojliderpoproizvodstvupshenitsy;
