import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const shirlansk = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/06/berkanabio-shirlan-sk.jpg"></a>
        <a href="https://berkanabio.ru/category/fluazinam/">Флуазинам</a> 500
        г/л
      </strong>
      Уникальный контактный фунгицид профилактического действия для защиты
      картофеля от фитофтороза.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Сокращает до минимума риск раннего проявления фитофтороза в поле в
          условиях, благоприятных для развития болезни;
        </li>
        <li>Сохраняет растения здоровыми в период всходов;</li>
        <li>
          Обеспечивает получение неповрежденных фитофторозом клубней в период
          уборки и во время хранения при условии своевременного применения;
        </li>
        <li>
          Способствует снижению возможного заражения клубней вторичной инфекцией
          из-за поражения фитофторозом (бактериальными, сухими гнилями и
          смешанными гнилями);
        </li>
        <li>
          Гарантирует стабильную защиту картофеля в условиях полива и выпадения
          осадков;
        </li>
      </ul>
      <h3>Норма расхода</h3>
      <div class="table_content_wrap">
        <table class="main_content">
          <tbody>
            <tr>
              <td>
                <strong>Нор­ма</strong>
              </td>
              <td>
                <strong>Куль­ту­ра</strong>
              </td>
              <td>
                <strong>Вред­ный объ­ект</strong>
              </td>
              <td>
                <strong>Спо­соб, вре­мя об­ра­бот­ки</strong>
              </td>
            </tr>
            <tr class="uneven" id="finish_row">
              <td class="width_12_prc t_a_center_f_s_11">0,3-0,4</td>
              <td class="width_20_prc left_border left_border">Картофель</td>
              <td class="width_19_prc left_border left_border">
                Фитофтороз, альтернариоз
              </td>
              <td class="width_27_prc left_border left_border">
                Опрыскивание в период вегетации: первое - в фазе смыкания
                рядков, последующие - с интервалом 7-10 дней. Расход рабочей
                жидкости - 200-500 л/га.
              </td>
            </tr>
          </tbody>
        </table>
        <div></div>
        <div class="table_content_wrap">
          <strong>Производитель:</strong>{" "}
          <a href="https://berkanabio.ru/category/singenta/">Syngenta</a>
        </div>
        <strong>Упаковка:</strong> 5 л
      </div>
    </div>
  );

  return (
    <>
      <Head>
        <title>Ширлан, СК - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Ширлан, СК" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default shirlansk;
