import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sichester = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Раннеспелый высокомасличный гибрид для классической технологии с
      максимальной генетической заразихоустойчивостью (G+) Тип гибрида:
      Заразихоустойчивый Группа спелости:  Раннеcпелый Назначение: Линолевый
      Масличность: 53-55% Высота растений: 150-170 см (в зависимости от
      влагообеспеченности) Устойчивость к расам заразихи: A-G+ Технология
      возделывания: Классическая
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущества</strong>
            </td>
            <td>
              <strong>Рекомендации по технологии</strong>
            </td>
          </tr>
          <tr>
            <td>
              Максимальная устойчивость к заразихе в портфеле Сингенты. Очень
              быстрый старт на начальных этапах развития растения. Раннее
              цветение позволяет избежать стресса высоких температур.
              Масличность до 55%! В условиях ограниченного потенциала высокая
              масличность становится одним из немногих параметров, которые
              позволяют увеличить доходность с гектара производства
              подсолнечника. Ранняя группа спелости гарантирует своевременную
              уборку при стандартной влажности.
              <h3></h3>
            </td>
            <td>
              Пластичен к срокам сева. Стабильный результат даже в условиях
              бедных почв, пригоден для малозатратного земледелия. Избегать
              ситуации разреженного посева или существенной потери густоты;
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ ЧЕСТЕР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ ЧЕСТЕР" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sichester;
