import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const siedison = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Среднепоздний заразихоустойчивый гибрид с максимальным потенциалом
      урожайности. Рекордсмен урожайности и масличности на рынке. Тип гибрида:
      Заразихоустойчивый Группа спелости: Среднепоздний Назначение: Линолевый
      Масличность: 52-54% Высота растений: 160-180 см (в зависимости от
      влагообеспеченности) Устойчивость к расам заразихи: A–F Технология
      возделывания: Классическая
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Преимущество</strong>
            </td>
            <td>
              <strong>Рекомендации по технологии</strong>
            </td>
          </tr>
          <tr>
            <td>
              Высокогофрированные листья - увеличенная эффективная площадь
              листового аппарата. Индекс опыленности корзинки - один из самых
              высоких на рынке. Максимальная масличность в своем сегменте.
              Отлично переносит стресс недостатка влаги.
            </td>
            <td>
              Сеять в оптимальные сроки. Для максимальной реализации потенциала
              - применять интенсивную технологию. Рекомендуется использование
              десеканта при позднем севе.
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ ЭДИСОН - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ ЭДИСОН" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default siedison;
