import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sifenomen = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>SYNGENTA</strong>
      Феноменальная комбинация урожайности и влагоотдачи. Очень быстрая
      влагоотдача в предуборочный период. Отличная засухо- и жаростойкость за
      счет эффективного использования влаги. Устойчив к прикорневому
      полеганию.Феноменальная комбинация урожайности и влагоотдачи. Назначение
      Кукурузы: зерно, корнаж, силос ФАО: 220 Тип зерна: зубовидный Потенциал
      урожайности зерна – 10 Засухоустойчивость – 10 Скорость раннего развития –
      10 Холодостойкость – 9 Скорость влагоотдачи – 10 Устойчивость к полеганию
      – 10
      <table>
        <tbody>
          <tr>
            <td>Другие характеристики</td>
            <td>Толерантность к болезням</td>
          </tr>
          <tr>
            <td>
              Крупный многорядный початок. Тонкий стержень. Быстрое развитие
              корневой системы.
            </td>
            <td>Фузариоз початка. Пузырчатая головня. Стеблевые гнили.</td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ ФЕНОМЕН - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ ФЕНОМЕН" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sifenomen;
