import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sijunitop = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>SYNGENTA</strong>
      Стабильно высокая переваримость. Гибрид промежуточного типа интенсивности
      с широким ареалом адаптации. Более высокая энергетическая ценность силоса,
      достигаемая за счет повышенной переваримости клетчатки. Быстро развивается
      на ранних этапах вегетации, пригоден для раннего сева. Тип зерна:
      кремнисто-зубовидный. Назначение Кукурузы: силос, корнаж ФАО: 240 Тип
      зерна: кремнисто-зубовидный Урожайность зеленой массы - 9 Выход усвояемой
      энергии - 9 Переваримость клетчатки - 10 Засухоустойчивость - 9 Раннее
      развитие - 10 Холодостойкость - 10 Устойчивость к полеганию - 9
      <table>
        <tbody>
          <tr>
            <td>Другие характеристики</td>
            <td>Толерантность к болезням</td>
          </tr>
          <tr>
            <td>
              Адаптирован к различным агротехнологиям. Пригоден для выращивания
              на различных типах почв.
            </td>
            <td>Фузариоз початка, Стеблевые гнили, Гельминтоспориоз.</td>
          </tr>
        </tbody>
      </table>
         
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ ЮНИТОП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ ЮНИТОП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sijunitop;
