import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sikarioka = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>SYNGENTA</strong>
      Карнавал урожайности. Высокоинтенсивный гибрид для достижения максимальной
      урожайности на орошении. Хорошая толерантность к фузариозу и стеблевым
      гнилям даже на высоком патогенном фоне. Зерно имеет более высокую натуру
      по сравнению со стандартами. Назначение Кукурузы: зерно, силос, корнаж,
      спирт ФАО: 430 Тип зерна: зубовидный Потенциал урожайности зерна – 10
      Засухоустойчивость – 8 Скорость раннего развития – 10 Холодостойкость – 9
      Скорость влагоотдачи – 9 Устойчивость к полеганию – 9
      <table>
        <tbody>
          <tr>
            <td>Другие характеристики</td>
            <td>Толерантность к болезням</td>
          </tr>
          <tr>
            <td>
              Быстро развивается на ранних этапах вегетации. Отличная
              отзывчивость на высокий фон минерального питания. Растение типа
              Stay Green
            </td>
            <td>Фузариоз початка Стеблевые гнили</td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ КАРИОКА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ КАРИОКА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sikarioka;
