import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const silvet408r = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/3452316.38.png"></a>
        100% органо-силикон
      </strong>
      Органосиликоновый супер-смачиватель нового поколения для повышения
      эффективности и стабильности средств защиты растений и удобрений.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Благодаря инновационной формуле снижает норму расхода препарата на 20%
          по сравнению с Сильвет® Голд, а также снижает объём расхода рабочей
          жидкости на 20 – 50%
        </li>
        <li>
          Обеспечивает высокую и стабильную эффективность средств защиты
          растений и удобрений благодаря значительному увеличению площади
          покрытия и проникновению в труднодоступные части растений
        </li>
        <li>Повышает устойчивость к смыванию препарата осадками</li>
      </ul>
      <h2>Норма расхода</h2>
      15 мл/100 л воды до 180 мл/100л воды
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/arista-lajfsajens/">Ариста</a>
      <strong>Упаковка:</strong> 1 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Сильвет 408, Р - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Сильвет 408, Р"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default silvet408r;
