import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const siozon = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2022/03/855685.png"></a>
        SYNGENTA
      </strong>
      Всё просто – бери и сей. Высокая адаптивность к различным
      почвенно-климатическим условиям и технологиям возделывания. Стабильность в
      условиях лимитированной урожайности. Отличная толерантность к основным
      патогенам початка, листьев и стебля. Назначение Кукурузы: зерно, силос,
      корнаж, спирт ФАО: 300 Тип зерна: Зубовидный Потенциал урожайности зерна –
      9 Засухоустойчивость – 9 Скорость раннего развития – 8 Холодостойкость – 9
      Скорость влагоотдачи – 9 Устойчивость к полеганию – 10
      <table>
        <tbody>
          <tr>
            <td>Другие характеристики</td>
            <td>Толерантность к болезням</td>
          </tr>
          <tr>
            <td>
              Зерно быстро отдает влагу при созревании. Высокая натура зерна.
              Отличная устойчивость к полеганию
            </td>
            <td>
              фузариоз початка стеблевые гнили гельминтоспориоз пузырчатая
              головня.
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ ОЗОН - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ ОЗОН" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default siozon;
