import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sirozetaklp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Среднеранний заразихоустойчивый Clearfield® Plus гибрид с великолепной
      жаро- и засухоустойчивостью. Жаростойскость. Надежность. Двойная защита от
      заразихи. Тип гибрида: для производственной системы Clearfield® Plus
      Группа спелости: среднеранний Назначение: линолевый Масличность: 50-53%
      Высота растений: 150-170 см (в зависимости от влагообеспеченности)
      Устойчивость к расам заразихи: A–G Технология возделывания:
      производственная система Clearfield® Plus
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Полный контроль заразихи за счет гербицидного и генетического
              механизма борьбы с растением-паразитом, в т.ч. от вторичного
              заражения. Отличная, ярко выраженная жаро/засухоустойчивость.
              Очень быстрый старт на начальных этапах развития растения. Раннее
              цветение дает возможность опыления корзинки раньше сезонных
              неблагоприятных условий. Высокая масличность: до 51%.
            </td>
            <td>
              Рекомендации по технологии Пластичен к срокам сева.Стабильный
              результат даже в условиях бедных почв, пригоден для малозатратного
              земледелия. Избегать загущения посевов. Не рекомендуется для
              возделывания в регионах с избыточным влагообеспечением.
            </td>
          </tr>
        </tbody>
      </table>
         
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ РОЗЕТА КЛП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ РОЗЕТА КЛП" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sirozetaklp;
