import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sistemytochnogozemledelijaobsudjatvskolkovo = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        Развитие систем точного земледелия, разработку правил для используемых в
        АПК беспилотных летательных аппаратов и другие темы обсудят на
        конференции «Точное земледелие 2018». Мероприятие пройдет 20 февраля в
        Технопарке «Сколково» при поддержке Министерства сельского
        хозяйства, KPMG
      </strong>
      <a href="http://berkanabio.ru/wp-content/uploads/2018/02/article79332.jpg"></a>
      В конференции примут участие представители Фонда «Сколково», Министерства
      сельского хозяйства РФ, Национального исследовательского университета
      «Высшая школа экономики». Среди гостей мероприятия крупные
      агропромышленные компании: Агрохолдинг «Кубань», «Зеленая долина»,
      «Агрофирма «Рубеж», ГК Агротерра. К дискуссиям присоединятся сотрудники
      одного из ведущих производителей минеральных удобрений в России, СНГ и
      Восточной Европе «ОХК «Уралхим», разработчика средств для защиты растений
      из Швейцарии «Сингента», а также телекоммуникационной компании «МТС». В
      рамках мероприятия будет организована выставка, где свои инновационные
      решения в сфере биомедицинских, а также передовых промышленных технологий
      продемонстрируют компании-резиденты Фонда «Сколково»: НТЦ «РобоПРОБ»,
      «Агроноут», «Точное землепользование», «СКАН» и другие стартапы.
      Представители отрасли АПК обсудят необходимость выделения субсидий для
      компаний, внедряющих системы точного земледелия; уточнение требований к
      качеству спутниковых снимков и каналам передачи данных; правила работы с
      беспилотными летательными аппаратами. Кроме того, участники выделят
      ключевые технологические тренды и изучат примеры успешного внедрения
      передовых IT-технологий. Конференция «Точное земледелие» пройдет в третий
      раз. За два года в мероприятии приняли участие более 700 специалистов
      отрасли, состоялись выступления более 80 ведущих российских и зарубежных
      экспертов. Конференция показала, что уже сегодня в России существуют
      примеры успешной разработки и внедрения технологий точного земледелия.
      (Источник: пресс-служба Фонда «Сколково»).<span id="ctrlcopy"></span> 
    </div>
  );

  return (
    <>
      <Head>
        <title>Системы точного земледелия обсудят в «СКОЛКОВО» - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Системы точного земледелия обсудят в «СКОЛКОВО»"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sistemytochnogozemledelijaobsudjatvskolkovo;
