import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sitelias = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>SYNGENTA</strong>
      Рентабельность в любых условиях. Высокая адаптивность к различным
      климатическим условиям. Пригоден для сроков сева от самых ранних до
      поздних. Хорошая отзывчивость на интенсивные условия выращивания.
      Назначение Кукурузы: зерно, силос, крупа, корнаж, спирт ФАО: 210 Тип
      зерна: кремнисто-зубовидный Потенциал урожайности зерна – 10
      Засухоустойчивость – 9 Скорость раннего развития –9 Холодостойкость – 9
      Скорость влагоотдачи – 9 Устойчивость к полеганию – 9
      <table>
        <tbody>
          <tr>
            <td>Преимущества</td>
            <td>Толерантность к болезням</td>
          </tr>
          <tr>
            <td>
              Быстрый старт и раннее развитие. Высокая стрессоустойчивость.
            </td>
            <td>фузариоз початка гельминтоспориоз</td>
          </tr>
        </tbody>
      </table>
    </div>
  );

  return (
    <>
      <Head>
        <title>СИ ТЕЛИАС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СИ ТЕЛИАС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sitelias;
