import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const skorpionvr = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/08/berkanabio_skorpion-vr.jpg"></a>
        <a href="https://berkanabio.ru/category/dikvat/">Дикват</a> 150 г/л
      </strong>
      Десикант контактного действия. Применяется для снижения влажности зерна и
      прекращения развития и распространения заболеваний подсолнечника за счет
      подсушивания растений перед уборкой. Препарат применяется для десикации
      сельскохозяйственных культур.
      <h2>Преимущества</h2>
      <ul>
        <li>проводить уборку прямым комбайнированием;</li>
        <li>проводить уборку урожая в более сжатые сроки;</li>
        <li>
          снизить влажность семян и засоренность продукции, что уменьшает
          затраты на дополнительные сушку и очистку;
        </li>
        <li>остановить развитие заболеваний, особенно в дождливую погоду;</li>
      </ul>
      <h3>Механизм действия</h3>
      Препарат контактного действия. Действующее вещество препарата
      адсорбируется живыми клетками растения, включается в процессы метаболизма
      растения и образует соединения, которые разрушают мембраны клеток
      растения. В результате этого клетки погибают и происходит подсушивание
      растения.
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>2</span>
            </td>
            <td>
              <span>Подсолнечник</span>
            </td>
            <td>
              <span>Десикация</span>
            </td>
            <td>
              <span>Опрыскивание в начале побурения корзинок.</span>
              <span>
                Расход рабочей жидкости -200-300 л/га, при авиа-обработке -
                50-100 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>2(А)</span>
            </td>
            <td>
              <span>Подсолнечник</span>
            </td>
            <td>
              <span>Десикация</span>
            </td>
            <td>
              <span>Опрыскивание в начале побурения корзинок.</span>
              <span>
                Расход рабочей жидкости -200-300 л/га, при авиа-обработке -
                50-100 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>1</span>
            </td>
            <td>
              <span>Подсолнечник</span>
            </td>
            <td>
              <span>Десикация</span>
            </td>
            <td>
              <span>
                Опрыскивание в начале побурения корзинок в смеси с мочевиной (30
                кг/га).
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/neoport/">Neoport</a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Скорпион, ВР - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Скорпион, ВР" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default skorpionvr;
