import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sternja = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/wp-content/uploads/2019/09/9939.png"></a>
      Микробиологический препарат для разложения растительных остатков и
      оздоровления почвы.
      <h2>Состав</h2>
      <ul>
        <li>
          Консорциум грибов и бактерий, в составе 4 штамма спорообразующих
          бактерий Bacillus subtilis
        </li>
        <li>3 штамма гриба Trihoderma</li>
        <li>Фосфатомобилизующие</li>
        <li>Азотфиксирующие бактерии</li>
        <li>Комплекс целлюлозолитических ферментов</li>
      </ul>
      <h3>Механизм действия</h3>
      <ul>
        <li>развивает полезную микрофлору;</li>
        <li>оздоравливает почву;</li>
        <li>ускоряет разложение растительных остатков;</li>
        <li>повышает плодородие почвы;</li>
        <li>улучшает минеральное питание растений;</li>
        <li>очищает почву от микробных токсинов;</li>
        <li>нейтрализует остатки химических пестицидов;</li>
        <li>повышает продуктивность с/х культур на 10-20%.</li>
      </ul>
      Совместим с микробиологическими средствами защиты растений, регуляторами
      роста, удобрениями, химическими гербицидами и инсектицидами.
      <h3>Норма расхода</h3>
      1,0-1,5 л/га Расход рабочего раствора - 100-300 л/га.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/ooo-nvp-bashinkom/">
        ООО “НВП БашИнком”
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Стерня - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Стерня" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sternja;
