import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const stimiksprofi = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/wp-content/uploads/2019/09/stimiks-profi.jpeg"></a>
      Борьба с болезнями бактериальной и смешанной бактериально-грибной природы
      зерновых культур.
      <h2>Назначение</h2>
      Повышение урожайности и устойчивости к стрессам (жара, заморозки, засуха и
      т.п. ). Снятие эффекта "гербицидной ямы". Повышение качества зерна.
      Стимулирование процессов развития растения. Применяется на озимых
      культурах в осенний период, а также на других культурах, в те периоды их
      развития, когда интенсивный рост нежелателен.
      <h3>Действие препарата</h3>
      Устраняет блокаду белкового синтеза, остановленного токсинами возбудителей
      базального бактериоза. Инактивирует токсины. Усиливает фотосинтез.
      Практически не оказывает ростостимулирующего действия на растение, но
      сохраняет выраженный эффект стимуляции его развития.
      <h2>Состав препарата</h2>
      <ul>
        <li>Свободные аминокислоты - не менее 30 г/л</li>
        <li>Соли гуминовых кислот - 40-45 г/л</li>
        <li>Живые микробные культуры</li>
        <li>Органический кремний</li>
        <li>Биологически активные вещества</li>
      </ul>
      <h3>Применение</h3>
      Вид обработки: некорневая подкормка, полив под корень Расход препарата:
      0,5 л/га Объем рабочей жидкости: 200-250 л/га Количество обработок: 1-4
      <h2>Особенности применения</h2>
      Не растворять препарат в холодной воде! Разница температуры воды и
      препарата при разведении не должна превышать 10°С При длительном хранении
      (особенно при высоких температурах) может образовываться осадок, не
      влияющий на качество препарата. Перед применением осадок взболтать.
      Препарат может использоваться в баковой смеси с химическими пестицидами и
      минеральными удобрениями. Рекомендуется тщательное перемешивание смеси в
      опрыскивателе. Не смешивать СтимиксПрофи с медьсодержащими препаратами,
      кальциевой селитрой и другими кальцийсодержащими материалами в виду того,
      что часть компонентов препарата может выпасть в осадок. При использовании
      комплексов NPK + микроэлементы предпочтительно провести их предварительное
      растворение и смешивание на растворных узлах. КАСы можно использовать
      непосредственно при заполнении водой бака опрыскивателя. Не рекомендуется
      использовать раствор удобрений, имеющий кислую реакцию (рН ниже 5-5,5).
      Повысить рН можно путем добавления в раствор удобрений мочевины или
      углекислого аммония в количестве от 2 кг и более на 200 л воды. В схемах
      обработки растений с применением антибиотиков рекомендуется раздельное
      применение антибиотика и СтимиксПрофи.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/biocentr-stavropole/">
        ООО НПО Центр биотехнологий «Биоцентр Ставрополье»
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Стимикс® Профи - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Стимикс® Профи"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default stimiksprofi;
