import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const stimikssemja = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/09/1531648246_stimiks-semya1.jpeg"></a>
        Получен путем сложного управляемого микробного гидролиза
      </strong>
      Защита семян сельскохозяйственных культур от почвенных фитопатогенов и их
      токсинов. Стимулирование прорастания семян и развития проростка.
      Оптимизация фосфорного питания. Ингибирует активность патогенных грибов и
      бактерий, в том числе и Pseudomonassyringae. Стимулирует биосинтез
      нуклеиновых кислот и активность ферментов в семени и проростке.
      <h2>Преимущество</h2>
      <ul>
        <li>Свободные аминокислоты</li>
        <li>Соли гуминовых кислот</li>
        <li>Живые микробные культуры</li>
        <li>Крезацин</li>
        <li>Биологически активные вещества</li>
      </ul>
      <h3>Применение</h3>
      Вид обработки: предпосевная обработка семян методом протравливания Расход
      препарата: 1л/т семян Объем рабочей жидкости: 10 -15 (до 30) л/т семян
      <h3>Особенности применения</h3>
      Не растворять препарат в холодной воде! Разница температуры воды и
      препарата при разведении не должна превышать 10°С. При длительном хранении
      (особенно при высоких температурах) может образовываться осадок, не
      влияющий на качество препарата. Перед применением осадок взболтать.
      Препарат может использоваться в баковой смеси с химическими пестицидами и
      минеральными удобрениями. Не смешивать Стимикс Семена с медьсодержащими
      препаратами. Не рекомендуется использовать в баковой смеси со Стимикс Семя
      растворы, имеющий кислую реакцию (рН ниже 5-5,5). Повысить рН можно путем
      добавления в раствор углекислого калия. При протравливании семян сложными
      баковыми смесями рекомендуется увеличить количество рабочей жидкости до
      15-30 л/т семян.
      <h3>Безопасность</h3>
      4-й класс опасности(малоопасный продукт). В случае попадания на кожу -
      смыть водой с мылом. При попадании в глаза - промыть большим количеством
      воды. При случайном проглатывании - прополоскать рот, выпить воды с
      измельченным активированным углем. При применении, хранении и
      транспортировке соблюдать требования и меры предосторожности, согласно
      СанПин 1.2.2584-10.
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/biocentr-stavropole/">
        ООО НПО Центр биотехнологий "Биоцентр Ставрополье"
      </a>
      <strong>Упаковка:</strong> 10 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Стимикс® Семя - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Стимикс® Семя" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default stimikssemja;
