import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const stsenikkombiks = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/03/234234-1.jpg"></a>
        <a href="https://berkanabio.ru/category/klotianidin/">Клотианидин</a>{" "}
        250 г/л +{" "}
        <a href="https://berkanabio.ru/category/protiokonazol/">
          Протиоконазол
        </a>{" "}
        37,5 г/л +{" "}
        <a href="https://berkanabio.ru/category/tebukonazol/">Тебуконазол</a> 5
        г/л +{" "}
        <a href="https://berkanabio.ru/category/fluoksastrobin/">
          Флуоксастробин
        </a>{" "}
        37,5 г/л
      </strong>
      Единственный в России 4-компонентный инсектофунгицидный протравитель для
      обработки семян зерновых культур, эффективно контролирующий семенную и
      почвенную инфекции, а также позволяющий защищать всходы от вредителей.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Первый на рынке РФ комбинированный инсектофунгицидный протравитель для
          зерновых культур.
        </li>
        <li>
          Наличие в составе клотианидина обеспечивает надежный контроль широкого
          спектра вредителей всходов.
        </li>
        <li>Самый эффективный контроль жужелицы в посевах зерновых.</li>
        <li>
          Высокоэффективный контроль широкого спектра семенной и почвенной
          инфекции.
        </li>
        <li>Исключительная эффективность против снежной плесени.</li>
        <li>Исключительный ростостимулирующий эффект.</li>
        <li>Хорошее окрашивание семян.</li>
      </ul>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/bajer/">Байер</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Сценик Комби, КС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Сценик Комби, КС"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default stsenikkombiks;
