import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sumatra = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Суматра – раннеспелый заразихоустойчивый гибрид, оптимизированный для
      гербицида Экспресс™ компании FMC. Тип гибрида: оптимизированный для
      гербицида Экспресс™ компании FMC Группа спелости: раннеcпелый Назначение:
      линолевый Масличность: 50-52% Высота растений: 140-160 см (в зависимости
      от влагообеспеченности) Устойчивость к расам заразихи: A–G Технология
      возделывания: с применением гербицида Экспресс™ компании FMC
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Гомозиготность гибрида обеспечивает устойчивость к полной норме
              гербицида (50гр/га). Генетически устойчив к высоковирулентным
              расам заразихи Гибрид устойчив к засушливым условиям и действию
              высоких температур Компактный габитус и активная саморегуляция
              тургора позволяет растению максимально использовать доступную воду
              и питательные элементы для формирования стабильного урожая, что
              особенно важно в стрессе Высокий параметр масличности – 50-52%
              (лучший в своем классе гибридов) что дает дополнительную
              возможность сельхозпроизводителям заработать больше с каждого
              гектара производственных полей.
            </td>
            <td>
              Пластичен к срокам сева Гибрид отлично подходит для возделывания в
              условиях ограниченного вегетационного цикла, а также умеренного и
              малозатратного земледелия Избегать возделывания в условиях
              переувлажнения
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СУМАТРА - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СУМАТРА" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sumatra;
