import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const sumikohts = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Среднеспелый гибрид подсолнечника, оптимизированный для гербицида
      Экспресс™ компании FMC Тип гибрида: оптимизированный для гербицида
      Экспресс™ компании FMC Группа спелости: среднеспелый Назначение: линолевый
      Масличность: 51-53% Высота растений: 150–170 см Устойчивость к расам
      заразихи: A–E Технология возделывания: с применением гербицида Экспресс™
      компании FMC
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Генетически близок к гибриду НК БРИО Средняя энергия роста на
              начальных этапах органогенеза Отличается высокой стабильностью
              Генетически устойчив к гербицидам группы на основе
              трибенурон-метила (гомозиготный гибрид)
            </td>
            <td>
              Применять интенсивную технологию возделывания Избегать
              возделывания в полях с агрессивными расами заразихи Сеять в
              оптимальные сроки Избегать загущения посевов
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СУМИКО HTS - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СУМИКО HTS" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default sumikohts;
