import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const suomi = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Раннеспелый высокомасличный гибрид, оптимизированный для гербицида
      Экспресс® компании FMC, сочетающий устойчивость к заразихе расы G и
      урожайность на уровне среднеспелых гибридов. Тип гибрида: оптимизированный
      для гербицида Экспресс™ компании FMC Группа спелости: раннеcпелый
      Назначение: линолевый Масличность: 51-53% Высота растений: 150-170 см (в
      зависимости от влагообеспеченности) Устойчивость к расам заразихи: A–G
      Технология возделывания: с применением гербицида Экспресс™ компании FMC
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Устойчивость к заразихе расы G. Гомозиготный гибрид – устойчив к
              полной норме гербицида Экспресс. Стабильно высокое содержание
              масла - до 53%.
            </td>
            <td>
              Пластичен к срокам сева. Стабильный результат даже в условиях
              бедных почв, пригоден для ресурсосберегающего земледелия.
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СУОМИ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СУОМИ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default suomi;
