import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const suzukahts = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>Syngenta</strong>
      Среднеранний заразихоустойчивый гибрид оптимизированный для гербицида
      Экспресс™ Компании FMC для засушливых условий. Тип гибрида:
      оптимизированный для гербицида Экспресс™ компании FMC Группа спелости:
      среднеранний Назначение: линолевый Масличность: 49-51% Высота растений:
      160-180 см (в зависимости от влагообеспеченности) Устойчивость к расам
      заразихи: A–G Технология возделывания: с применением гербицида Экспресс™
      компании FMC
      <table>
        <tbody>
          <tr>
            <td>Преимущество</td>
            <td>Рекомендации по технологии</td>
          </tr>
          <tr>
            <td>
              Гомозиготность гибрида обеспечивает устойчивость к полной норме
              гербицида (50гр/га) Генетически устойчив к высоковирулентным расам
              заразихи Гибрид чрезвычайно устойчив к засушливым условиям и
              действию высоких температур Раннее цветение и повышенный порог
              стерилизации пыльцы обеспечивает выполненную корзинку Быстрый
              старт обеспечит развитие корневой системы до начала засухи
            </td>
            <td>
              Пластичен к срокам сева Стабильный результат даже в условиях
              бедных почв, пригоден для малозатратного земледелия Избегать
              загущения посевов
            </td>
          </tr>
        </tbody>
      </table>
       
    </div>
  );

  return (
    <>
      <Head>
        <title>СУЗУКА HTS - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="СУЗУКА HTS" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default suzukahts;
