import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const tajgeremv = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <a href="https://berkanabio.ru/category/klokvintoset-meksil/">
        Клоквинтосет-мексил
      </a>{" "}
      34,5 г/л +{" "}
      <a href="https://berkanabio.ru/category/fenoksaprop-p-etil/">
        Феноксапроп-П-этил
      </a>{" "}
      69 г/л Гербицид системного спектра действия.
      <h2>Преимущества</h2>
      <ul>
        <li>
          Эффективный контроль всего спектра однолетних злаковых сорняков.
        </li>
        <li>
          Широкий период применения, независимо от фазы развития культуры.
        </li>
        <li>
          Полная селективность к культурным растениям благодаря наличию
          антидота.
        </li>
        <li>
          Возможность применения в баковых смесях с гербицидами против
          двудольных сорняков.
        </li>
        <li>Не нарушает севооборот с/х культур.</li>
      </ul>
      <h3>Норма расхода</h3>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния пре­па­ра­та</strong>
            </td>
            <td>
              <strong>Куль­ту­ра, об­ра­ба­ты­ва­емый объ­ект</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,8-1</td>
            <td>Пшеница яровая и озимая, ячмень яровой</td>
            <td>
              Однолетние злаковые сорняки (виды щетинника, просо куриное, просо
              сорное, овсюг, метлица полевая)
            </td>
            <td>
              Опрыскивание посевов в ранние фазы развития (2-3 листа) сорняков
              независимо от фазы развития культуры (с учетом чувствительности
              сортов). Озимая пшеница обрабатывается весной. Расход рабочей
              жидкости – 150-200 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель: </strong>
      <a href="https://berkanabio.ru/category/kchhk/">КЧХК</a>
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Тайгер, ЭМВ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Тайгер, ЭМВ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default tajgeremv;
