import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const taranve = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/05/berkanabio_taran-ve.jpg"></a>
        <a href="https://berkanabio.ru/category/zeta-cipermetrin/">
          Зета-циперметрин
        </a>{" "}
        100 г/л
      </strong>
      Пиретроид третьего поколения контактно-кишечный инсектицид широкого
      спектра действия.
      <h2>Преимущество</h2>
      <ul>
        <li>Низкие нормы применения.</li>
        <li>Высокая скорость действия.</li>
        <li>Водная основа препарата устраняет проблему фитотоксичности.</li>
        <li>Высокая эффективность при высоких температурах.</li>
        <li>Период защитного действия составляет 3–4 недели.</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,07-0,1</span>
              <span>0,07-0,1 (А)</span>
            </td>
            <td>
              <span>Пшеница</span>
            </td>
            <td>
              <span>
                Клоп вредная черепашка, пьявица, тли, хлебные жуки, трипсы
              </span>
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>
                Расход рабочей жидкости- 200-400 л/га, для авиаприменения –
                25-50 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,07-0,1</span>
              <span>0,07-0,1 (А)</span>
            </td>
            <td>
              <span>Ячмень</span>
            </td>
            <td>
              <span>Пьявица, трипсы</span>
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>
                Расход рабочей жидкости - 200-400 л/га, для авиаприменения –
                25-50 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,1</span>
              <span>0,1 (А)</span>
            </td>
            <td>
              <span>Рапс, горчица (кроме горчицы на масло)</span>
            </td>
            <td>
              <span>Рапсовый цветоед</span>
            </td>
            <td>
              <span>Опрыскивание в период вегетации.</span>
              <span>
                Расход рабочей жидкости - 200-400 л/га, для авиаприменения –
                25-50 л/га
              </span>
            </td>
          </tr>
          <tr>
            <td>
              <span>0,1-0,15</span>
            </td>
            <td>
              <span>Пастбища, участки заселенные саранчовыми</span>
            </td>
            <td>
              <span>Саранчовые</span>
            </td>
            <td>
              <span>
                Опрыскивание в период развития личинок. Срок возможного
                пребывания людей на обработанных площадях не ранее 3 дней после
                обработки; сбор грибов и ягод в сезон обработки не допускается.
              </span>
              <span>Расход рабочей жидкости – 200-400 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/fmrus/">
        <span>ФМРус</span>
      </a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Таран, ВЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Таран, ВЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default taranve;
