import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const terrastarvdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/tribenuron-metil/">
          Трибенурон-метил
        </a>{" "}
        750 г/кг
      </strong>
      Относится к гербицидам системного действия и используется для уничтожения
      бодяка полевого и двудольных сорняков, произрастающих среди посевов
      культур, относящихся к зерновым колосовым.
      <h2>Преимущество</h2>
      <ul>
        <li>
          Обладает высокой эффективностью; препарат обладает высокой
          избирательностью действия в отношении зерновых культур, это очень
          большое преимущество – широчайший диапазон применения (2–3 настоящих
          листа у культуры до выхода флаг-листа);
        </li>
        <li>
          Химстар имеет широкий спектр воздействия на сорняки, устойчивые к
          гербицидам гормонального действия 2,4-Д, поэтому его можно применять
          против большинства видов сорных трав, в том числе устойчивых к другим
          гербицидам;
        </li>
        <li>
          Можно без опасений вносить холодной весной, поскольку в отличие от
          гормональных гербицидов препарат не вызывает токсичности;
        </li>
        <li>
          Быстро разлагается в почве, поэтому не существует ограничений в
          отношении последующих культур при обычной ротации в севообороте;
        </li>
        <li>
          Позволяет существенно снизить гербицидную нагрузку на почву. Период
          защитного действия: препарат надежно защищает культуру от фазы всходов
          до появления флаг-листа.
        </li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния пре­па­ра­та</strong>
            </td>
            <td>
              <strong>Куль­ту­ра, об­ра­ба­ты­ва­емый объ­ект</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,015-0,02</td>
            <td>Пшеница и ячмень яровые, овес</td>
            <td>
              Однолетние двудольные, в т.ч. устойчивые к 2,4-Д и 2М-4Х, сорняки
            </td>
            <td>
              Опрыскивание посевов в фазе 2-3 листьев - начала кущения культуры
              и ранние фазы роста сорняков. Расход рабочей жидкости - 200-300
              л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
          <tr>
            <td>0,02-0,025</td>
            <td>Пшеница и ячмень яровые и озимые, овес</td>
            <td>
              Однолетние двудольные, в т.ч. устойчивые к 2,4-Д и 2М-4Х, сорняки
              и бодяк полевой
            </td>
            <td>
              Опрыскивание посевов в фазе кущения культуры и ранние фазы роста
              сорняков. Озимые обрабатывают весной. Расход рабочей жидкости -
              200-300 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>
      <a href="https://berkanabio.ru/category/rosagrohim/">
        {" "}
        ООО НПО “РосАгроХим”
      </a>
      <strong>Упаковка:</strong> 100 гр
    </div>
  );

  return (
    <>
      <Head>
        <title>Террастар, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Террастар, ВДГ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default terrastarvdg;
