import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const tituspljusvdg = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/category/dikamba/">
          Дикамба (диметиламинная соль)
        </a>{" "}
        609 г/кг дикамбы к-ты +{" "}
        <a href="https://berkanabio.ru/category/rimsulfuron/">Римсульфурон</a>{" "}
        32,5 г/кг
      </strong>
      Двухкомпонентный гербицид, который позволяет контролировать практически
      все сорняки в посевах кукурузы, включая самые проблемные виды.
      <h2>Преимущество</h2>
      <ul>
        <li>
          эффективен против всех злаковых (включая пырей и гумай), а также
          большинства двудольных сорняков в посевах кукурузы;
        </li>
        <li>
          высокоэффективен против всех злаковых сорняков, включая многолетние
          пырей и гумай, а также против всех двудольных сорняков, включая
          амброзию, марь, паслен, бодяки, осоты и вьюнок полевой;
        </li>
        <li>
          обеспечивает быстрый гербицидный эффект, симптомы действия на сорняки
          появляются уже через несколько часов;
        </li>
        <li>
          не нуждается в гербицидах-партнерах, в связи с чем нет необходимости
          готовить баковые смеси;
        </li>
        <li>
          исключает выживание и накопление на полях резистентных видов сорняков,
          снижая, таким образом, запасы семян сорняков в почве;
        </li>
        <li>имеет широкое окно применения от 2 до 6 листьев у кукурузы;</li>
        <li>
          чрезвычайно удобен в работе и не имеет ограничений для последующих
          культур севооборота;
        </li>
        <li>соответствует стандартам качества компании «Дюпон».</li>
      </ul>
      <h2>Норма расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>Спо­соб и вре­мя об­ра­бот­ки</strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <span>0,307-0,385</span>
            </td>
            <td>
              <span>Кукуруза</span>
            </td>
            <td>
              <span>
                Однолетние и многолетние двудольные и злаковые (в т.ч.
                однолетние двудольные, устойчивые к 2,4-Д и 2М-4Х) сорняки
              </span>
            </td>
            <td>
              <span>
                Опрыскивание посевов в фазе 2-6 листьев культуры, 1-4 листьев у
                однолетних сорняков и розетки листьев у многолетних двудольных и
                при высоте пырея ползучего 10-15 см в смеси с 200 мл/га
                Тренда-90.
              </span>
              <span>Расход рабочей жидкости - 200-300 л/га</span>
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/djupon/">Дюпон</a>
      <strong>Упаковка: </strong>0,768 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Титус Плюс, ВДГ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Титус Плюс, ВДГ"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default tituspljusvdg;
