import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const tmtdtps = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2019/03/berkanabio_tmtd-tps.jpg"></a>
        <a href="https://berkanabio.ru/category/tiram/">Тирам</a> (ТМТД) 400 г/л
      </strong>
      Фунгицид, с его помощью осуществляется протравливание семян яровой и
      озимой пшеницы для защиты от комплекса болезней, включая виды головни,
      корневые гнили.
      <h2>Преимущества</h2>
      <ul>
        <li>Быстрое контактное действие.</li>
        <li>
          Эффективное подавление патогенной микрофлоры – гарантирует семенам
          лучший старт.
        </li>
        <li>Длительная защита культуры с начальных фазвегетации.</li>
        <li>
          Усовершенствованная препаративная форма и удобство в применении.
        </li>
        <li>Высокая эффективность и селективность.</li>
        <li>Гарантия получения дружных и здоровых всходов культуры.</li>
      </ul>
      <h2>Нома расхода</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния пре­па­ра­та</strong>
            </td>
            <td>
              <strong>Куль­ту­ра, об­ра­ба­ты­ва­емый объ­ект</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>2,5-3</td>
            <td>Пшеница яровая, озимая</td>
            <td>
              Твердая головня, фузариозная и гельминтоспориозная корневые гнили,
              плесневение семян
            </td>
            <td>
              Протравливание семян заблаговременно (2-7 месяцев) или перед
              посевом (7-14 дней). Расход рабочей жидкости - 10 л/т.
            </td>
          </tr>
          <tr>
            <td>4</td>
            <td>Кукуруза</td>
            <td>
              Пузырчатая и пыльная головня, гельминтоспориозная корневая гниль,
              фузариозная корневая гниль, плесневение семян, бактериоз
            </td>
            <td>
              Протравливание семян за 2-15 дней до посева или заблаговременно
              (2-7 месяцев). Расход рабочей жидкости - 10 л/т.
            </td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/pestitsidy/fmrus/">ФМРус</a>
      <strong>Упаковка:</strong> 5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>ТМТД, ТПС - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="ТМТД, ТПС" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default tmtdtps;
