import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const tsitodef100vrp = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>100 г/кг N-(1,2,4-триазол-4-ил)-N'-фенилмочевины</strong>
      Антистрессовый эффект. Препарат обладает активностью природных
      фитогормонов цитокининов.Препарат обладает активностью природных
      фитогормонов цитокининов.
      <h3>Преимущества препарата</h3>
      <ul>
        <li>
          Использование препарата для предпосевной обработки семян способствует
          получению более ранних и дружных всходов и эффективному использованию
          проростками почвенной влаги.
        </li>
        <li>
          Применение препарата по вегетирующим растения в условиях недостатки
          влаги, повышенных или пониженных температур, обеспечивает стабильный
          антистрессовый эффект.
        </li>
        <li>
          В зависимости от продолжительности и интенсивности стрессовых
          факторов, эффект от применения препарата сохраняется в течение 2-3
          недель.
        </li>
      </ul>
      <h3>Механизм действия</h3>
      Действующее вещество препарата обладает активностью природных фитогормонов
      цитокининов. При воздействии на растение стрессовых факторов, под
      действием препарата происходит стабилизация белоксинтезирующих систем
      растений, повышается температурный порог коагуляции белков цитоплазмы, что
      обеспечивает устойчивость к недостатку влаги. Препарат обеспечивает
      стабильный синтез хлорофилла в клетках и устойчивую работу
      фотосинтетического аппарата даже в условиях пониженных температур;
      ускоряет процессы накопление сахаров в узлах кущения, что повышает
      морозостойкость.
      <h3>Норма расхода и применение</h3>
      <table>
        <tbody>
          <tr>
            <td>
              <strong>Культуры</strong>
            </td>
            <td>
              <strong>Норма расхода препарата</strong>
            </td>
            <td>
              <strong>
                Способ, время обработки, норма расхода рабочей жидкости
              </strong>
            </td>
            <td>
              <strong>Срок ожидания (кратность обработок)</strong>
            </td>
          </tr>
          <tr>
            <td>Пшеница,  ячмень</td>
            <td>20-40 г/т</td>
            <td>
              Предпосевная обработка семян. Расход рабочей жидкости – 10 л/т
            </td>
            <td>-(1)</td>
          </tr>
          <tr>
            <td>Пшеница,  ячмень</td>
            <td>200-300 г/га</td>
            <td>
              Опрыскивание растений в фазу кущения - начала колошения. Расход
              рабочей жидкости 200-300 л/га.
            </td>
            <td>-(1)</td>
          </tr>
          <tr>
            <td>Сахарная свёкла</td>
            <td>300-400 г/га</td>
            <td>
              Опрыскивание растений в фазу смыкания рядков. Расход рабочей
              жидкости 200-300 л/га.
            </td>
            <td>-(1)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong>{" "}
      <a href="https://berkanabio.ru/category/agrosintez/">АгроСинтез</a>
      <strong>Упакока:</strong> 1 кг
    </div>
  );

  return (
    <>
      <Head>
        <title>Цитодеф-100®, ВРП - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Цитодеф-100®, ВРП"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default tsitodef100vrp;
