import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const urozhajzernavrossiiprevysit100mlntonnsborpshenitsyvyrastetdo63mlntonnusda =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        Минсельхоз США (USDA) во вторник, 10 мая, впервые в 2016 году
        опубликовал прогноз по рынку зерна на будущий 2016/2017 сельхозгод (июль
        2016 года - июнь 2017 года). В том числе, и для стран Причерноморья –
        России, Казахстана и Украины. По прогнозам экспертов USDA, производство
        пшеницы в данной группе стран может сократиться на 1,77 млн тонн до
        115,83 млн тонн. За счет уменьшения сбора в Казахстане на 0,75 млн тонн
        до 13 млн тонн и Украине на 3,27 млн тонн до 24 млн тонн. В России по
        прогнозу производство пшеницы вырастет на 1,96 млн тонн до 63 млн тонн
        (урожай пшеницы текущего сезона в России оценен USDA в 61,04 млн тонн).
        Минсельхоз США оценил урожай зерна в России более чем в 100 млн тонн.
        Экспорт пшеницы сохранится на уровне этого сельхозгода - 24,5 млн тонн.
        Переходящие запасы российской пшеницы на 1 июля 2017 года прогнозируются
        на уровне 8,13 млн тонн. Прогноз сбора фуражного зерна в РФ в новом
        сельхозгоду составляет 39,38 млн тонн против 37,43 млн тонн по оценкам
        этого года. Экспорт увеличится до 8,61 млн тонн с 8,27 млн тонн, которые
        могут быть поставлены за рубеж в этом сельхозгоду. Переходящие запасы
        фуражного зерна для России на 1 июля 2017 года оценены в 1,65 млн тонн.
        Мировой урожай пшеницы в новом сельхозгоду Минсельхоз США прогнозирует в
        объеме 726,99 млн тонн против 734,05 млн тонн в этом году. Переходящие
        запасы пшеницы к 1 июля 2017 года могут увеличиться до 257,34 млн тонн с
        242,91 млн тонн в этом сельхозгоду. Мировое производство фуражного зерна
        оценено в 1 млрд 298,63 млн тонн против 1 млрд 258,15 млн тонн в текущем
        сельхозгоду. Переходящие запасы фуражного зерна, как прогнозируют
        эксперты Минсельхоза США, снизятся до 241,03 млн тонн с 244,54 млн тонн
        в этом сельхозгоду. Внутреннее потребление причерноморской группы
        вырастет на 0,94 млн тонн до 78,97 млн тонн. В основном, за счет
        потребления фуражного зерна, которое вырастет на 0,6 млн тонн до 26,33
        млн тонн. В России внутреннее потребление пшеницы увеличится на 0,5 млн
        тонн до 37,5 млн тонн только за счет фуражной пшеницы. В Казахстане и
        Украине потребление пшеницы останется на текущих уровнях - 6,9 млн тонн
        и 12,5 млн тонн соответственно. Существенно меньше в будущем сезоне
        станет экспортный потенциал Причерноморья, минус 4,7 млн тонн до 43,63
        млн тонн. На 0,5 млн тонн до 7 млн тонн сократится экспортный потенциал
        Казахстана и на 4 млн тонн до 11,50 млн тонн Украины. Источник: 
        <a href="http://zerno.avs.ru/news/64019/yrojai-zerna-v-rossii-previsit-100-mln-tonn-sbor-pshenici-virastet-do-63-mln-tonn---usda.html">
          zerno.avs.ru
        </a>
      </div>
    );

    return (
      <>
        <Head>
          <title>
            Урожай зерна в России превысит 100 млн тонн, сбор пшеницы вырастет
            до 63 млн тонн - USDA - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="Урожай зерна в России превысит 100 млн тонн, сбор пшеницы вырастет до 63 млн тонн - USDA"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default urozhajzernavrossiiprevysit100mlntonnsborpshenitsyvyrastetdo63mlntonnusda;
