import React from 'react';
            import Layout from "@/components/general/layout";
            import Head from "next/head";
            import HeadNav from "@/components/services/head-nav";
            import ReactHtmlParser from 'html-react-parser';

            function wrapUntaggedTextWithP(node) {
                if (typeof node === 'string') {
                    return <p>{node}</p>;
                }

                if (React.isValidElement(node)) {
                    if (node.type === 'span') {
                        return node; 
                    }
                const hasSpanChildren = React.Children.toArray(node.props.children).some(child => React.isValidElement(child) && child.type === 'span');
                 if (!hasSpanChildren) {
                    const children = React.Children.map(node.props.children, child => wrapUntaggedTextWithP(child));
                    return React.cloneElement(node, null, children);
                } else {
                    return node;
                }
            }
                return node;
        }

            const uslugi = () => {
                let style= {
                    background: '#185F65',
                    color: '#D4A95A',
                };
                let pathStyle = {
                    fill: '#D4A95A',
                };
                let headerStyle = {
                    color: '#D4A95A'
                };

            
                const jsx_content_wrapped = wrapUntaggedTextWithP(<div><div class="panel-layout" id="pl-1086"><div background_image_attachment":false,"background_display":"tile","cell_alignment":"flex-start"}"="" class="panel-grid panel-no-style" data-ratio="1" data-ratio-direction="right" data-style="{" id="pg-1086-0"><div class="panel-grid-cell" data-weight="0.5" id="pgc-1086-0-0"><div background_image_attachment":false,"background_display":"tile"}"="" class="so-panel widget widget_text panel-first-child panel-last-child" data-index="0" data-style="{" id="panel-1086-0-0-0"><h3 class="widget-title">Пневмоходы</h3> <div class="textwidget"><p>Пневмоходы является востребованным агрегатом с шинами сверхнизкого давления которые не причинят вреда растениям в процессе опрыскивания, используется при выполнении различных агрохимических задач на полях. Мы решили помочь сельхозпроизводителям и закупили некое количество данных агрегатов и сдаем их в аренду для обработки полей.</p>
<p><a href="http://berkanabio.ru/pnevmohod/">Подробнее о пневмоходах…</a></p>
<p><a href="http://berkanabio.ru/pnevmohod/"></a></p>
</div>
</div></div><div class="panel-grid-cell" data-weight="0.5" id="pgc-1086-0-1"><div background_image_attachment":false,"background_display":"tile"}"="" class="so-panel widget widget_text panel-first-child panel-last-child" data-index="1" data-style="{" id="panel-1086-0-1-0"><h3 class="widget-title">Элеватор</h3> <div class="textwidget"><p>Сооружение для хранения больших партий сельскохозяйственных культур и доведения его до кондиционного состояния. В распоряжении компании имеется доступ к несколько элеваторам на территории Воронежской области. В связи с этим оказываем услуги по хранению и доработки вашего урожая.<br/>
<a href="https://i2.wp.com/berkanabio.ru/wp-content/uploads/2018/08/IMG_1405.jpg"></a></p>
</div>
</div></div></div></div></div>);

                return (
                    <>
                        <Head>
                            <title>Услуги - Berkana</title>
                            <meta name="description" content="Generated by create next app" />
                            <meta name="viewport" content="width=device-width, initial-scale=1" />
                            <link rel="icon" href="/favicon.ico" />
                        </Head>
                        <Layout style={headerStyle, pathStyle}>
                            <HeadNav pageName="Услуги" style={style} pathStyle={pathStyle} />
                            <div className="page-content">
                                <div className="page-content-wrapper">
                                    {jsx_content_wrapped}
                                </div>
                            </div>
                        </Layout>
                    </>
                );
            };

            export default uslugi;
