import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const vitaminspozvoljaetpoluchitizodnogosemeni23prorostka = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      Сейчас не время спорить о том можно ли с помощью витамина С лечить
      простуду, ведь биохимики из Университета штата Калифорния (Риверсайд)
      сделали открытие, благодаря которому аграрии могут существенно снизить
      расходы на приобретение семян, а производство этого вещества возрастет
      вдвое или втрое. Дениель Р. Галлье и Зонг Чен обнаружили, что повышение
      уровня дегидроаскорбат редуктазы (DHAR), обычного фермента, встречающегося
      в клетках растений и животных, приводит к увеличению содержания витамина
      С, а в результате одно семя может дать два или даже три проростка.
      Лабораторные эксперименты показали, что инъекция витамина С в растительную
      яйцеклетку многократно повышает вероятность образования двойных и тройных
      семян. Витамин заставляет оплодотворенную яйцеклетку разделиться на две
      или три новые клетки, каждая из которых дает зародыш. В итоге, вместо
      одного зародыша, в семени развивается два или три будущих растения. В
      своих исследованиях ученые использовали табак, но Галлье полагает, что
      витамин С может приводить к образованию "двойни" и у других видов
      растений. "Ранние стадии эмбрионального развития довольно консервативны у
      разных видов растений, поэтому витамин С должен оказывать аналогичный
      эффект почти на все виды, -- написал ученый в пресс-релизе. -- Ценность
      этого открытия состоит в том, что оно дает в наши руки инструмент для
      получения генетически идентичных растений и увеличения скорости
      воспроизводства высокоценных линий сельскохозяйственных культур". Однако
      ученый в данный момент не может дать подробную инструкцию, как сделать
      инъекцию витамина С в яйцеклетку дорогих семян рапса. Источник:{" "}
      <a href="http://www.agroxxi.ru/zhurnal-agroxxi/novosti-nauki/novaja-rol-vitamina-s-umenshite-zatraty-na-semena.html">
        www.agroxxi.ru
      </a>
    </div>
  );

  return (
    <>
      <Head>
        <title>
          Витамин С позволяет получить из одного семени 2—3 проростка - Berkana
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav
          pageName="Витамин С позволяет получить из одного семени 2—3 проростка"
          style={style}
          pathStyle={pathStyle}
        />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default vitaminspozvoljaetpoluchitizodnogosemeni23prorostka;
