import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/general/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const vvoronezhskujuoblastvernulislivnivregioneustanovilizheltyjurovenpogodnojopasnosti =
  () => {
    let style = {
      background: "#185F65",
      color: "#D4A95A",
    };
    let pathStyle = {
      fill: "#D4A95A",
    };
    let headerStyle = {
      color: "#D4A95A",
    };

    const jsx_content_wrapped = wrapUntaggedTextWithP(
      <div>
        В Воронежской области объявлен желтый уровень погодной опасности.
        Сильные дожди начались утром в среду, 26 октября, и продлятся до 6:00
        четверга, 27 октября. Об этом сообщает прогностическая карта
        Гидрометцентра России для Центрального федерального округа. Согласно
        прогнозу Гидрометцентра, днем 26 октября в Воронеже выпадет около 8,6 мм
        осадков, а ночью около 1,6 мм. Сильные дожди пройдут в Павловске, где
        днем 26 октября прогнозируется 17,1 мм осадков, а также в Богучаре –
        11,8 мм осадков. По прогнозу Воронежского гидрометцентра, на рабочей
        неделе в дожди в регионе ожидаются ежедневно. Температура воздуха в
        дневное время не будет переходить отметку в +10 градусов. Источник:
        www.zerno.avs.ru
      </div>
    );

    return (
      <>
        <Head>
          <title>
            В Воронежскую область вернулись ливни: в регионе установили желтый
            уровень погодной опасности - Berkana
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout style={(headerStyle, pathStyle)}>
          <HeadNav
            pageName="В Воронежскую область вернулись ливни: в регионе установили желтый уровень погодной опасности"
            style={style}
            pathStyle={pathStyle}
          />
          <div className="page-content">
            <div className="page-content-wrapper">{jsx_content_wrapped}</div>
          </div>
        </Layout>
      </>
    );
  };

export default vvoronezhskujuoblastvernulislivnivregioneustanovilizheltyjurovenpogodnojopasnosti;
