import React from "react";
import Layout from "@/components/general/layout";
import Head from "next/head";
import HeadNav from "@/components/services/head-nav";
import ReactHtmlParser from "html-react-parser";

function wrapUntaggedTextWithP(node) {
  if (typeof node === "string") {
    return <p>{node}</p>;
  }

  if (React.isValidElement(node)) {
    if (node.type === "span") {
      return node;
    }
    const hasSpanChildren = React.Children.toArray(node.props.children).some(
      (child) => React.isValidElement(child) && child.type === "span"
    );
    if (!hasSpanChildren) {
      const children = React.Children.map(node.props.children, (child) =>
        wrapUntaggedTextWithP(child)
      );
      return React.cloneElement(node, null, children);
    } else {
      return node;
    }
  }
  return node;
}

const zlakterrke = () => {
  let style = {
    background: "#185F65",
    color: "#D4A95A",
  };
  let pathStyle = {
    fill: "#D4A95A",
  };
  let headerStyle = {
    color: "#D4A95A",
  };

  const jsx_content_wrapped = wrapUntaggedTextWithP(
    <div>
      <strong>
        <a href="https://berkanabio.ru/wp-content/uploads/2020/08/berkanabio_zlakterr-ke-2.jpg"></a>
        <a href="https://berkanabio.ru/category/kletodim/">Клетодим</a> 240 г/л
      </strong>
      Противозлаковый гербицид для защиты посевов сахарной свеклы, сои,
      картофеля, льна и овощных культур
      <h3>Преимущество</h3>
      <ul>
        <li>
          Незаменимый гербицид в борьбе с однолетними и многолетними злаковыми
          сорняками.
        </li>
        <li>Отличается высокой биологической эффективностью.</li>
        <li>Характеризуется высокой селективностью к защищаемым культурам.</li>
        <li>Возможно применение во всех фазах развития культур.</li>
        <li>
          Благодаря системному действию обеспечивает гибель, не только надземной
          части, но и корневой системы сорняков, предотвращая повторное
          отрастание.
        </li>
      </ul>
      <h2>Норма расхода и применение</h2>
      <table>
        <thead>
          <tr>
            <td>
              <strong>Нор­ма при­ме­не­ния</strong>
            </td>
            <td>
              <strong>Куль­ту­ра</strong>
            </td>
            <td>
              <strong>Вред­ный объ­ект</strong>
            </td>
            <td>
              <strong>
                Спо­соб, вре­мя об­ра­бот­ки, осо­бен­нос­ти при­ме­не­ния
              </strong>
            </td>
            <td>
              <strong>Срок ожи­да­ния (крат­ность об­ра­бо­ток)</strong>
            </td>
            <td>
              <strong>
                Сро­ки вы­хо­да для руч­ных (ме­ха­ни­зи­ро­ван­ных ра­бот)
              </strong>
            </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>0,2-0,4</td>
            <td>Свекла сахарная, соя, лук-репка</td>
            <td>
              Однолетние злаковые (виды щетинника, просо куриное, просо полевое)
              сорняки
            </td>
            <td>
              Опрыскивание сорняков в период их активного роста (в фазе от 2-6
              листьев) с добавлением 0,2 л/га ПАВ Неон 99 (Неонол АФ
              <sub>9-12</sub>). Расход рабочей жидкости - 200-300 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
          <tr>
            <td>0,7-1</td>
            <td>Свекла сахарная, соя, лук-репка</td>
            <td>Многолетние злаковые (пырей ползучий) сорняки</td>
            <td>
              Опрыскивание посевов при высоте сорняков 10-20 см с добавлением
              0,2 л/га ПАВ Неон 99 (Неонол АФ<sub>9-12</sub>). Расход рабочей
              жидкости - 200-300 л/га
            </td>
            <td>60(1)</td>
            <td>-(3)</td>
          </tr>
        </tbody>
      </table>
      <strong>Производитель:</strong> Гранум
      <strong>Упаковка: </strong>5 л
    </div>
  );

  return (
    <>
      <Head>
        <title>Злактерр, КЭ - Berkana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={(headerStyle, pathStyle)}>
        <HeadNav pageName="Злактерр, КЭ" style={style} pathStyle={pathStyle} />
        <div className="page-content">
          <div className="page-content-wrapper">{jsx_content_wrapped}</div>
        </div>
      </Layout>
    </>
  );
};

export default zlakterrke;
